	PROGRAM DNANDDC
C
C	THIS CALCULATES STUFF FROM DENISSE AND DELCROIX, EQ(11) OF
C		APPENDIX 2, THE 4 X 4 SYMMETRIC DETERMINANT
C		PUC AND PLC ARE P upper case and lower case
C		LUC AND LLC same
C	IT FINDS THE ROOTS Y, AND USES THE SAME INPUTS AS OSCARS
C	HOWEVER, DENISSE AND DELCROIX START WITH W AND FIND K,
C		WHICH IS TAKEN TO BE THE Z DIRECTION
C		ALSO, ONLY ONE ELECTRON AND ONE ION COMPONENT ARE
C		ALLOWED
C

      DIMENSION RATIOM(10),DENS(10),BETAZ(10),TPAR(10),TPERP(10)
      DIMENSION XKPL(4)
      CHARACTER*4 NAME(70)
      COMMON /DISBLK/ RATIOM,BETAZ,TPAR,TPERP,DENS  
      COMMON /DATABL/ XD(70)
      EQUIVALENCE (XD(1),WR),(XD(2),WI),(XD(3),WCYCL),(XD(4),XKX)
      EQUIVALENCE (XD(5),XKZ),(XD(7),RW),(XD(8),RKX),(XD(9),RKZ)
      EQUIVALENCE (XD(13),END1),(XD(14),END2)
      DATA NAME /'  WR','  WI',' WCE','  KX','  KZ',' KIT','  RW',
     1' RKX',' RKZ','MODE',' NPR','  NC','END1','END2',6*'    ',
     2 10*'RMAS',10*'DENS',10*'BETA',10*'TPAR',10*'TPRP'/
C
	DOUBLE PRECISION M4X4(4,4),EVAL(4),EVECT(4,4),T2(4)
	DOUBLE PRECISION LUC,LLC,LUC2,LLC2
	DOUBLE PRECISION TUC,TLC,TUC2,TLC2
	DOUBLE PRECISION PUC,PLC,DUC,DLC
	DOUBLE PRECISION RTEPSE,RTEPSI,ONE,ARG
	DATA NPR /1/
C
	OPEN(UNIT=3,NAME='OSCARD.DAT',TYPE='OLD')
	READ (3,106) WR,WI,WCYCL,XKX,XKZ,RW,RKX,RKZ,NC,KIT,MODE
C	PRINT   106, WR,WI,WCYCL,XKX,XKZ,RW,RKX,RKZ,NC,KIT,MODE
	WRITE(6,105) WR,WI,WCYCL,XKX,XKZ,RW,RKX,RKZ,NC,KIT,MODE
 105	FORMAT(8E12.5,3I3)
 106	FORMAT(5F10.5,3F5.3,3I2)
	READ(3,101)(RATIOM(I),DENS(I),BETAZ(I),TPAR(I),TPERP(I),I=1,NC)
C	PRINT  101,(RATIOM(I),DENS(I),BETAZ(I),TPAR(I),TPERP(I),I=1,NC)
	WRITE(6,1011)(RATIOM(I),DENS(I),BETAZ(I),TPAR(I),TPERP(I),I=1,NC)
 101	FORMAT(5E10.4)
 1011	FORMAT(5E12.4)
	CLOSE(UNIT = 3)
      XD(12) = NC
      XD(6) = KIT
      XD(10) = MODE
      XD(11) = NPR
C
      WR0 = WR/RW**(KIT/2)
      WR = WR0
      DO NWR = 1,2*KIT
	WR = WR*RW
	GAMMAE = 1.
	GAMMAI = 3.
	PLC = 1./WR
	PUC = PLC/SQRT(RATIOM(2))
	THETA = ATAN2(XKX,XKZ)
	XK = SQRT(XKX**2 + XKZ**2)
	LLC = WCYCL*COS(THETA)/WR
	LUC = LLC/ABS(RATIOM(2))
	TLC = WCYCL*SIN(THETA)/WR
	TUC = TLC/ABS(RATIOM(2))
	TLC2 = TLC**2
	TUC2 = TUC**2
	PLC2 = PLC**2
	PUC2 = PUC**2
	LLC2 = LLC**2
	LUC2 = LUC**2
	DLC = ONE - LLC2
	DUC = ONE - LUC2
	ARG = DBLE(GAMMAE*(TPAR(1)/3. + 2.*TPERP(1)/3.))
	RTEPSE = ONE/DSQRT(ARG)
	ARG = DBLE(GAMMAI*(TPAR(2)/3. + 2.*TPERP(2)/3.))
	RTEPSI = ONE/DSQRT(ARG)
C
	ONE = 1.D00
	M4X4(1,1) = ONE - PLC2/DLC - PUC2/DUC
	M4X4(1,2) = PUC2*LUC/DUC - PLC2*LLC/DLC
	M4X4(2,1) = M4X4(1,2) 
	M4X4(1,3) = -RTEPSE*PLC*TLC/DLC
	M4X4(1,4) =  RTEPSI*PUC*TUC/DUC
	M4X4(3,1) = M4X4(1,3) 
	M4X4(4,1) = M4X4(1,4) 
	M4X4(2,2) = M4X4(1,1)
	M4X4(2,3) = M4X4(1,3)*LLC
	M4X4(2,4) = -M4X4(1,4)*LUC
	M4X4(3,2) = M4X4(2,3) 
	M4X4(4,2) = M4X4(2,4) 
	M4X4(3,3) = RTEPSE**2*(1. - PLC2 - TLC2/DLC) 
	M4X4(3,4) = -RTEPSE*RTEPSI*PUC*PLC 
	M4X4(4,3) = M4X4(3,4) 
	M4X4(4,4) = RTEPSI**2*(1. - PUC2 - TUC2/DUC) 
C
	IF(NWR.EQ.1) THEN
	  PRINT*,(M4X4(1,I),I=1,4)
	  PRINT*,(M4X4(2,I),I=1,4)
	  PRINT*,(M4X4(3,I),I=1,4)
	  PRINT*,(M4X4(4,I),I=1,4)
	ENDIF
C
C	NOW FIND THE EIGENVALUES AND EIGENVECTORS
C
	NP = 4
C	CALL JACOBI(M4X4,NP,NP,EVAL,EVECT,NROT)
	CALL JACOBI(M4X4,NP,NP,EVAL,EVECT,NROT)
C
C	CALL TRED2(M4X4,NP,NP,EVAL,T2)
C	DO I = 1,NP
C	  DO J = 1,NP
C	    EVECT(I,J) = M4X4(I,J)
C	  ENDDO
C	ENDDO
C	CALL TQLI(EVAL,T2,NP,NP,EVECT)
C
	DO N = 1,NP
	  XKSOL2 = WR**2*EVAL(N)
	  XKSOL = 0.
	  IF(XKSOL2.GT.0.) THEN
	    XKSOL = SQRT(XKSOL2)
	    XKPL(N) = ALOG(XKSOL)
	  ELSE
	    XKSOL = -SQRT(-XKSOL2)	
	    XKPL(N) = -4.
C	    IF(XKSOL.NE.0.) XKPL(N) = -ALOG(-XKSOL)
	  ENDIF
	  PRINT*,WR,XKSOL,EVAL(N)
C	  XKPL(N) = XKSOL
C	  WRITE(88,*) WR,XKSOL,EVAL(N)
	ENDDO
	WRITE(88,*) WR,XKPL
C
      ENDDO				! END OF WR LOOP
	STOP
	END
