	PROGRAM EPSTEST
C
C	TEST SMALL EPSILON APPROX TO DISERSION RELATION, STERO-CASSINI NB P.84
C
	COMPLEX ROOT(3)
	REAL POLY(40)
C
	DATA TPAR /.15E-4/
	DATA WRSAVE,XKSAVE /1.0014,7.13/
	DATA VGP0 /-1./
	DATA WCYCL /.0062/
C	DATA ANG /11.1/
	DATA ANG /0./
c
	XK = 1.
	RATIO = 1.1
	XK = XK*RATIO
	I = 1
C	DO I = 1,5
	  XK =XK/RATIO
C	  USE CUBIC, COLD PLASMA
	  A = -XK**2
	  B = (XK**2 - WCYCL**2)/4.
	  C = ((WCYCL*XK*SIND(ANG))**2)/8.
	  EPS = .005
	  RATEPS = 1.1
	  EPS = EPS/RATEPS
	  DO J = 1,60
	     EPS = EPS*RATEPS
	     POLY(I) = EPS**3 + A*EPS**2 + B*EPS + C
	     WRITE(27,1026) EPS,POLY(I)
	  ENDDO
C	  CALL CUBIC(A,B,C,ROOT) 
C	  PRINT*,'ROOTS',ROOT
C	  PRINT*,'XK,A,B,C',XK,A,B,C
C	  WRITE(26,1026) XK,ROOT
 1026	FORMAT(F6.3,6E12.3)
C	ENDDO
	STOP
	END
