	PROGRAM FORSLUND
C
C	CALCULATES REDUCED DISTRIBUTION FUNCTION FOR ION,ECORE,EHALO
C		AND ITS DERIVATIVE
C
	DATA EMASS /.91094E-28/
	DATA EVME /.511E6/
	DATA AION /1836./
	DATA TION,TCEV,THEV /10., 10., 80./
	DATA RN0C,RN0H /.95,.05/
	DATA BOLTZK /1.3807E-16/
	DATA QE /1.602177E-19/
	DATA CLIGHT /3.E5/		! KM/SEC
	DATA PI /3.14159265/
	DATA VCOREF /3.5/
C
C      VTE = SQRT(BOLTZK*TPARDEG/EMASS)
C      PRINT*,'VTE',VTE
	PRINT*,' TC, TH, TI', TCEV,THEV,TION,' eV'
	VTI = SQRT(2.*TION/EVME/AION)*CLIGHT
	VTC = SQRT(2.*TCEV/EVME)*CLIGHT
	VTH = SQRT(2.*THEV/EVME)*CLIGHT
	PRINT*,'VTC,VTH,VTI',VTC,VTH,VTI
	VC = -VCOREF*VTI
	VH = -VC*RN0C/RN0H
	PRINT*,'VCORE,VHALO',VC,VH
	SQMR = SQRT(AION)
	TRC = (TION/TCEV)**1.5
	TRH = (TION/THEV)**1.5
	VMAX = 0.
	VMIN = -VTC
	NV = 100
	RATIO = ALOG(ABS(VMIN))/(NV-1)
	PRINT*,'LOG RATIO',RATIO
	RATIO = EXP(RATIO)
	PRINT*,'RATIO',RATIO
	VEL = VMIN
	DO N = 1,NV
	  DIST = EXP(-(VEL/VTI)**2)/AION/VTI
	  DIST = DIST + RN0C*EXP(-((VEL-VC)/VTC)**2)/VTC
	  DIST = DIST + RN0H*EXP(-((VEL-VH)/VTH)**2)/VTH
	  DF = SQMR*VEL*EXP(-(VEL/VTI)**2)
	  DF = DF + (VEL-VC)*RN0C*TRC*EXP(-((VEL-VC)/VTC)**2)
	  DF = DF + (VEL-VH)*RN0H*TRH*EXP(-((VEL-VH)/VTH)**2)
	  DF = -DF
	  WRITE(69,*) VEL,DIST,DF
	  VEL = VEL/RATIO
	ENDDO
       STOP
       END
