	PROGRAM FTEST
C
C	THIS PROGRAM COMPARES THE RESULTS OF SUBROUTINE F, TAKEN FROM
C	OSCARS, AND A DOUBLE PRECISION VERSION OF IT
C	THE OUTPUTS CAN BE COMPARED WITH FRIED AND CONTE IF XKZ = 1
C	AND TP = .5, SO THAT ZTR + i ZTI IS EQUAL TO F & C'S ZETA
C
	DIMENSION ZETAR(40),ZETAI(40),DZETAR(40),DZETAI(40)
	DATA ZETAR /40*0./
	DATA ZETAI /40*0./
C
	XKZ = 1.
	TP = .5
	BZ = 0.
	NX = 88
	NX = 6
	NX = 30
	NX = 40
C	NY = 61
	NY = 21
	NXHALF = NX/2
	NYHALF = NY/2
C
C	SPECIAL TEST FOR ERROR IN F DOUBLE PRECISION
C		NOTE F AND FOLD RETURN ZETA TIMES F0, ETC. 
	ZTI = -.1
c	ZTI =  0.
	DO  I = 0,NX
	    ZTR = 2.0 +.1*I
C	    ZTI = -ZTR
	    CALL F(ZTR,ZTI,TP,XKZ,BZ,F0R,F0I,F1R,F1I,F2R,F2I)
	    DZETAR(I+1) = -QI(F0R,F0I,ZTR,ZTI)
	    DZETAI(I+1) =  QR(F0R,F0I,ZTR,ZTI)
	ENDDO
	IF(1) STOP
C
C	WRITE(7,102) ZTI,(ZETAR(K),K=1,7)
C	WRITE(8,102) ZTI,(ZETAI(K),K=1,7)
C
C	end of special test
C
C	SPECIAL TEST FOR ERROR IN F DOUBLE PRECISION
C		NOTE F AND FOLD RETURN ZETA TIMES F0, ETC. 
	ZTI = -.1
	ZTI =  0.
	DO  I = 0,NX
	    ZTR = 2.0 +.1*I
	    CALL F(ZTR,ZTI,TP,XKZ,BZ,F0R,F0I,F1R,F1I,F2R,F2I)
	    DZETAR(I+1) = -QI(F0R,F0I,ZTR,ZTI)
	    DZETAI(I+1) =  QR(F0R,F0I,ZTR,ZTI)
	    CALL FOLD(ZTR,ZTI,TP,XKZ,BZ,F0R,F0I,F1R,F1I,F2R,F2I)
	    ZETAR(I+1) = -QI(F0R,F0I,ZTR,ZTI)
	    ZETAI(I+1) =  QR(F0R,F0I,ZTR,ZTI)
	    K = I+1
	    WRITE(7,103) ZTR,ZTI,ZETAR(K),ZETAI(K),DZETAR(K),
     1       DZETAI(K),ABS(ZETAR(K)-DZETAR(K)+ZETAI(K)-DZETAI(K))
	    WRITE(8,103) ZTI,ZETAI(K)
	ENDDO
C	WRITE(7,102) ZTI,(ZETAR(K),K=1,7)
C	WRITE(8,102) ZTI,(ZETAI(K),K=1,7)
C
C	end of special test
C
C	TEST OF F2, COMPARING WITH Z' of Fried and Conte
C
	ZTI = -.1
	ZTI =  0.
	DO  I = 0,NX
	    ZTR = 1.9 +.1*I
	    ZT2R = PR(ZTR,ZTI,ZTR,ZTI)
	    ZT2I = PI(ZTR,ZTI,ZTR,ZTI)
	    CALL F(ZTR,ZTI,TP,XKZ,BZ,F0R,F0I,F1R,F1I,F2R,F2I)
	    ZPRIMER =  4.*TP*QI(F2R,F2I,ZT2R,ZT2I)
	    ZPRIMEI = -4.*TP*QR(F2R,F2I,ZT2R,ZT2I)
C	    ZPRIMER = -TP*F2I
C	    ZPRIMEI =  TP*F2R
	    WRITE(9,103) ZTR,ZTI,ZPRIMER,ZPRIMEI
	ENDDO
	IF(1) STOP
C
C	DO 10 J = 0,NY
	  ZTI = J-NYHALF
C	PRINT 102, ZTI,ZTI
	  DO  I = 0,NX
	    ZTR = .1*I
	CALL F(ZTR,ZTI,TP,XKZ,BZ,F0R,F0I,F1R,F1I,F2R,F2I)
C	CALL FOLD(ZTR,ZTI,TP,XKZ,BZ,FD0R,FD0I,FD1R,FD1I,FD2R,FD2I)
C	WRITE(7,100) ZTR,F0R,F0I,FD0R,FD0I,ABS(F0R)+ABS(F0I)
C     1    -ABS(FD0R) - ABS(FD0I)
C	print 101, ZTR,F0R,F0I,FD0R,FD0I,ABS(F0R)+ABS(F0I)
C     1    -ABS(FD0R) - ABS(FD0I)
C	     ZETAR(J+1) = -FD0I
C	     ZETAI(J+1) = FD0R
	     IF(ABS(ZTR)+ABS(ZTI).NE.0.) THEN
	       ZETAR(I+1) = -QI(F0R,F0I,ZTR,ZTI)
	       ZETAI(I+1) =  QR(F0R,F0I,ZTR,ZTI)
	     ENDIF
	  ENDDO
	WRITE(7,102) ZTI,(ZETAR(K),K=1,7)
	WRITE(8,102) ZTI,(ZETAI(K),K=1,7)
  10	CONTINUE
C	DO 20 I = 1,20
C	ZTR = I
C	CALL Z(ZTR,ZTI,ZR,ZI,DZR,DZI)
C	WRITE(7,100) ZTR,ZTI,ZR,ZI,DZR,DZI
C  20	CONTINUE
 100	FORMAT(5E15.7,E12.3)
 101	FORMAT(5E13.5,E12.3)
 102	FORMAT(F6.1,7E13.5)
 103	FORMAT(2F6.1,5E14.6)
	STOP
	END

