	SUBROUTINE LILOPLOT(NPT,ITER,BX,BY,XX,YY,ZZ)
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PXDEF,PYDEFF,COFFMGO,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PIMGO,USERVAR(10),AUTODOT
	COMMON /FREQS/ NC,FC(10),FP,FLH,FUH
C
        DIMENSION XX(1),YY(1),ZZ(1)
C
C	ITER NE 0 IS TERMINAL, ITER = 0 IS HARDCOPY
C
	YMINA = -BY
	YMAXA = BY
	XMINA = XX(1)
	XMAXA = XMINA
	XMIN = ALOG10(ABS(XX(1)))
	XMAX = XMIN
	DO N = 1,NPT
	YMINA = AMIN1(YMINA,YY(N))
	YMINA = AMIN1(YMINA,ZZ(N))
	YMAXA = AMAX1(YMAXA,YY(N))
	YMAXA = AMAX1(YMAXA,ZZ(N))
	YY(N) = FLILO(YY(N),BY)
	ZZ(N) = FLILO(ZZ(N),BY)
	XMINA = AMIN1(XX(N),XMINA)
	XMAXA = AMAX1(XX(N),XMAXA)
	ENDDO
	NYMIN = ALOG10(-YMINA)
	YMINT = -(NYMIN+1)
	NYMAX = ALOG10(YMAXA)
	YMAXT = NYMAX + 1
	PRINT*,'MIN AND MAX OF     FREQ',XMINA,XMAXA
	PRINT*,'MIN AND MAX OF       Y',YMINA,YMAXA
	PRINT*,'INTEGER MIN AND MAX OF LOG10 Y',YMINT,YMAXT

C
C	LEAVE SPACE AT END
	XMAX = XMAX + .7
        CALL MGOINIT
        IF(ITER.NE.0) CALL MGOSETUP(3)                       !TERMINAL
        IF(ITER.EQ.0) CALL MGOSETUP(-6)                       !LASER PRINTER
        CALL MGOERASE
        !CALL MGOWINDOW(2,1,1)
	YMAXL = FLILO(10.**YMAXT,BY)
	YMINL = -FLILO(10.**(-YMINT),BY)
	PRINT*,'MIN AND MAX OF Y LIMITS',YMINL,YMAXL
 	print*,'user limits',x1,x2,y1,y2
 	print*,'dev limits',gx1,gx2,gy1,gy2
C	TOP AND BOTTOM
	IF(XMINA*XMAXA.GT.0.) THEN
	DO N = 1,NPT
 	 XX(N) = ALOG10(ABS(XX(N)))
	 XMIN = AMIN1(XX(N),XMIN)
	 XMAX = AMAX1(XX(N),XMAX)
	ENDDO
         CALL MGOSETLIM( XMIN,YMINL,XMAX,YMAXL)
	 CALL MGOAXIS(XMIN,XMAX,-1.,-1.,GX1,GY1,GX2,GY1,101,0)
	 CALL MGOAXIS(XMIN,XMAX,-1.,-1.,GX1,GY2,GX2,GY2,100,1)
	ELSE
	DO N = 1,NPT
 	 XX(N) = FLILO(XX(N),BX)
	 XMIN = AMIN1(XX(N),XMIN)
	 XMAX = AMAX1(XX(N),XMAX)
	ENDDO
	 NXMIN = ALOG10(-XMINA)
	 XMINT = -(NXMIN+1)
	 NXMAX = ALOG10(XMAXA)
	 XMAXT = NXMAX + 1
	 XMAXL = FLILO(10.**XMAXT,BX)
	 XMINL = -FLILO(10.**(-XMINT),BX)
         CALL MGOSETLIM( XMINL,YMINL,XMAXL,YMAXL)
	 BL = ALOG10(BX)                          ! FIRST LABEL
	 CALL MGORELOCATE(BX,GY1)
	 XB2 = GX
C	TOP AND BOTTOM
	 CALL MGOAXIS(BL,XMAXT,-1.,-1.,GX,GY1,GX2,GY1,100,0)
	 CALL MGORELOCATE(BX,GY1)
	 CALL MGOAXIS(BL,XMAXT,-1.,-1.,GX,GY2,GX2,GY2,100,1)
	 CALL MGORELOCATE(-BX,GY1)
	 XB1 = GX
	 CALL MGOAXIS(BL,-XMINT,-1.,-1.,GX,GY1,GX1,GY1,100,1)
	 CALL MGORELOCATE(-BX,GY2)
	 CALL MGOAXIS(BL,-XMINT,-1.,-1.,GX,GY2,GX1,GY2,100,0)
C	DO LINEAR PART
	 CALL MGOAXIS(-BX,BX,BX,BX,XB1,GY1,XB2,GY1,101,0)
	 CALL MGOAXIS(-BX,BX,BX,BX,XB1,GY2,XB2,GY2,100,1)
	ENDIF
C	SIDES
	BL = ALOG10(BY)                          ! FIRST LABEL
	CALL MGORELOCATE(GX1,BY)
	CALL MGOAXIS(BL,YMAXT,-1.,-1.,GX1,GY,GX1,GY2,100,1)
	CALL MGORELOCATE(GX1,BY)
	CALL MGOAXIS(BL,YMAXT,-1.,-1.,GX2,GY,GX2,GY2,100,0)
	CALL MGORELOCATE(GX1,-BY)
	CALL MGOAXIS(BL,-YMINT,-1.,-1.,GX1,GY,GX1,GY1,100,0)
	CALL MGORELOCATE(GX1,-BY)
	CALL MGOAXIS(BL,-YMINT,-1.,-1.,GX2,GY,GX2,GY1,100,1)
C	DO LINEAR PART
	CALL MGORELOCATE(GX1,BY)
	YB2 = GY
	CALL MGORELOCATE(GX1,-BY)
	YB1 = GY
	CALL MGOAXIS(-BY,BY,BY,BY,GX1,YB1,GX1,YB2,102,1)
	CALL MGOAXIS(-BY,BY,BY,BY,GX2,YB1,GX2,YB2,100,0)
        CALL MGOCONNECT(XX,YY,NPT)
	CALL MGOSETLTYPE(2)
        CALL MGOCONNECT(XX,ZZ,NPT)
	CALL MGOSETLTYPE(0)
        CALL MGOXLABEL(14,'FREQUENCY (HZ)')
        CALL MGOYLABEL(5,' DEQ ')
C
        IF(ITER.NE.0) CALL MGOTIDLE
	IF(ITER.EQ.0) CALL MGOPRNTPLOT(NVEC)
        RETURN
        END

 

