	PROGRAM MHD
C
C	DATA VS,VA /1.76,1.00/		! cs>va for nice, ratio to Va
	DATA VS,VA /0.80,1.00/		! va>cs for nice, ratio to Va
C
C	THE FOLLOWING MAKES A TABLE FOR PLOTTING USING MHD.MGO
C
	XMAX = 0.
	YMAX = 0.
	DO N = 1,91
	  THETA = N-1
	  COSTH = COSD(THETA)
	  CALL MHDDISPER(VS,VA,COSTH,XN12,XN22,XN32,V1,V2,V3)
	  X1 = V1*SIND(THETA)
	  Y1 = V1*COSD(THETA)
	  X2 = V2*SIND(THETA)
	  Y2 = V2*COSD(THETA)
	  X3 = V3*SIND(THETA)
	  Y3 = V3*COSD(THETA)
	  XMAX = AMAX1(XMAX,X1,X2,X3)
	  YMAX = AMAX1(YMAX,Y1,Y2,Y3)
	  WRITE(77,1077) X1,Y1,X2,Y2,X3,Y3
 1077	  FORMAT(6E12.4)
	ENDDO
	PRINT*,'XMAX,YMAX',XMAX,YMAX
C	
	STOP
	END
	SUBROUTINE MHDDISPER(VS,VA,COSTH,XN12,XN22,XN32,V1,V2,V3)
C
C	I GOT THIS FROM EQ. 3-33, PAGE 66, OF SPITZER, PHYSICS OF FULLY
C		IONIZED GASES, 2ND ED.
C	XN1 IS INDEX OF REFRACTION OF ALFVEN WAVE. 
C	XN2
C	XN3
C
	IF(COSTH.NE.0.) THEN
	  V1 = VA*COSTH
	  XN12 = 1./V1**2
	  COMMONF = (VA**2 + VS**2)/(VA*VS)**2/COSTH**2
	  DISC = 1.- 4.*(VA*VS*COSTH)**2/(VA**2 + VS**2)*2
	  IF(DISC.GE.0.) THEN
	    DISC = SQRT(DISC)
	  ELSE
	    DISC = 0.
	  ENDIF
	  XN22 = COMMONF*(1. + DISC)
	  XN32 = COMMONF*(1. - DISC)
	ELSE
	  V1 = 0.
	ENDIF
C
C	I GOT THIS FROM EQS 22 AND 23, P 38 OF WEITZNER'S ARTICLE IN
C		BASIC PLASMA PHYSICS, SELECTED CHAPTERS
C	V1 IS THE SPEED OF THE ALFVEN WAVE. 
C	V2 IS THE SLOW MODE
C	V3 IS THE FAST MODE
C
	IF(COSTH.NE.0.) THEN
	  V1 = VA*COSTH
	  XN12 = 1./V1**2
	  COMMONF = (VA**2 + VS**2)
	  DISC = COMMONF**2 - 4.*(VA*VS*COSTH)**2
	  IF(DISC.GE.0.) THEN
	    DISC = SQRT(DISC)
	  ELSE
	    DISC = 0.
	  ENDIF
	  V22 = .5*(COMMONF - DISC)
	  V2 = SQRT(AMAX1(V22,0.))
	  V32 = .5*(COMMONF + DISC)
	  V3 = SQRT(AMAX1(V32,0.))
	ELSE
	  V1 = 0.
	  V2 = 0.
	  V3 = SQRT(VA**2 + VS**2)
	ENDIF
	RETURN
	END
