	PROGRAM OSCPLT
C
C	PLOT RESULTS OF OSCARS RUNS WHICH HAVE BEEN STORED IN FOR008
C
	COMMON /PPAK/ XMIN,XMAX,DELX,YMIN,YMAX,DELY,FILFAC
	DIMENSION RATIOM(10),DENS(10),BETAZ(10),TPAR(10),TPERP(10)
	DIMENSION XX(900),YY(900),ZZ(900),SYM(900)
C
	CALL BITPLTBGN(' ',' ')
	CALL THROW(358)
	OPEN(UNIT=8,FILE='FOR008.DAT',TYPE='OLD')
	XMIN = 0.
	XMAX = 0.
	YMIN = 0.
	YMAX = 0.
	N = 0
	READ (8,105) WR,WI,WCYCL,XKX,XKZ,RW,RKX,RKZ,NC,KIT,MODE
	READ (8,101)(RATIOM(I),DENS(I),BETAZ(I),TPAR(I),TPERP(I),I=1,NC)
	WCI = WCYCL/RATIOM(2)
C
	IF(MODE.GT.6) GO TO 50
C
C	READ IN THE DATA FROM A FILE FOR008.DAT
C
  10	READ (8,361,END=20) WR,WI,DML,DTR,DTI,XKX,XKZ
	N = N+1
C	THE FOLLOWING SET IS FOR RADIUS PROP. TO. WR, DIRECTION OF K
C	I.E.
	WPL = -WI
C	WPL = WR
	XK = SQRT(XKX**2 + XKZ**2)
	XX(N) = WPL*XKX/XK
	YY(N) = WPL*XKZ/XK
C	THE FOLLOWING IS FOR KX VS KZ
C	XX(N) =XKX
C	YY(N) = XKZ
C	SYM(N) = DTR
	YMIN = AMIN1(YMIN,YY(N))
	YMAX = AMAX1(YMAX,YY(N))
	XMIN = AMIN1(XX(N),XMIN)
	XMAX = AMAX1(XX(N),XMAX)
	GO TO 10
C
  20	CONTINUE
C	NOW PLOT THE RESULTS WHICH HAVE BEEN READ IN
C
	NPLT = N
	TEMP = ABS(YMIN)
	NTEMP = TEMP
	TEMP = NTEMP+1
C 	XMAX = XMAX/WCI
C	XMIN = XMIN/WCI
	DO 21 N = 1,NPLT
C  	YY(N) = (YY(N) + TEMP)*SYM(N)
C	XX(N) = XX(N)/WCI
	SYM(N) = 1.
  21	CONTINUE
	PRINT*,'NPLT',NPLT
	XMAX = AMAX1(ABS(YMAX),ABS(YMIN),ABS(XMAX))
C	YMIN = -YMAX
	YMIN = 0.
	DELX = .1E-6
	xmin = 0.
	xmax = .3e-6
	ymax = xmax
	xmax = 1.143*xmax
	FILFAC = 1.
	DELY = DELX
	PRINT*,'XMIN, ETC',XMIN,XMAX,YMIN,YMAX
C	PRINT*,(XX(I),YY(I),I=1,NPLT)
	CALL LGRAPH(NPLT,XX,YY,SYM)
	CALL BPLTERM
 105	FORMAT(8E12.5,3I3)
 106	FORMAT(5F10.5,3F5.3,3I2)
 101	FORMAT(5E10.4)
  361 FORMAT (1X,E12.6 ',' E10.3,1X,F8.3,F8.3,',',F7.3,E12.4 ',' E11.4)
	STOP
C
C	READ IN THE DATA FROM A FILE FOR008.DAT--MODE GT 6
C
  50	READ (8,361,END=60) WR,WI,DML,DTR,DTI,XKX,XKZ
	N = N+1
	XX(N) = XKX
	YY(N) = XKZ
	ZZ(N) = WI
	YMAX = AMAX1(YMAX,YY(N))
	XMAX = AMAX1(XX(N),XMAX)
	GO TO 50
C
  60	CONTINUE
C	NOW PLOT THE RESULTS WHICH HAVE BEEN READ IN
C
	FILFAC = 1.
	NPLT = N
C
C	PLOT CONSTANT W CONTOUR IN K SPACE
C
	XMAX = 0.
	YMAX = 0.
	DO 62 N = 1,NPLT
	YMAX = AMAX1(YMAX,YY(N))
	XMAX = AMAX1(XX(N),XMAX)
	SYM(N) = 1.
  62	CONTINUE
	PRINT*,'NPLT',NPLT,' X,YMAX',XMAX,YMAX
	YMAX = AMAX1(ABS(YMAX),ABS(XMAX))
	XMAX = AMAX1(ABS(YMAX),ABS(XMAX))
	XMAX = 1.2*XMAX
	YMAX = 1.2*YMAX
	XMAX = 1.140*XMAX
	DELX = .1*XMAX
	NXMAX = (ALOG10(DELX) + 50.)
	DELX = 10.**(NXMAX-50)
	DELY = DELX
	CALL PRINTXX(7,'CONST W',1,420)
	CALL PRINTXX(6,'KZ',1,400)
	CALL LGRAPH(NPLT,XX,YY,SYM)
C
C	PLOT IMAGINARY PART OF FREQUENCY
C
	XMAX = 0.
	YMAX = 0.
	DO 61 N = 1,NPLT
C 	YY(N) = (YY(N) + TEMP)*SYM(N)
C	XX(N) = XX(N)/WCI
	XK = SQRT(XX(N)**2 + YY(N)**2)
	IF(XK.EQ.0.) XK = 1.
	WI = ZZ(N)/WCI
 	YY(N) = -WI*YY(N)/XK
	XX(N) = -WI*XX(N)/XK
	YMAX = AMAX1(YMAX,YY(N))
	XMAX = AMAX1(XX(N),XMAX)
	SYM(N) = 1.
  61	CONTINUE
	PRINT*,'NPLT',NPLT,' X,YMAX',XMAX,YMAX
	YMAX = AMAX1(ABS(YMAX),ABS(XMAX))
	XMAX = AMAX1(ABS(YMAX),ABS(XMAX))
	XMAX = 1.2*XMAX
	YMAX = 1.2*YMAX
	XMAX = 1.140*XMAX
	DELX = .01
	DELY = DELX
	CALL PRINTXX(6,'WI/WCI',1,400)
	CALL LGRAPH(NPLT,XX,YY,SYM)
C
	CALL BPLTERM
	STOP
	END
