	PROGRAM PROCESS15
C
C	PROCESSES FILE FOR015.DAT, WRITTEN BY OSCARS, CONTAINING DATA TO
C		BE USED IN MODE STUDY.
C
	REAL RATIOM(10),DENS(10),BETAZ(10),TPAR(10),TPERP(I)
	REAL XDATA(15,500)
C
	OPEN(UNIT=15,FILE='FOR015.DAT',STATUS='OLD',READONLY)
	READ(15,*) WR,WI,WCYCL,XKX,XKZ,RW,RKX,RKZ,NC,KIT,MODE
	READ(15,1011)(RATIOM(I),DENS(I),BETAZ(I),TPAR(I),TPERP(I),I=1,NC)
 1011	FORMAT(5E12.4)
	NR = 0
C
 100	CONTINUE
     	READ(15,*,ERR=150,END=200) WR,WI,XK,ANG,BZR,BZI,BMAG,EDENSR,
     1	EDENSI,HDENSR,HDENSI,HIDENSR,HIDENSI,DBRATIOR,DBRATIOI
	NR = NR+1
	XDATA(1,NR) = WR
	XDATA(2,NR) = WI
	XDATA(3,NR) = XK
	XDATA(4,NR) = ANG
	XDATA(5,NR) = BZR
	XDATA(6,NR) = BZI
	XDATA(7,NR) = BMAG
	XDATA(8,NR) = EDENSR
	XDATA(9,NR) = EDENSI
	GO TO 100
 150	CONTINUE
	PRINT*,'ERROR IN READ AT NR = ',NR
 200	CONTINUE
	STOP
	END
