	PROGRAM SHZMGO
C
C	PLOTS GRAPH FOR PAPER ON ION SHEATH IMPEDANCE
C
	CHARACTER*50 COM(20)
	DIMENSION PLT(6,50)
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PXDEF,PYDEFF,COFFMGO,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PIMGO,USERVAR(10),AUTODOT
C
C	ITERM = 3 FOR TERMINAL, -5 or -6 FOR PRINTER 
	DATA ITERM /-6/
C
	IF(ITERM.GT.0) THEN
	  COM(1) = 'TERMINAL 3'
	  NCOM = 2
	ELSE
	  COM(1) = 'PRINTER 6'
	  NCOM = 2
	ENDIF
	COM(NCOM) = 'DATA FOR018.DAT;3'
	NCOM = NCOM+1
C	COM(NCOM) = 'INPUT SHZMGO.MGO'
	COM(NCOM) = 'INPUT SHZMGO.IMG'
	CALL MONGO(NCOM,COM,6,50,PLT)
C
	NCOM = 1
	COM(NCOM) = 'DATA FOR018.DAT;4'
	NCOM = NCOM+1
C	COM(NCOM) = 'INPUT SHZMGO.MGO'
	COM(NCOM) = 'INPUT SHZMGO.IMG'
	CALL MONGO(NCOM,COM,6,50,PLT)
C
	NCOM = 1
	COM(NCOM) = 'DATA FOR018.DAT;5'
	NCOM = NCOM+1
C	COM(NCOM) = 'INPUT SHZMGO.MGO'
	COM(NCOM) = 'INPUT SHZMGO.IMG'
C
	IF(ITERM.LT.0) THEN
	 NCOM = NCOM+1
	 COM(NCOM) = 'HARDCOPY'
	ENDIF
	NCOM = NCOM+1
	COM(NCOM) = 'END'
	CALL MONGO(NCOM,COM,6,50,PLT)
  120	STOP
	END
