	PROGRAM CHAMBR
C
C	COMPUTES POTENTIAL IN A PLASMA CHAMBER
C
      COMMON /PPAK/ XMIN,XMAX,DELX,YMIN,YMAX,DELY,FILFAC
      COMMON /PARAMS/ FCE,PTORR,VBEAM,BEAMI,SECEMC,ESEC,IPR
      COMMON /RESULT/ DENSE,DENSI,RLBE,RLSEC,RLI
      DIMENSION RADIUS(700),POTL(700),SYM(700),EXTRA(700)
	DATA IPR /1/
	DATA POTL /700*0./
	DATA EXTRA/700*0./
C
	YMAX = 0.
	YMIN = 0.
	DELY = 1.
	BEAMIS = BEAMI
	DO 200 N = 1,10
	BEAMI = N*35.E-6
	PRINT*,'FCE,PTORR,BEAMV,BEAMI',FCE,PTORR,VBEAM,BEAMI
	PRINT*,'SEC EM COEF, E SEC',SECEMC,ESEC
	CALL WOMPOT(0.,POTE,POTI,POT,E)
 200	CONTINUE
	IPR = 0
	BEAMI = BEAMIS
	PRINT*,' '
	PRINT*,'FCE,PTORR,BEAMV,BEAMI',FCE,PTORR,VBEAM,BEAMI
C	STOP
	DO 100 N = 1,531
	R = -40. + 80.*(N-1)/530
	RADIUS(N) = R
	CALL WOMPOT(R,POTE,POTI,POT,E)
	YMAX = AMAX1(POT,YMAX)
	YMIN = AMIN1(POT,YMIN)
	SYM(N) = 1.
	POTL(N) = POT
	EXTRA(N) = E
	EMAX = AMAX1(EXTRA(N),EMAX)
	EMIN = AMIN1(EXTRA(N),EMIN)
  100	CONTINUE
	CALL BITPLTBGN(' ',' ')
	CALL THROW(358)
	XMAX = 50.
	XMIN = -50.
	DELX = 5.
	YMAX = 3.*YMAX
	YMIN = 3.*YMIN
	FILFAC = 1.
C
C	MARK ELECTRON AND ION RADII
	NPT = 531
	NPT = NPT + 1
	RADIUS(NPT) = 2.*SQRT(RLBE**2 + RLSEC**2)
	SYM(NPT) = 5.
	NPT = NPT + 1
	RADIUS(NPT) = -2.*SQRT(RLBE**2 + RLSEC**2)
	SYM(NPT) = 5.
	NPT = NPT + 1
	RADIUS(NPT) = 2.*RLI
	SYM(NPT) = 5.
	NPT = NPT + 1
	RADIUS(NPT) = -2.*RLI
	SYM(NPT) = 5.
	DO N = NPT-3,NPT
	EXTRA(N) = 0.
	POTL(N) = 0.
	ENDDO
C
	CALL PRINTXX(4,' POT',1,400)
	CALL LGRAPH(NPT,RADIUS,POTL,SYM)
	YMAX = 3.*EMAX
	YMIN = 3.*EMIN
	DELY = 100.
	FILFAC = 1.
	CALL PRINTXX(4,' E',1,400)
	CALL LGRAPH(NPT,RADIUS,EXTRA,SYM)
	CALL BPLTERM
	STOP
	END
	SUBROUTINE WOMPOT(R,POTE,POTI,POT,E)
C
C	COMPUTES POTENTIAL IN WOMBAT
C
	COMMON /PARAMS/ FCE,PTORR,VBEAM,BEAMI,SECEMC,ESEC,IPR
        COMMON /RESULT/ DENSE,DENSI,RLBE,RLSEC,RLI
C	
C	THE FOLLOWING ARE FOR THE WAVEFORM FIGURE
	DATA FCE /25. E6/	!ELECTRON CYCLOTRON FREQUENCY
	DATA PTORR /2.2E-6/	!PRESSURE IN TORR
	DATA VBEAM /100./	!BEAM ENERGY IN ELECTRON VOLTS
C
C	DATA FCE /22.5E6/	!ELECTRON CYCLOTRON FREQUENCY
C	DATA PTORR /1.E-5/	!PRESSURE IN TORR
	DATA SIGMA /2.6E-16/	!IONIZATIONS CROSS SECTION IN CM**2
C	DATA BEAMI /25.E-6/	!BEAM CURRENT IN AMPERES
	DATA BEAMI / 6.E-6/	!BEAM CURRENT IN AMPERES
	DATA MASSI /30./	!ATOMIC WT. OF IONS
	DATA GUNDIV /9./	!GUN DIVERGENCE ANGLE IN DEGREES
	DATA SECEMC /.5/	!SECONDARY EMISSION COEFFICIENT
	DATA ESEC /2./		!ENERGY OF END PLATE SECONDARIES IN EV
C				!DETERMINED FOR CU FROM 
C				! SEAH, SURFACE SCIENCE 17,132-160,(1969)
	DATA RC /40./		!RADIUS OF CONDUCTING WALL IN CM
	DATA AXL /100./		!LENGTH OF INTERACTION REGION
C	
C	THE FOLLOWING ARE FOR ROCKET ELECTRON GUNS
	DATA FCE /1.5 E6/	!ELECTRON CYCLOTRON FREQUENCY
	DATA PTORR /2.2E-6/	!PRESSURE IN TORR
	DATA VBEAM /4000./	!BEAM ENERGY IN ELECTRON VOLTS
	DATA RC /1000./		!RADIUS OF CONDUCTING WALL IN CM
	DATA AXL /1000./		!LENGTH OF INTERACTION REGION
	DATA GUNDIV /1./	!GUN DIVERGENCE ANGLE IN DEGREES
	DATA BEAMI / 6.E-3/	!BEAM CURRENT IN AMPERES
	DATA MASSI /16./	!ATOMIC WT. OF IONS
	DATA SECEMC /0./	!SECONDARY EMISSION COEFFICIENT
C
	DATA QE /4.807E-10/	!ELECTRON CHARGE IN ESU
	DATA C /2.9979E10/	!VELOCITY OF  LIGHT IN CGS
	DATA PI /3.14159265/	
	DATA MEC2 /.51E6/	!M C**2 FOR ELECTRONS IN EV
C
C	FCE = FCE*1.1
C	PRINT*,'FCE',FCE
	QECOUL = 10.*QE/C
	VESU = C*1.E-8			!300 = VOLTS TO ESU
	EPS0 = 1.E11/(4.*PI*C**2)

C	ELECTRON BEAM LARMOR RADIUS
	VE = SQRT(2.*VBEAM/MEC2)*C
	RLBE = VE*SIN(GUNDIV/57.295)/(2.*PI*FCE)

C	SECONDARY ELECTRON LARMOR RADIUS
	VSEC = SQRT(2.*ESEC/MEC2)*C
	RLSEC = VSEC*.5/(2.*PI*FCE)

C	ION COLUMN LARMOR RADIUS AT kT = 26 meV
	VTI = SQRT(2.*.026/(MASSI*1836.*MEC2))*C
	RLI = VTI*1836.*MASSI/(2.*PI*FCE)
	IF(IPR.NE.0)PRINT*,'RLBE,RLSEC,RLI',RLBE,RLSEC,RLI

C	TOTAL NO. OF ELECTRON IN CHAMBER
C	BEAM ELECTRONS
	TOTNBE = (BEAMI/QECOUL)*(AXL/VE)
	VOLE = PI*AXL*((2.*RLBE)**2 + RLSEC**2)
	DENSE = TOTNBE/VOLE
C	SEC. EMISSION ELECTRONS FROM END PLATE
	SECFAC = SECEMC*VE/VSEC
	DENSE = DENSE*(1. + SECFAC)
	IF(IPR.NE.0)PRINT*,'SECFAC,TOTNBE,DENSE',SECFAC,TOTNBE,DENSE
C
C	TOTAL NO. OF IONS IN CHAMBER
C	FIRST COMPUTE NEUTRAL DENSITY
	DENSNT = (6.022E23/23900.)*(PTORR/760.)
C	LIFETIME OF IONS
	TAUI = .5*AXL*1.4142/VTI
	TOTNI = (BEAMI/QECOUL)*AXL*DENSNT*SIGMA*TAUI
	VOLI = PI*AXL*(2.*RLI)**2
	DENSI = TOTNI/VOLI
	IF(IPR.NE.0)PRINT*,'NI,TAUI,DENSI',TOTNI,TAUI,DENSI
C
C	POTENTIAL AND ELECTRIC FIELD
C
	RA = ABS(R)
	IF(RA.GE.(2.*RLBE)) GO TO 10
C	R IS INSIDE THE BEAM
	POTE = -PI*DENSE*QE*(2.*RLBE)**2*
     1  (1. - (.5*R/RLBE)**2 + 2.*ALOG(.5*RC/RLBE))*VESU
	EEL = -2.*PI*DENSE*QE*R*VESU*100.
	GO TO 30
  10	CONTINUE
C	R IS OUTSIDE THE BEAM
	POTE = -PI*DENSE*QE*(2.*RLBE)**2*2.*ALOG(RC/RA)*VESU
	IF(R.NE.0.)
     1	EEL = -2.*PI*DENSE*QE*(2.*RLBE)**2*VESU*100./R
C
  30	IF(RA.GE.(2.*RLI)) GO TO 40
C	IONS,  R IS INSIDE THE BEAM
	POTI =  PI*DENSI*QE*(2.*RLI )**2*
     1  (1. - (.5*R/RLI)**2 + 2.*ALOG(.5*RC/RLI ))*VESU
	EI =  2.*PI*DENSI*QE*R*VESU*100.
	GO TO 50
  40	CONTINUE
C	IONS,  R IS OUTSIDE THE BEAM
	POTI =  PI*DENSI*QE*(2.*RLI )**2*2.*ALOG(RC/RA)*VESU
	IF(R.NE.0.)
     1	EI =  2.*PI*DENSI*QE*(2.*RLI)**2*VESU*100./R
  50	POT = POTE + POTI
	E = EEL + EI
  60	IF(IPR.NE.0) PRINT 1001,'R,POTE,POTI,POT,E',R,POTE,POTI,POT,E
C  60	IF(IPR.NE.0) PRINT 1001,'R,POTE,POTI,POT,E',R,POTE,POTI,POT,E
	IF(IPR.NE.0) WRITE(22,1002) BEAMI,DENSE,DENSI
	RETURN
 1001	FORMAT(1X,A17,F10.3,5F12.4)
 1002	FORMAT(3E13.4)
	END

