	SUBROUTINE LSFIT(Y,X,WT,N,A,B,RMS)
C
C	FIT Y = A*X + B
C
	DIMENSION Y(128),X(128),WT(128)
C
C
	SYY=0.
	SXY=0.
	SXX=0.
	SX=0.
	SY=0.
	SC=0.
	DO 1 J = 1,N
	   SYY=SYY+WT(J)*Y(J)**2
	   SXY=SXY+WT(J)*X(J)*Y(J)
	   SXX=SXX+WT(J)*X(J)**2
	   SX=SX+WT(J)*X(J)
	   SY=SY+WT(J)*Y(J)
	   SC=SC+WT(J)
 1	CONTINUE
	A=0.
	B=0.
	DEN=SXX*SC-SX*SX
	IF(DEN.EQ.0.) TYPE 101
	IF(DEN.EQ.0.) RETURN
	A=(SXY*SC-SY*SX)/DEN
	B=(SXX*SY-SX*SXY)/DEN
	SUMSQ=SYY+SXX*A**2+SC*B**2-2.*SXY*A-2.*SY*B+2.*SX*A*B
	SM=SUMSQ/SC
	RMS=SQRT(AMAX1(SM,0.))
	RETURN
C
C
 101	FORMAT(' VANISHING DETERMINANT IN LSFIT')
	END

