	FUNCTION TDS_FILTER(CHANNEL,FILTER_NO,F)
C
C	CHANNEL IS THE TDS CHANNEL, ITEM - 'CHANNEL', FILTER_NO IS THE NUMBER 
C	RETURNED BY ITEM = 0 FOR HIGHEST CUTOFF FREQUENCY, 3 FOR LOWEST
C
	INTEGER*4 CHANNEL,FILTER_NO
	REAL F, F0(6),FQ(6)
	DATA F0 /9600.,9600.,4*2400./
C
	TDS_FILTER = 1.
	RETURN
	END
