	PROGRAM ANTENNAZ
C
C	CALCULATES RESISTANCE, CAPACITANCE AND SHOT NOISE ON WIND ANTENNAS
C
C	X ANTENNA
	PHYSLEN = 5000.
	EFFLEN = .5*PHYSLEN
	ICS = 1
	TPHI = 1.3		! eV
	TPHI = .7		! eV
	DIA = .038
	DENSE = 7.
	TE = 12.
	RATIO = 1.1
	DENSE = 2.
	DO N = 1,30
	  DENSE = DENSE*RATIO
	  FLUX = DENSE*SQRT(TE)
	  CALL ANTENNA(EFFLEN,PHYSLEN,DIA,ICS,DENSE,TE,TPHI,ANTCURR,
     1		RES,CAP)
	  PRINT*,ANTCURR,RES,CAP
	  WRITE(66,*) DENSE,FLUX,RES
	ENDDO
	STOP
	END
