	PROGRAM APMTEST
C
C	MAKES A FILE OF APMCAL FOR PLOTTING BY APMTEST.MGO
C
	REAL APMV(5)
C
	DO NTM = 0,255
	  DO IPA = 1,5
	    APMV(IPA) = APMCAL(IPA,NTM)
	  ENDDO
	  WRITE(64,1064) NTM,(APMV(J),J=1,5)
 1064	FORMAT(I5,5F9.3)
	ENDDO
	STOP
	END
