	SUBROUTINE BLOBOUT(NDATA,VDATA,IBLOB)
C
	INTEGER*4 NDATA(2048)
	REAL VDATA(2048),ZCROSS(512)
C
C	MOST OF THE EVENTS ARE BLOBS.  TO ELIMINATE THEM:
C	BLOBS START NEAR THE MIDDLE, AND MOSTLY OCCUPY THE
C	SECOND HALF OF AN EVENT.  SO REQUIRE THAT THE MAXIMUM
C	INTERVAL BETWEEN ZEROS IN THE SECOND HALF NOT BE 
C	MORE THAN ?? TIMES THE AVERAGE INTERVAL IN THE FIRST
C	HALF
C
	IBLOB = 0
C
C	FIND ZERO CROSSINGS
C
	IZCNT = 1
	ZCROSS(IZCNT) = 0.
	IL = 1
	IZ = IL
C
C	FIRST HALF OF CHANNEL
C
	DO IL = 1,1023
C
C	    IF(NDATA(IL).EQ.0) PRINT*,'ZERO DATA',IL,NDATA(IL-1),
C     1     NDATA(IL),NDATA(IL+1)
C
C		COUNT ONLY POS TO NEG
C
	    IF(NDATA(IL).GT.128.AND.NDATA(IL+1).LE.128) THEN
	        IZCNT = IZCNT+1
		S1 = NDATA(IL)
		S2 = NDATA(IL+1)
		IF(S1-S2.NE.0.) THEN
	  	   ZCROSS(IZCNT) = IL + S1/(S1-S2)
	  	ELSE
		   ZCROSS(IZCNT) = IL 
		ENDIF	
	    ENDIF
	ENDDO
C
	ZCNT1 = IZCNT
C
	AVR1_1ST_HALF = 1023./ZCNT1
	NZCNT1 = IZCNT
C
	Z1MAX = 0.
	DO N = 1,IZCNT-1
	  Z1INT = ZCROSS(N+1) - ZCROSS(N)
	  Z1MAX = AMAX1(Z1INT,Z1MAX)
C	  IF(Z1INT.EQ.0.) PRINT*,'ZINT=0 AT ',N
	  IF(Z1INT.EQ.0.) Z1INT = 1.E-6
	ENDDO
C
C	SECOND HALF OF CHANNEL 1, BUT NOT QUITE ALL
C
	IEND = 1580
	DO IL = 1024,IEND
C
C		COUNT ONLY POS TO NEG
C
	    IF(NDATA(IL).GT.128.AND.NDATA(IL+1).LE.128) THEN
	        IZCNT = IZCNT+1
		S1 = NDATA(IL)
		S2 = NDATA(IL+1)
		IF(S1-S2.NE.0.) THEN
	  	   ZCROSS(IZCNT) = IL + S1/(S1-S2)
	  	ELSE
		   ZCROSS(IZCNT) = IL 
		ENDIF	
	    ENDIF
	ENDDO
	IZCNT = IZCNT + 1
	ZCROSS(IZCNT) = IEND
C
	AVR1_2ND_HALF = 1023./(IZCNT-NZCNT1)
C
	Z1MAX = 0.
	DO N = NZCNT1,IZCNT-1
	  Z1INT = ZCROSS(N+1) - ZCROSS(N)
	  if(z1int.gt.z1max) then
	     z1max = z1int
	     nnmax = n
	  endif
C	  IF(Z1INT.EQ.0.) PRINT*,'ZINT=0 AT ',N
	  IF(Z1INT.EQ.0.) Z1INT = 1.E-6
	ENDDO
CDIAG	print*,'max int ch 1',z1max,' at',zcross(nnmax),zcross(nnmax+1)
C
C	NOW AVR1_1ST_HALF IS THE AVERAGE INTERVAL, IN NUMBER OF SAMPLES
C	IN THE FIRST HALF OF THE EVENT, AND Z1MAX IS THE MAXIMUM
C	INTERVAL IN THE SECOND HALF.  Z1MAX IS EXPECTED TO BE LARGE
C	FOR BLOBS
C
CDAIG	print*,'zero crossings, ch 1,AVR1_1ST_HALF,Z1MAX',NO_EVT,izcnt,
CDIAG     1		AVR1_1ST_HALF,Z1MAX
	IF(Z1MAX.GT.5.*AVR1_1ST_HALF.AND.Z1MAX.GT.220.) THEN
	  IBLOB = 1
	ENDIF
C
	RETURN
	END
