	PROGRAM DCACCONV
C
C	INPUT IS SIGNAL FROM CHANNELS 7 TO 10
C	OUTPUT IS CALCULATED RESPONSE FROM CHANNELS 3 TO 6, TAKING INTO
C	ACCOUNT THE FREQUENCY RESPONSE OF THE FFTAMP
C
	REAL SIG,DATA(1025)
	COMPLEX FCOEF,CGAIN,CCORR
	COMMON /GAINBLK/ PHASE,CGAIN                   ! PHASE IS IN RADIANS
	real ffund(3)
	data ffund /21.34766,5.336914,.3335571/

C
	ICH = 3
c	SPS = FFUND(2)*1024.
	SPS = FFUND(3)*1024.
C
	OPEN(UNIT=77,NAME='XANT.DAT',TYPE='OLD',READONLY)
	DO NN = 1,1024
	  READ(77,*) J,SIG
	  DATA(NN) = SIG
 	ENDDO
C
	CALL REALFT(DATA,512,1)
C
C	CORRECT FOURIER ANALYSED SIGNAL FOR FREQUENCY RESPONSE
C
	     DO IK = 3,1024,2
		FCOEF = CMPLX(DATA(IK),DATA(IK+1))
	        FREQ = SPS*(IK-1)/2048.
	        EJUNK = FFTAMP(ICH,FREQ)
		FCOEF = FCOEF*CGAIN
		CCORR = CGAIN
		DATA(IK) = FCOEF
		DATA(IK+1) = AIMAG(FCOEF)
		WRITE(79,*) FREQ,CABS(CGAIN),CGAIN
	     ENDDO
C
C	NOW DATA CONTAINS FOURIER COEFFS CORRECTED FOR FREQUENCY RESPONSE
C
	TYPE*,'AFTER CORRECTING'
	TYPE*,(DATA(I),I=1,10)
	TYPE*,(DATA(I),I=1020,1025)
C
C
C
	     CALL REALFT(DATA,512,-1)
	     DO IK = 1,1024
	       DATA(IK) = DATA(IK)/512.
		WRITE(78,*) IK,DATA(IK)
	     ENDDO
	STOP
	END
