	PROGRAM ERRPLOT
C
C	PLOTS VARIOUS HISTOGRAMS FOR TESTING TDS_PHYS
C
	INTEGER*4 NDATA(5),ISCET(2),NUMEVENT,ICH
	REAL      DATA(5)
	CHARACTER*50 COM(20)
	CHARACTER*20 TITLE1(10)
	COMMON /PLOTBLK/ PLDATA(256,2)
C
	DO NW = 1,4
	  OPEN(UNIT=98,FILE='FOR099.DAT',STATUS='OLD',READONLY)
	  NBIN = 256
	  XMIN = -1.
	  XMAX = 1.
	  IF(NW.EQ.1) IWRONG = 71
	  IF(NW.EQ.2) IWRONG = -71
	  IF(NW.EQ.3) IWRONG = 58
	  IF(NW.EQ.4) IWRONG =-58
 	  READ(98,*) ISCET,NUMEVENT,ICH
	  XAMAX = 0.
	  XAMIN = 0.
	  CALL HISTOG(2,X,NBIN,XMIN,XMAX,PCTILE,TOTAL,RET)	!CLEAR
C
 100	  CONTINUE
	  READ(98,*,END=200) NUMBER,NDATA,DATA,FIXED_V
	  IF(NW.EQ.1.AND.NDATA(3).NE.IWRONG) GO TO 100
	  IF(NW.EQ.2.AND.NDATA(3).NE.IWRONG) GO TO 100
	  IF(NW.EQ.3.AND.NDATA(2).NE.IWRONG) GO TO 100
	  IF(NW.EQ.4.AND.NDATA(2).NE.IWRONG) GO TO 100
	  X = (FIXED_V - DATA(3))/DATA(3)	
	  IF(NDATA(2).EQ.58) PRINT 2001,NUMBER,NDATA,X
 2001	  FORMAT(6I6,F9.2)
	  XAMAX = AMAX1(X,XAMAX)
	  XAMIN = AMIN1(X,XAMIN)
	  CALL HISTOG(1,X,NBIN,XMIN,XMAX,PCTILE,TOTAL,RET)
	  GO TO 100
 200	  CONTINUE
	  CLOSE(UNIT=98)
	  PRINT*,'ACTUAL MIN,MAX',XAMIN,XAMAX
	  PCTILE = .5
	  CALL HISTOG(0,X,NBIN,XMIN,XMAX,PCTILE,TOTAL,RET)
C
	IF(NW.EQ.1) THEN
	  WRITE(COM(2),1001) NW
 1001	  FORMAT('WINDOW 2 2 ',I2)
C	  COM(1) = 'TERMINAL 3'
	  COM(1) = 'PRINTER 2'
	  COM(3) = 'RELOCATE .05 .95'
 	  WRITE(COM(4),1020) ISCET,NUMEVENT,ICH,IWRONG
 1020	  FORMAT('LABEL',I10,I10,I10,'  CH',I4,I6)
	  COM(5) = 'INPUT ERRPLOT.MGO'
	  CALL MONGO(5,COM,256,2,PLDATA)
	ELSE
	  WRITE(COM(2),1001) NW
	  COM(3) = 'LIMITS 0. 1. 0. 1.'
	  COM(4) = 'RELOCATE .05 .95'
 	  WRITE(COM(5),1020) ISCET,NUMEVENT,ICH,IWRONG
	  COM(6) = 'INPUT ERRPLOT.MGO'
	  COM(7) = 'HARDCOPY'
	  COM(8) = 'END'
	  ICOM = 6
	  IF(NW.EQ.4) ICOM = 8
	  CALL MONGO(ICOM,COM,256,2,PLDATA)
	ENDIF
	ENDDO
	STOP
	END
	SUBROUTINE HISTOG(ILOAD,X,NBIN,XMIN,XMAX,PCTILE,TOTAL,RET)
C
C	THIS IS A SPECIAL VERSION TO CALCULATE LEVEL AT A CERTAIN PERCENTILE
C
	COMMON /PLOTBLK/ PLDATA(256,2)
	INTEGER*4 NARR(256)
	DATA NARR /256*0/
C
	IF(ILOAD.GT.1) THEN
	  DO N = 1,256
	    NARR(N) = 0
	  ENDDO
	  TOTAL = 0.
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  XT = AMAX1(X,XMIN)
	  XT = AMIN1(XT,XMAX)
	  IBIN = (NBIN-1)*(XT-XMIN)/(XMAX-XMIN) + 1
	  NARR(IBIN) = NARR(IBIN)+1
	  TOTAL = TOTAL + 1.
	  RETURN
	ENDIF
C
C	IF(PCTILE.GT..5) THEN
C	  PRINT OUT RESULTS
    	  PRINT*,' TOTAL NUMBER, NBIN',TOTAL,NBIN
	  PRINT*,'XMIN,XMAX',XMIN,XMAX
	  PRINT*,'HISTOGRAM'
	  PRINT 1111, (NARR(J),J=1,NBIN)
 1111	  FORMAT(10I7)
C	ENDIF
C
C	NOW CALCULATE VALUE OF X CORRESPONDING TO PCTILE PERCENTILE
C
C	PCTILE = .2
	SET = PCTILE*TOTAL
	SUM = 0.
	N = 0
  100	N = N+1
	  SUM = SUM + NARR(N)
	  IF(SUM.LT.SET) GO TO 100
C
C	NOW THE DESIRED VALUE LIES IN BIN N
C
	SUMLOW = SUM - NARR(N)
	XN = N
	RETLOW = XMIN + ((XN-1.)/(NBIN-1.))*(XMAX-XMIN)
	RETHI = XMIN +       (XN/(NBIN-1.))*(XMAX-XMIN)
	RET = .5*(RETHI+RETLOW)    		! PROVISIONAL
	IF(NARR(N).NE.0) 
     1		RET = RETLOW + (SET-SUMLOW)*(RETHI-RETLOW)/NARR(N)
C	PRINT*,'N,SET,SUMLOW,LOW,RET',N,SET,SUMLOW,RET
C
	DO N = 1,NBIN
	  PLDATA(N,1) = XMIN + N*(XMAX-XMIN)/(NBIN-1.)
	  PLDATA(N,2) = NARR(N)
	ENDDO
	RETURN
	END
