	SUBROUTINE FANDBW(SPS,ICHANN,DBX,DBY,NPEAK,F,BW,AMP)
C
	REAL DBX(1025),DBY(1025)
	REAL F(5),BW(5),AMP(5)
	REAL X(25)
	INTEGER HPEAK
C
C	FINDS FREQUENCY OF HIGHEST PEAK AND ITS BANDWIDTH
C
C	FIRST FIND THE MAXIMUM IN THE SPECTRUM. 
C	THEN TRACE EACH SIDE DOWN TO:
C		(1) HALFWAY TO BACKG
C		(2) SIGNAL STARTS TO GO UP AGAIN (REQUIRE 3 UP POINTS)
C	THEN FIT A/((W-W0)**2 + DW**2) TO THESE POINTS IF THERE
C		ARE AT LEAST 3 POINTS
C	THEN LOOK FOR POSSIBLE SECOND PEAK.  IF THE HIGHEST PEAK IS
C	    IN THE CENTER, THEN IT CAN FIND 3 PEAKS
C
C	  FIND MAXIMUM IN SPECTRUM
C
	SMAX = -1000.
	DO N = 10,1022
	    IF(DBX(N).GT.SMAX) THEN
	      SMAX = DBX(N)
	      NSPMAX1 = N
	    ENDIF
	ENDDO
	PRINT*,'X SPEC. MAX:N,F,SMAX',NSPMAX1,(NSPMAX1-1)*SPS/2048.,SMAX
	FREQMAX1 = (NSPMAX1-1)*SPS/2048.
	NPEAK = 1
C
C	GO DOWN LOW SIDE
C
	SLIM = .5*(SMAX - 80.)
	LCOUNT = 0
	SSAVE = SMAX
	LPEAK = 0
	DO N = NSPMAX1-1,10,-1
	    NSVL = N
	    IF(DBX(N).GT.SSAVE) THEN
	      LCOUNT = LCOUNT+1
	      IF(LCOUNT.GE.3) THEN
		LPEAK = 1
		GO TO 20
	      ENDIF
	    ENDIF
	    IF(DBX(N).LT.SLIM) GO TO 20
	    SSAVE = DBX(N)
	ENDDO
C
C	GO DOWN HIGH SIDE
C
 20	CONTINUE
	LCOUNT = 0
	SSAVE = SMAX
	HPEAK = 0
	DO N = NSPMAX1+1,1024
	    NSVH = N
	    IF(DBX(N).GT.SSAVE) THEN
	      LCOUNT = LCOUNT+1
	      IF(LCOUNT.GE.3) THEN
		HPEAK = 1
		GO TO 30
	      ENDIF
	    ENDIF
	    IF(DBX(N).LT.SLIM) GO TO 30
	    SSAVE = DBX(N)
	ENDDO
C
 30	CONTINUE
C
C	DETERMINE SECOND AND MAYBE THIRD PEAK
C
	IF(LPEAK.NE.0) THEN
	  NPEAK = NPEAK + 1
	  SMAX = -1000.
	  DO N = NSVL+2,10,-1
	    IF(DBX(N).GT.SMAX) THEN
	      SMAX = DBX(N)
	      NSPMAX3 = N
	    ENDIF
	  ENDDO
	  FREQMAX3 = (NSPMAX3-1)*SPS/2048.
	  PRINT*,'2ND PK. MAX:N,F,SMAX',NSPMAX3,FREQMAX3,SMAX
	ENDIF
C
	IF(HPEAK.NE.0) THEN
	  NPEAK = NPEAK + 1
	  SMAX = -1000.
	  DO N = NSVH-2,1024
	    IF(DBX(N).GT.SMAX) THEN
	      SMAX = DBX(N)
	      NSPMAX4 = N
	    ENDIF
	  ENDDO
	  FREQMAX4 = (NSPMAX4-1)*SPS/2048.
	  PRINT*,'2ND PK. MAX:N,F,SMAX',NSPMAX4,FREQMAX4,SMAX
	ENDIF
C
C	FIT SPECTRUM(F) = A DF^2/((F-F0)^2 + DF^2) TO HIGHEST 3 POINTS
C
	SINV1 = 10.**(-DBX(NSPMAX1-1))
	SINV2 = 10.**(-DBX(NSPMAX1))
	SINV3 = 10.**(-DBX(NSPMAX1+1))
	DELF = 	SPS/2048.
	TEMP = SINV1 - 2.*SINV2 + SINV3
	ADF2 = 2.*DELF**2/TEMP
	TEMP = ADF2*(SINV3 - SINV1) - 4.*FREQMAX1*DELF
	F0 = -.25*TEMP/DELF
	AINV = SINV2 - (FREQMAX1-F0)**2/ADF2
	AMP(1) = 1./AINV
	BW2 = ADF2*AINV
	BW(1) = SQRT(BW2)
	F = F0
	PRINT*,'A,F0,BW',AMP(1),F0,BW(1)
	RETURN
	END

