
	FUNCTION FFT_FILTER(CHANNEL,FILTER_NO,F)
C
C	CHANNEL IS THE FFT CHANNEL, ITEM - 'FFT_CHANNEL', FILTER_NO IS THE 
C	NUMBER RETURNED BY ITEM = '0 FOR HIGHEST CUTOFF FREQUENCY, 3 FOR LOWEST
C
	INTEGER*4 CHANNEL,FILTER_NO
	REAL F, F0(10), FQ(10)
	DATA F0 /9600.,9600.,4*2400.,4*150./
C
	FFT_FILTER = 1.
	RETURN
	END
