	PROGRAM FFTWIN
C
C	TESTS WINDOWING--LINK WITH FASFOR
C
	COMMON /SHBLK/ DRVFRQ(2048),PWRL(256,511)
	COMMON /PLOTDT/ ITERM,NPT,FMIN,FMAX,NDRV,NF1,NF2,NSIZE,AMP
	COMMON /WINBLK/ WINDOW(1024)
	DIMENSION AR(1024),AI(1024),PWRS(512),PWRC(512)
	DATA TWOPI /6.2831853/
	DATA WINDOW /1024*1./
C
	NP = 10
	NSIZE = 256                        ! FIRST DIMENSION OF PWRL
	NPROS = 2**NP
	NFRQ = NPROS/2
	NDRV = 2048
	AMP = 2.
C
C	IWINDW = 0
C	CALL FWINDW(IWINDW)
	FMIN = .1
	FMAX = 512.
	FRAT = ALOG(FMAX/FMIN)/(NDRV-1)
	FRAT = EXP(FRAT)
	HARM = FMIN/FRAT
	NX = 0
	NF1 = 1
	DO NF = 1,NDRV
	  HARM = HARM*FRAT
	  DRVFRQ(NF) = HARM
	  NX = NX+1
C	  PRINT*,NF,HARM
	  DO N = 0,NPROS-1
	    AR(N+1) = AMP*WINDOW(N+1)*COS(TWOPI*N*HARM/NPROS)
	    AI(N+1) = 0.
	  ENDDO
	  CALL FASFOR(NP,AR,AI,PWRC)
	  DO N = 0,NPROS-1
	    AR(N+1) = AMP*WINDOW(N+1)*SIN(TWOPI*N*HARM/NPROS)
	    AI(N+1) = 0.
	  ENDDO
	  CALL FASFOR(NP,AR,AI,PWRS)
	  DO N = 1,NFRQ-1
	    PWRL(NX,N) = ALOG10(PWRS(N) + PWRC(N))
	  ENDDO
C	  PRINT*,NF,HARM,PWRL(NX,1),PWRL(NX,511)
	  IF(NX.GE.NSIZE) THEN
	    NF2 = NF
	    NPT = NX
C	    CALL SHPLOT
	    CALL SHPGPLOT
C		if(nf.gt.512) stop
	    NF1 = NF2 + 1
	    NX = 0
	  ENDIF
	ENDDO
	NHARM = 510
	PRINT*,'PWR',PWRC(NHARM-1),PWRC(NHARM),PWRC(NHARM+1)
	PRINT*,' AR', AR(NHARM-1), AR(NHARM), AR(NHARM+1)
C	PRINT*,(AR(JJ),JJ=1,72)
	PRINT*,' AI', AI(NHARM-1), AI(NHARM), AI(NHARM+1)
C	PRINT*,(AI(JJ),JJ=1,72)
C
C	PWR(NHARM) WILL BE AMP**2/2.
C
	STOP
	END
	SUBROUTINE SHPLOT
C
	COMMON /SHBLK/ DRVFRQ(2048),PWRL(256,511)
	COMMON /PLOTDT/ ITERM,NPT,FMIN,FMAX,NDRV,NF1,NF2,NSIZE,AMP
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	CHARACTER*6 TITLE(4)
	CHARACTER*120 STR
C
C
	IF(NPT.LT.1) NPT = 1             	  ! protection
	PRINT*,' IN SHPLOT,NF1,NF2',NF1,NF2
	PRINT*,' IN SHPLOT,FREQS',DRVFRQ(1),DRVFRQ(NPT),NPT
C	CALCULATE BOX SIZE
	PIXSIZ = .1
	IF(NPT.GT.1) PIXSIZ = (DRVFRQ(NF2) - DRVFRQ(NF1))/(NPT-1)
	HSTART = DRVFRQ(1) - .5*PIXSIZ
	HEND =   DRVFRQ(NPT) + .5*PIXSIZ
	PRINT*,' IN SHPLOT',HSTART,HEND,NPT
	  CALL MGOINIT
	  CALL MGOSETUP(ITERM)
	  CALL MGOERASE
C
	IF(NF1.EQ.1) THEN
	  YMIN = PWRL(1,1)
	  YMAX = YMIN
	  DO N = 1,NPT
	    DO J = 1,511
	        YMIN = AMIN1(YMIN,PWRL(N,J))
	        YMAX = AMAX1(YMAX,PWRL(N,J))
	    ENDDO
	  ENDDO
	ENDIF
C
	
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(XSTART,280.,XEND,1587.)
	ENDIF
	PRINT*,' YMIN,MAX ACTUAL',YMIN,YMAX
C	RAISING YMIN MAKES THE BACKGROUND LIGHTER
C	LOWERING YMAX MAKES THE SIGNAL DARKER
	YMIN = -6.
	PRINT*,'YMIN,MAX SET TO',YMIN,YMAX
	CALL MGOHALFTONE(PWRL,NPT,511,YMIN,YMAX,1.E7)
	CALL MGOSETEXPAND(.7)
	CALL MGOSETLIM(FSTART,1.,FEND,511.)
	IF(NF2.EQ.NSIZE) THEN
          CALL MGOXLABEL(15,'INPUT HARMONIC')	
	  CALL MGOYLABEL(15,'OUTPUT HARMONIC')	
	  CALL MGOBOX(1,2)
	  CALL MGOSETEXPAND(1.)
	  CALL MGOPLOTID('FFTWIN','SHPLOT')
	  CALL MGOSETEXPAND(1.)
C
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
	ENDIF
C
	CALL MGOSETEXPAND(1.)
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	  NPLOTS = NPLOTS + 1
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
	END
	SUBROUTINE SHPGPLOT
C
	COMMON /SHBLK/ DRVFRQ(2048),PWRL(256,511)
	COMMON /PLOTDT/ ITERM,NPT,FMIN,FMAX,NDRV,NF1,NF2,NSIZE,AMP
C
	CHARACTER*6 TITLE(4)
	CHARACTER*120 STR
	DIMENSION AXFM(6)
	DATA AXFM /0.,1.,0.,0.,0.,1./
C
C
	IF(NPT.LT.1) NPT = 1             	  ! protection
	PRINT*,' IN SHPGPLOT,NF1,NF2',NF1,NF2
	PRINT*,' IN SHPGPLOT,FREQS',DRVFRQ(NF1),DRVFRQ(NF2),NPT
C
C	CALCULATE PIXEL SIZE
	PIXSIZ = .1
	IF(NPT.GT.1) PIXSIZ = ALOG10(DRVFRQ(NF2)/DRVFRQ(NF1))/(NPT-1)
	HSTART = DRVFRQ(NF1) - .5*PIXSIZ
	HEND =   DRVFRQ(NF2) + .5*PIXSIZ
	PRINT*,' IN SHPGPLOT',HSTART,HEND,NPT
	AXFM(4) = 1.
	AXFM(6) = 1./511.
C	AXFM(1) = AXFM(1) - AXFM(2)

C
C	CALCULATE MAX AND MIN, FOR GREY SCALING
C
	IF(NF1.EQ.1) THEN
C
C	  CALL PGBEGIN(0,'/PS',1,1)
	  CALL PGBEGIN(0,'/LASER',1,1)
	  PRINT*,'CALCULATE MAX AND MIN FOR SHPGPLOT'
	  YMIN = PWRL(1,1)
	  YMAX = YMIN
	  DO N = 1,NPT
	    DO J = 1,511
	        YMIN = AMIN1(YMIN,PWRL(N,J))
	        YMAX = AMAX1(YMAX,PWRL(N,J))
	    ENDDO
	  ENDDO
	  PRINT*,' YMIN,MAX ACTUAL',YMIN,YMAX
C	  RAISING YMIN MAKES THE BACKGROUND LIGHTER
C	  LOWERING YMAX MAKES THE SIGNAL DARKER
	  YMAX = 0.
	  YMIN = -8.
	  PRINT*,'YMIN,MAX SET TO',YMIN,YMAX
	  CALL PGVSTAND
	  CALL PGQVP(1,XX1,XX2,YY1,YY2)
	  PRINT*,'STANDARD viewport',XX1,XX2,YY1,YY2
	  CALL PGQWIN(XFULL1,XFULL2,YFULL1,YFULL2)
	  PRINT*,'initial WINDOW',XFULL1,XFULL2,YFULL1,YFULL2
C	  XLEFT = XFULL1 + (NF1-1)*(XFULL2-XFULL1)/NDRV
C	  XRIGHT = XFULL1 + (NF2)*(XFULL2-XFULL1)/NDRV
	  XLEFT = ALOG10(FMIN)
	  XRIGHT = ALOG10(FMAX)
	  CALL PGWINDOW(XLEFT,XRIGHT,1.,511.)
	  CALL PGQCH(CHT)
	  CALL PGPTEXT(.5,-2.*CHT,0.,.5,'DRIVE FREQUENCY')
	  CALL PGPTEXT(-2.*CHT,.5,90.,.5,'OUTPUT FREQUENCY')
	  CALL PGBOX('BCILNST',0.,0,'BCINST',0.,0)
	ENDIF
C
c	CALL PGVSTAND
c	CALL PGQVP(1,XX1,XX2,YY1,YY2)
	PRINT*,'STANDARD viewport',XX1,XX2,YY1,YY2
c	CALL PGQWIN(XFULL1,XFULL2,YFULL1,YFULL2)
	PRINT*,'WINDOW',XFULL1,XFULL2,YFULL1,YFULL2
	CALL PGQWIN(XL,XR,YFULL1,YFULL2)
	PRINT*,'RESET WINDOW',XLEFT,XRIGHT,XL,XR
	AXFM(1) = ALOG10(DRVFRQ(NF1))
	AXFM(2) = ALOG10(DRVFRQ(NF2)/DRVFRQ(NF1))/(NPT-1)
	AXFM(1) = AXFM(1) - AXFM(2)
C	AXFM(4) = YFULL1
C	AXFM(6) = YFULL2/511.
	PRINT*,'AXFM',AXFM
C	CALL PGVSIZE(XX1,XX2,YY1,YY2)
	print*,'calling pggray44,npt=',npt
	CALL PGGRAY44(PWRL,256,511,1,NPT,1,511,YMAX,YMIN,AXFM)
c	CALL MGOSETEXPAND(.7)
c	CALL MGOSETLIM(FSTART,1.,FEND,511.)
	IF(NF2.EQ.NDRV) THEN
	  print*,' end called'
	  CALL PGIDEN
	  CALL PGEND
	ENDIF
C
c	CALL MGOSETEXPAND(1.)
C
	RETURN
	END
	SUBROUTINE OUTPLOT
C
C	PLOTS THE OUTPUT OF 4 GIVEN CHANNELS V.S. DRIVE FREQUENCY
C
	COMMON /SHBLK/ DRVFRQ(2048),PWRL(256,511)
	COMMON /PLOTDT/ ITERM,NPT,FMIN,FMAX,NDRV,NF1,NF2,NSIZE,AMP
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	CHARACTER*6 TITLE(4)
	CHARACTER*120 STR
	DIMENSION INPT(4),YY(2048)
C
	DATA NPLOTS /0/
C
C
	TSTART = DRVFRQ(1) - .05
	TEND =   DRVFRQ(NPT) + .05
	PRINT*,' IN TPLOT',TSTART,TEND,NPT
C
	  CALL MGOINIT
	  CALL MGOSETUP(ITERM)
	  CALL MGOERASE
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(500.,330.,2200.,3000.)
	ENDIF
C
	  CALL MGOSETEXPAND(.85)
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                   
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
	  CALL MGOPUTLABEL(53,STR,9)
	  CALL MGOSETEXPAND(1.)
C
	IF(IFSTART.LE.0) GO TO 100
C
	DO JH = 1,4
	  JHP = INPT(JH)
	  CALL MGOWINDOW(1,4,JH)                          ! HI FREQ
	  YMIN = 0.
	  YMAX = 0.
	  DO JP = 1,NPT
	    YY(JP) = PWRL(JP,JHP)
	    YMAX = AMAX1(YY(JP),YMAX)
	    YMIN = AMIN1(YY(JP),YMIN)
	  ENDDO
	  PRINT*,'FREQ,YMAX',JHP,YMAX
	  CALL MGOSETLIM(TSTART,YMIN,TEND,1.1*YMAX)
	  CALL MGOCONNECT(DRVFRQ,YY,NPT)
	  CALL MGOBOX(1,2)
C	  WRITE(STR,704) (12-JHP)
C 704	  FORMAT('\\tFREQ',I3)
C	  WRITE(STR,704) FREQHI(13-JHP)
C 704	  FORMAT('\\t',F4.0,' kHz')
C	  CALL MGOYLABEL(11,STR)
	ENDDO
	GO TO 200
C
 100	CONTINUE
C
	LFSTART = IFSTART
	LFSTART = IABS(LFSTART)
C
C	DO JF = 1,64
C	  FREQLO(JF) = .5 + .75*JF
C	ENDDO
C
	TSTART = DRVFRQ(1) - .05
	TEND =   DRVFRQ(NPT) + .05
	PRINT*,' IN OUTPLOT ',TSTART,TEND,NPT
C
	DO JL = 1,4
C          IF(NMODE.EQ.3) THEN                            ! LINEAR SWEEP
C	    JLP = 16*(JL-1) + LFSTART + 1
C	  ELSE
C	    JLP = LOLIST(2*JL-1,LISTLO+1) + 1
C	  ENDIF
	  CALL MGOWINDOW(1,4,JL4)                          ! LO FREQ
	  YMIN = 0.
	  YMAX = 0.
	  DO JP = 1,NPT
	    YY(JP) = PWRL(JP,JLP)
	    YMAX = AMAX1(YY(JP),YMAX)
	  ENDDO
	  PRINT*,'FREQ,YMAX',JLP-1,YMAX
	  YMAX = AMAX1(YMAX,9.09091)
	  CALL MGOSETLIM(TSTART,YMIN,TEND,1.1*YMAX)
	  CALL MGOCONNECT(THL,YY,NPT)
	  CALL MGOBOX(1,2)
C	  WRITE(STR,705) FREQLO(JLP)
C 705	  FORMAT('\\t',F4.1,' kHz')
C	  CALL MGOYLABEL(11,STR)
	ENDDO
C
C
 200	CONTINUE
	CALL MGOSETEXPAND(.8)
	CALL MGOPLOTID('FREQINV','TPLOT')
	CALL MGOSETEXPAND(1.)
	IF(ITERM.LT.0) THEN
C	  CALL MGOTIDLE
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	  NPLOTS = NPLOTS + 1
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END
	SUBROUTINE SPPLOT
C
C	PLOTS THE OUTPUT SPECTRUM FOR 4 INPUT FREQUENCIES
C
	COMMON /TBLK/ DRVFRQ(1250),THL(300),PWRL(300,64),AVSH(1250,12)
	COMMON /PLOTDT/ ITERM,NPT,FMIN,FMAX,NDRV,NF1,NF2,NSIZE,AMP
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	DIMENSION JTPS(4)
	CHARACTER*6 TITLE(4)
	CHARACTER*120 STR
C	DATA JTPS /4,75/
C
	PRINT*,' IN SPPLOT',NPT
C	DO JF = 1,64
C	  FREQLO(JF) = .5 + .75*JF
C	ENDDO
C
	  CALL MGOINIT
	  CALL MGOSETUP(ITERM)
	  CALL MGOERASE
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(500.,330.,2200.,3000.)
	ENDIF
C
	  CALL MGOSETEXPAND(.85)
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                    
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
	  CALL MGOPUTLABEL(53,STR,9)
c	  WRITE(STR,704) SAA()
c 704	  FORMAT('\\tSOLAR ASPECT',F6.1,' DEG.')
c	  CALL MGOPUTLABEL(55,STR,9)
	  CALL MGOSETEXPAND(1.)
C
	DO JT = 1,2
	  JTP = JTPS(JT)
	  JHS = 2*JT - 1
	  CALL MGOWINDOW(1,4,JHS)                          ! LO FREQ
	  YMIN = 40.
	  YMAX = YMIN+10.
	  JP = 1
	  DO J = 1,64
C	    YY(JP) = PWRL(JTP,J)
C	    XX(JP) = FREQLO(J)
C	    IF(YY(JP).GT.1.) THEN
C	      YMAX = AMAX1(YY(JP),YMAX)
C	      JP = JP+1
C	    ENDIF
	  ENDDO
	  JP = JP-1
	PRINT*,'SPEC #,YMAX,JP',JTP,YMAX,JP
	  CALL MGOSETLIM(0.,YMIN,50.,1.2*YMAX)
	  J4 = JP
	  CALL MGOCONNECT(XX,YY,J4)
	  CALL MGOBOX(1,2)
	  WRITE(STR,704) THL(JTP)
C 704	  FORMAT('\\tSPEC #',I3)
 704	  FORMAT('\\tAT',F6.2,' HRS')
	  CALL MGOYLABEL(15,STR)
C
	  CALL MGOWINDOW(1,4,JHS+1)                          ! HI FREQ
	  YMIN = 0.
	  YMAX = 0.
C	  DO JP = 1,12
C	    YY(JP) = AVSH(JTP,JP)
C	    YMAX = AMAX1(YY(JP),YMAX)
C	  ENDDO
	PRINT*,'SPEC #,YMAX',JTP,YMAX
	  CALL MGOSETLIM(0.,YMIN,1000.,1.1*YMAX)
	  CALL MGOCONNECT(FREQHI,YY,12)
	  CALL MGOBOX(1,2)
	  WRITE(STR,704) DRVFRQ(JTP)
	  CALL MGOYLABEL(15,STR)
c	  CALL MGOPUTLABEL(55,STR,9)
	ENDDO
C
C
	CALL MGOSETEXPAND(.8)
	CALL MGOPLOTID('FFTWIN','SPPLOT')
	CALL MGOSETEXPAND(1.)
	IF(ITERM.LT.0) THEN
	  CALL MGOTIDLE
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	  NPLOTS = NPLOTS + 1
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END
