	PROGRAM FITHIST
C
	REAL HIST(14,4,100),HIST1(100),XAX(101)
	CHARACTER*120 JUNK
	INTEGER*4 NFHIST(14)
	REAL*8 SCETSTS,SCETEND
C
	OPEN(UNIT=89,FILE='FOR089.DAT',STATUS='OLD',READONLY)
	read (89,*) SCETSTS,SCETEND
	READ (89,*) NFHIST,NHISTST

C	
 189	FORMAT(A)
	irxlim = 4
	irxlim = 2
	do irx = 1,irxlim
	  do ifr = 1,14
		READ(89,189) JUNK
		PRINT*,JUNK
C		  range is +10 to -90 dB for irxlim = 4 (TDSS)
C			and -10 tp -110 for irxlim = 2  (TDSF)
C		  no, now range is nhistst to nhistst + 99
	          READ(89,*) (hist(ifr,irx,nhist),NHIST=1,100) 
C	          READ(89,1089) (hist(ifr,irx,nhist),NHIST=1,100) 
 1089		  format(10F8.0)
          enddo
	enddo
	CLOSE(UNIT=89)
	do nhist=1,101
	  xax(nhist) = nhist + nhistst - 1
	enddo
C
	do irx = 1,4
	  do ifr = 1,14
	    DO N = 1,100
	      HIST1(N) = HIST(IFR,IRX,N)
	    ENDDO
c	    CALL FITLOGNORM(IRX,IFR,HIST1)
          enddo
	enddo
	ITERM = 3
c	ITERM = -1
	CALL PLOTHIST(ITERM,NFHIST,XAX,HIST)
C
	STOP
	END
	SUBROUTINE FITLOGNORM(IRX,IFR,HIST)
C
	REAL HIST(100),MAX
C
	SUM = 0.
	MAX = 0.
	COUNT = 1.E-9
	STD = 0.
	DO N = 1,100
	  SUM = SUM + N*HIST(N)
	  STD = STD + (N**2)*HIST(N)
	  COUNT = COUNT + HIST(N)
	ENDDO
	AVR = SUM/COUNT
	STD = SQRT(STD/COUNT - AVR**2)
	SIGMA = .7071*STD
	AMP = 2.*SUM/SIGMA**2
C
C	DETERMINE TOP 12 PERCENTILE
C
	PCTILE = 0.
	GOAL = .12*COUNT
	DO N = 100,1,-1
	  PCTSV = PCTILE
	  PCTILE = PCTILE + HIST(N)
	  IF(PCTILE.GT.GOAL) THEN	
	    EXCESS = PCTILE - GOAL
	    CUT = N + 1 - EXCESS/HIST(N)
	    DEV = -(AVR - CUT)/STD
	    GO  TO 100
	  ENDIF
	ENDDO
 100	PRINT 69,IFR,IRX,COUNT,AVR,STD,AMP,DEV
 69	FORMAT(2I5,F8.0,E12.3,F7.1,2E12.3)
	RETURN
	END
	SUBROUTINE PLOTHIST(ITERM,NFHIST,XAX,HIST)
	REAL HIST(14,4,100),HIST1(100),XAX(101)
	INTEGER*4 NFHIST(14)
	CHARACTER*120 STR
	CHARACTER*1 DISPOSE
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV,DDS
C
	DATA TWOPI /6.2831853/
C	DATA ITERM /3/
C
	DO IRX = 1,4
	  CALL MGOINIT
	  CALL MGOSETUP(ITERM)
	  CALL MGOERASE
C
C	  HALF WIDTH, 2/3 HEIGHT, LOOKED TERRIBLE
C	  CALL MGOSETLOC(100.,100.,600.,600.)
C
	  DO IFR = 1,12
	    CALL MGOWINDOW(3,4,IFR)
	    HMAX = 0
	    DO IH = 1,100
	      HIST1(IH) = HIST(IFR,IRX,IH)
	      HMAX = AMAX1(HMAX,HIST1(IH))
	    ENDDO
	    CALL MGOSETLIM(XAX(1), 0.,XAX(100), 1.1*HMAX)
	    CALL MGOHISTOGRAM(XAX,HIST1,100)
	    CALL MGOBOX(1,2)
	    EXSAVE = EXPAND
	    CALL MGOSETEXPAND(.8)
	    WRITE(STR,102) 120000.*NFHIST(IFR)/2048.
 102	    FORMAT(F5.0,' Hz')
	    CALL MGORELOCATE(-100.,.9*HMAX)
	    CALL MGOLABEL(9,STR)
	    CALL MGOSETEXPAND(EXSAVE)
	  ENDDO
	
C	  PRINT*,'IRS',IRX
	  WRITE(STR,101) IRX
 101	  FORMAT(I2)
	  CALL MGOSETEXPAND(2.)
	  CALL MGOPLOTID('[.WIND]FITHIST',STR)
	  CALL MGOSETEXPAND(1.)
	  IF(ITERM.LT.0) THEN
	    CALL MGOPRNTPLOT(NVEC)
	    PRINT*,' NO. VECTORS PLOTTED',NVEC
	  ELSE
	    READ(5,1234) DISPOSE
 1234	    FORMAT(A)
	    CALL MGOTCLOSE
	  ENDIF
	ENDDO				! END OF IRX = 1,4 LOOP
C
	RETURN
	END
