	SUBROUTINE FITSLOPE(X,Y,N,SLOPE,SUMSQ)
C
	DIMENSION X(1),Y(1),WT(2048)
C
	SUMSQ = 0.
	SXX = 0.
	SXY = 0.
	SYY = 0.	
	DO J = 1,N
	  WT(J) = 1.
	  SXX =SXX + WT(J)*X(J)**2
	  SXY =SXY + WT(J)*X(J)*Y(J)
	  SYY =SYY + WT(J)*Y(J)**2
	ENDDO
C	SLOPE IS Y/X
	SLOPE = SXY/SXX
	SUMSQ = SXX*SLOPE**2 - 2.*SLOPE*SXY + SYY
	RETURN
	END

