	SUBROUTINE FITZERO(X,SUMSQ)
C
	COMMON /ZBLK/ NPT,ZCROSS(128)
	DIMENSION X(25),WT(2048)
	DATA WT /2048*1./
C
	SUMSQ = 0.
	DO N = 1,NPT
	  SUMSQ = SUMSQ + (ZCROSS(N) - X(1) - X(2)*(N-1))**2
	ENDDO
	RETURN
	END

