	SUBROUTINE FIXBADTDS(IPRC,NDATA,VDATA)
C
C	COMMON /FIXBLK/ MPDATA(2050)
	COMMON /FIXUPBLK/ ISTART,NBAD2,NBAD1,IFXB
	COMMON /TDS_STATUS/ ITDSCHAN,SPS,FILTER,IRX,ISPS
	COMMON /CHECK/FVDATA(2048)
C
C
	REAL 		VDATA(2050),FDATA(5),WT(10)
	REAL		ZCROSS(2048),ZINT(2048)
	INTEGER*4	NDATA(2048),MPDATA(2050)
        DATA WT /2*1.,0.,7*1./
C
C	THIS SUBROUTINE LOOKS FOR CERTAIN VALUES IN A TDS EVENT OUTPUT
C	WHICH ARE KNOWN TO BE SUSPICIOUS, AND PUTS IN NEW VALUES BASED
C	ON FITTING A SINE WAVE THROUGH THE 4 ADJACENT VALUES.  THIS IS A 
C	TRY WHICH FIXES ONLY VALUES OF IWRONG1  (IWRONG1 = +-71 OR 81), 
C	AND SAMPLES FOLLOWING -IWRONG2 = -58.
C	THE BAD VALUES RESULT FROM TIMING IN THE A/D CIRCUIT, WHICH ALLOWS
C	THE SIGNAL TO CHANGE AFTER A CHOICE HAS BEEN MADE AS TO SIGN, AND
C	AS TO HIGH OR LOW GAIN.
C	THIS DIFFERS FROM FIXBADTDS3 IN (1) ONLY -58'S HAVE FOLLOWING
C	BAD NUMBERS (2) NO CONSTANT TERM IN SINFIT  
C
	IFXB = 4
C
	ISTART = 0
	IF(ITDSCHAN.LE.2) THEN
	  IWRONG1 = 71
	  IWRONG2 = 58
	ELSE
	  IWRONG1 = 81
	  IWRONG2 = 58
	ENDIF
C
C	ESTIMATE FREQUENCY AND GENERAL SIZE OF MAXIMUM
C
	NBAD2 = 0			! THE NUMBER OF "58"'S FIXED
	NBAD1 = 0			! THE NUMBER OF IWRONG1' FIXED
	MAXDATA = 0			
	MINDATA = 256
	DO N = 1,2048
	  MPDATA(N) = NDATA(N)-128
	  IF(MPDATA(N).NE.IWRONG1) MAXDATA = MAX0(NDATA(N),MAXDATA)
	  IF(MPDATA(N).NE.-IWRONG1) MINDATA = MIN0(NDATA(N),MINDATA)
	ENDDO
	VMAX = TDSCAL(ITDSCHAN,ISPS,MAXDATA)
	VMIN = TDSCAL(ITDSCHAN,ISPS,MINDATA)
C
C	FIND ZERO CROSSINGS, AND COUNT THEM TO ESTIMATE FREQUENCY
C
	IZCNT = 0
	IL = 1
cd	  IF(NDATA(IL).EQ.0) PRINT*,'ZERO DATA',IL,NDATA(IL),NDATA(IL+1)
	DO IL = 2,2047
	  IZ = IL
cd	  IF(MPDATA(IL).EQ.0) PRINT*,'ZERO DATA',IL,MPDATA(IL-1),
cd     1       MPDATA(IL),MPDATA(IL+1)
C		COUNT ONLY POS TO NEG
	  IF(MPDATA(IL).GT.0.AND.MPDATA(IL+1).LE.0) THEN
	        IZCNT = IZCNT+1
		S1 = MPDATA(IL)
		S2 = MPDATA(IL+1)
		DELZ = S1/(S1 - S2)
		IF(DELZ.GE.0.AND.DELZ.LE.1.) THEN
			ZCROSS(IZCNT) = IL + DELZ
		ELSE
			ZCROSS(IZCNT) = IL + .5
		ENDIF
	  ENDIF
	ENDDO
C
	STD = 0.
	DO N = 1,IZCNT-1
	  ZINT(N) = ZCROSS(N+1) - ZCROSS(N)
	  IF(ZINT(N).EQ.0.) ZINT(N) = 1.E-6
	  STD = STD + ZINT(N)**2              		 ! IN SAMPLES
	ENDDO
C
	AVRFREQ=0.
	RMS = 0.
	IF(IZCNT.GT.1) THEN
	  AVRPER = (ZCROSS(IZCNT)-ZCROSS(1))/(IZCNT-1)   ! IN SAMPLES
	  AVRFREQ = .001*SPS/AVRPER                      ! IN KHZ
	  RMS = SQRT(AMAX1(STD/(IZCNT-1) - AVRPER**2,0.))
	ENDIF
C
C	REMOVE MULTIPLE ZERO CROSSING FOR LOW FREQUENCIES
C
	IF(AVRPER.GT.20.) THEN
	  ZLIM = .2*RMS
	  IZCNTS = IZCNT
	  NNN = 2
	  DO N = 1,IZCNT-1
	    IF(ZINT(NNN).LT.ZLIM) THEN
	      IZCNTS = IZCNTS-1
	      ZINT(NNN-1) = ZINT(NNN-1) + ZINT(NNN)
	      DO NN = NNN,IZCNTS-1
		ZINT(NN) = ZINT(NN+1)
	      ENDDO
	    ELSE
	      NNN = NNN+1
	    ENDIF
	  ENDDO
C	  PRINT*,'NUMBER OF MULTIPLE CROSSINGS REMOVED',IZCNT-IZCNTS
	  IZCNT = IZCNTS
	  STD = 0.
	  AVR = 0.
	  DO N = 1,IZCNT-1
	    AVR = AVR + ZINT(N)
	    STD = STD + ZINT(N)**2              		 ! IN SAMPLES
	  ENDDO
	  IF(IZCNT.GT.1) THEN
	    AVRPER = AVR/(IZCNT-1)
	    RMS = SQRT(AMAX1(STD/(IZCNT-1) - AVRPER**2,0.))
C	    print*,'now average period is',avrper,' +-',rms
	  ENDIF 
	ENDIF
C
	IF(AVRPER.EQ.0.) RETURN
C
C	NOW FIX BAD POINTS
C
	N = 3
 100	CONTINUE
C
C	DO N = 3,2046
C
C	FIX SAMPLES FOLLOWING VALUES OF 58 = IWRONG2 
C
C	  IF(IABS(MPDATA(N)).EQ.IWRONG2) THEN
	  IF(MPDATA(N).EQ.-IWRONG2) THEN
	      IF(IABS(MPDATA(N+2)).EQ.IWRONG1.OR.
     1	        IABS(MPDATA(N+3)).EQ.IWRONG1) GO TO 200
		NFIX = N+1
		DO NF = 1,5
		  FDATA(NF) = VDATA(NFIX-3+NF)
		ENDDO
		CALL FIXUP(NFIX,ISTART,FDATA,WT,AVRPER,RMS,FIXED_V)
		NBAD2 = NBAD2+1
		ISTART = ISTART+1
		FIXED_V = AMIN1(FIXED_V,VMAX)
C
	        VDATA(NFIX) = AMAX1(FIXED_V,VMIN)
C
		N = N+3
	        GO TO 300
	  ENDIF
C
C	BAD VALUES WHICH ARE DUE TO THE CHOICE OF SMALL SIGNAL
C	 A/DB CONVERTER WHEN IT SHOULD HAVE BEEN LARGE SIGNAL.  
C	THESE DEPEND ON CHANNEL.  THEY HAVE
C	THE VALUES +-71 IN CHANNELS 1 AND 2, +-81 IN CHANNELS 3-6
C
	  IF(IABS(MPDATA(N)).EQ.IWRONG1) THEN
	      IF(MPDATA(N+1).EQ.-IWRONG2.OR.
     1	        MPDATA(N+2).EQ.-IWRONG2) THEN
C	      IF(IABS(MPDATA(N+1)).EQ.IWRONG2.OR.
C     1	        IABS(MPDATA(N+2)).EQ.IWRONG2) THEN
	   	GO TO 200
	      ENDIF
	      NFIX = N
	      DO NF = 1,5
		  FDATA(NF) = VDATA(NFIX-3+NF)
	      ENDDO
	      CALL FIXUP(NFIX,ISTART,FDATA,WT,AVRPER,RMS,FIXED_V)
	      NBAD1 = NBAD1+1
	      ISTART = ISTART+1
	      FIXED_V = AMIN1(FIXED_V,VMAX)
C
	      VDATA(NFIX) = AMAX1(FIXED_V,VMIN)
	    N = N+3
	    GO TO 300
	  ENDIF
	  N = N+1
	  GO TO 300
C
 200	  CONTINUE
C	  FIX TWO BAD POINTS OUT OF SIX, NOT DONE YET
	  PRINT*,' TWO BAD POINTS AT N = ',N
	  N = N+1
C
 300	  CONTINUE
C
	IF(N.LE.2046) GO TO 100
C	ENDDO
C	
	TYPE*,'NUMBER FIXED, 71s, after 58s,',NBAD1,NBAD2
C
C	SAVE FVDATA FOR FIXCHECK PLOT
C
	DO N = 1,2048
	  FVDATA(N) = VDATA(N)
	ENDDO
	RETURN
	END
	SUBROUTINE FIXUP(N,ISTART,FDATA,WT,AVRPER,RMS,FIXED_V)
C
	EXTERNAL SINFIT,SINFIT2
	REAL X,DX,FDATA(5),WT(10)
C	COMMON /PLTBLK/ IZCNT,IPROCESS,ZCROSS(2048),ZINT(2048),
C     1   NDATA(2048),DATA(2050),SPECT(1025)
C
C
C	MORE ESTIMATES OF FREQUENCY
C
	  IF(ISTART.EQ.0)  X = .15
	  IF(AVRPER.NE.0.)  X = 1./AVRPER
C	  IF(ISTART.EQ.0) PRINT*,'1ST ESTIMATES OF X',JZCNT,X
C	  IF(ISTART.EQ.0) PRINT*,'WITH RMS=',RMS
	  DX = .1*X
C	  THE UNCERTAINTY IN PERIOD MUST BE .LE.  1 SAMPLE
C	  DX = AMAX1(RMS,.2)
C	  DX = AMIN1(.7*X,DX)
C	  IF(AVRPER.NE.0.) DX = 1./AVRPER - 1./(AVRPER+RMS)
	  SUMSQS = 1.E8
	  DO IT = 1,10
C	    CALL HUNTMN(X,DX,FDATA,WT,FIXED_V,SINFIT,SUMSQ)  
	    CALL HUNTMN4(X,DX,FDATA,WT,FIXED_V,SINFIT2,SUMSQ)  
	    X = ABS(X)
	    SUMSQS = SUMSQ
	    IF(SUMSQ.LT.1.E-9) GO TO 100
	  ENDDO
	  RETURN
 100	  CONTINUE
	  IF(X.NE.0.) AVRPER = .8*AVRPER + .2/X
	  RETURN
	END
       SUBROUTINE SINFIT(X,FDATA,WT,FIXED_V,SUMSQ)
C
C	THIS ROUTINE FITS A SINE WAVE TO DATA.  X IS SUPPOSED TO
C	BE VARIED BY HUNTMN, WHILE Y(1) TO Y(3) ARE DETERMINED BY
C	LEAST SQUARES FIT IN CLOSED FORM.  
C
C	X IS FREQUENCY IN CYCLES PER SAMPLE  (A SMALL NUMBER)
C
C	Y(1) IS AVERAGE (OFFSET)
C	Y(2) IS COEFF OF COSINE
C	Y(3) IS COEFF OF SINE
C
C	COMMON /FIXBLK/ MPDATA(2050),FDATA(5),FIXED_V
        DOUBLE PRECISION COS1,SIN1,COSN,SINN,SINNT,THT0
        REAL X,C(3,3),Y(3),ERR(10),WT(10),FDATA(5)
        DATA TWOPI /6.2831853/
C
	DO I = 1,3
	  Y(I)= 0.
	  DO J = 1,3
	    C(I,J) = 0.
	  ENDDO
	ENDDO
C
	THT0 = TWOPI*X
	COS1 = DCOS(THT0)
	SIN1 = DSIN(THT0)
	SINN = SIN1
	COSN = COS1
	DO N = 1,5
	  Y(1) = Y(1) + WT(N)*FDATA(N)
	  Y(2) = Y(2) + WT(N)*FDATA(N)*COSN
	  Y(3) = Y(3) + WT(N)*FDATA(N)*SINN
	  C(1,1) = C(1,1) + WT(N)
	  C(1,2) = C(1,2) + WT(N)*COSN
	  C(1,3) = C(1,3) + WT(N)*SINN
	  C(2,2) = C(2,2) + WT(N)*COSN**2
	  C(2,3) = C(2,3) + WT(N)*COSN*SINN
	  C(3,3) = C(3,3) + WT(N)*SINN**2
C
	  SINNT = COSN*SIN1 + SINN*COS1
	  COSN = COS1*COSN - SIN1*SINN
	  SINN = SINNT
	ENDDO
	C(3,1)= C(1,3)
	C(3,2) = C(2,3)
	C(2,1) = C(1,2)
	CALL GAUSSJ(C,3,3,Y,1,1)
C
	SUMSQ = 0.
	SUMN = 1.E-8
	THT0 = TWOPI*X
	COS1 = DCOS(THT0)
	SIN1 = DSIN(THT0)
	SINN = SIN1
	COSN = COS1
	DO N = 1,5
          ERR(N) =  FDATA(N) - Y(2)*COSN - Y(3)*SINN - Y(1)
	  SUMSQ = SUMSQ + WT(N)*ERR(N)**2
	  SUMN = SUMN + WT(N)
	  SINNT = COSN*SIN1 + SINN*COS1
	  COSN = COS1*COSN - SIN1*SINN
	  SINN = SINNT
	ENDDO
	SUMSQ = SUMSQ/SUMN
C	FIXED_V1 = Y(1) + Y(2)*COS(3.*THT0) + Y(3)*SIN(3.*THT0)
	FIXED_V = FDATA(3) - ERR(3)
C	PRINT*,'SINFIT EXIT,X,ERR,FDATA,SUMSQ',X,ERR(3),FDATA(3),SUMSQ
       RETURN
       END
       SUBROUTINE SINFIT2(X,FDATA,WT,FIXED_V,SUMSQ)
C
C	THIS ROUTINE FITS A SINE WAVE TO DATA.  X IS SUPPOSED TO
C	BE VARIED BY HUNTMN, WHILE Y(1) AND Y(2) ARE DETERMINED BY
C	LEAST SQUARES FIT IN CLOSED FORM.  
C
C	X IS FREQUENCY IN CYCLES PER SAMPLE  (A SMALL NUMBER)
C
C	Y(1) IS COEFF OF COSINE
C	Y(2) IS COEFF OF SINE
C
C	COMMON /FIXBLK/ MPDATA(2050),FDATA(5),FIXED_V
        DOUBLE PRECISION COS1,SIN1,COSN,SINN,SINNT,THT0
        REAL X,C(2,2),Y(2),ERR(10),WT(10),FDATA(5)
        DATA TWOPI /6.2831853/
C
	DO I = 1,2
	  Y(I)= 0.
	  DO J = 1,2
	    C(I,J) = 0.
	  ENDDO
	ENDDO
C
	THT0 = TWOPI*X
	COS1 = DCOS(THT0)
	SIN1 = DSIN(THT0)
	SINN = SIN1
	COSN = COS1
	DO N = 1,5
	  Y(1) = Y(1) + WT(N)*FDATA(N)*COSN
	  Y(2) = Y(2) + WT(N)*FDATA(N)*SINN
	  C(1,1) = C(1,1) + WT(N)*COSN**2
	  C(1,2) = C(1,2) + WT(N)*COSN*SINN
	  C(2,2) = C(2,2) + WT(N)*SINN**2
C
	  SINNT = COSN*SIN1 + SINN*COS1
	  COSN = COS1*COSN - SIN1*SINN
	  SINN = SINNT
	ENDDO
	C(2,1) = C(1,2)
	CALL GAUSSJ(C,2,2,Y,1,1)
C
	SUMSQ = 0.
	SUMN = 1.E-8
	THT0 = TWOPI*X
	COS1 = DCOS(THT0)
	SIN1 = DSIN(THT0)
	SINN = SIN1
	COSN = COS1
	DO N = 1,5
          ERR(N) =  FDATA(N) - Y(1)*COSN - Y(2)*SINN 
	  SUMSQ = SUMSQ + WT(N)*ERR(N)**2
	  SUMN = SUMN + WT(N)
	  SINNT = COSN*SIN1 + SINN*COS1
	  COSN = COS1*COSN - SIN1*SINN
	  SINN = SINNT
	ENDDO
	SUMSQ = SUMSQ/SUMN
C	FIXED_V1 = Y(1) + Y(2)*COS(3.*THT0) + Y(3)*SIN(3.*THT0)
	FIXED_V = FDATA(3) - ERR(3)
C	PRINT*,'SINFIT EXIT,X,ERR,FDATA,SUMSQ',X,ERR(3),FDATA(3),SUMSQ
       RETURN
       END
	SUBROUTINE HUNTMN4( X, DX, FDATA, WT, FIXED_V, FN, FF) 
C
C     THIS IS MODIFIED FOR WIND FROM MK V, APRIL 1988 
C
	REAL X, Y, DX, DXB, FDATA(5), WT(10)
	COMMON /HNTBLK/ NHUNT(25) 
	DATA NHUNT/25*1/
C
C

    	Y = X 
	   DXB = 0.  
	CALL FN(Y,FDATA,WT,FIXED_V,F0)  
	FM = F0 
	   IF(NHUNT(1).EQ.0) GO TO 2  
	   XB = X
	   Y = X + DX   
	   CALL FN(Y,FDATA,WT,FIXED_V, F1)
	   IF(F1.GE.FM) GO TO 4
	   FM = F1 
	   XB = Y
 4	   Y = X - DX   
	   CALL FN(Y,FDATA,WT,FIXED_V,F2) 
	   IF(F2.GE.FM) GO TO 8
	   FM = F2 
	   XB = Y
 8	   DEN = F1 + F2 - 2.*F0   
	   IF(DEN.EQ.0.) GO TO 2 
C	   DEN IS SECOND DERIV DIVIDED BY 2.*DX**2.  IF ITS NEGATIVE
C	   THEN THE EXTREMUM IS A MAXIMUM.  IN THAT CASE, GO ONE STEP
C	   BEYOND THE LOWEST POINT.
	   IF(DEN.GT.0.) THEN
	     DEX = -.5*(F1 - F2)/DEN  
	   ELSE
	     DEX = SIGN(2.,(F2-F1))
	   ENDIF
	   Y = X + DEX*DX
	   CALL FN(Y,FDATA,WT,FIXED_V,FF) 
	   IF(FF.LT.FM) GO TO 18 
C		NEW VALUE IS NOT BETTER
	   FF = FM 
	   Y = XB
	   IF((F1+F2).LT.3.*F0) GO TO 18
C		DX IS TOO BIG, ADJUST TO GIVE 50 % INCREASE IN F
	   DX = SQRT(ABS(F0/DEN))*DX
	   GO TO 19
 18	   CONTINUE
	   DX = .5*(ABS(DX) + ABS(X - Y))
 19	   DXB = Y - X
	   X = Y  
	   F0 = FF  
	   FM = FF 
 2	CONTINUE
C
	RETURN
C
C     ENTRY HERE MEANS THAT F1, F2, OR FF IS SMALLEST 
C
 34	IF(FF.LE.F1.AND.FF.LE.F2) RETURN
	DEX = 1.  
	IF(F2.LT.F1) DEX = -1. 
C	DO 35 I = 1,N  
	   Y = X + DEX*DXB
	   X = Y
C 35	CONTINUE
	FF = AMIN1(F1,F2) 
	RETURN
C
C
	END
