	SUBROUTINE FLUX_3DP(YYYYMMDD,ECOUNT,FLUX,FSTD)
C
C	RETURN ACCURATE FLUXES FROM STUART 
	THERE ARE TWO VERSIONS OF THIS.  3DPFLUX RETURNS FLUX AT
C		A CERTAIN TIME.  THIS ONE RETURNS AN AVERAGE FLUX AND
C		VARIANCE FOR THE RESISTANCE PAPERS
C
C
	CHARACTER*50 FILENAME
	INTEGER DATE,YYYYMMDD,ANGLE
C
C	FLUX = 1.68E7*FLUX
C	
C
	WRITE(FILENAME,123) YYYYMMDD
C 123	FORMAT('MONTHLY:[KELLOGG.EFLUX]FLUX_',I8.8,'.ASC')	
 123	FORMAT('[KELLOGG.WIND.PAPERS]FLUX_',I8.8,'.ASC')	
	OPEN(UNIT=83,FILE=FILENAME,STATUS='OLD',READONLY)
	TEFLUX = 0.
	SEFLUX = 0.
	ECOUNT = 0.
 140	CONTINUE
	READ(83,*,END=141,ERR=140) NYR,MO,NDAY,N4,N5,N6,EFLUX
	SEFLUX = SEFLUX + EFLUX**2
	TEFLUX = TEFLUX + EFLUX
	ECOUNT = ECOUNT + 1.
	GO TO 140
 141	CONTINUE
	TEFLUX = TEFLUX/ECOUNT
	SEFLUX = SEFLUX/ECOUNT - TEFLUX**2
	FSTD = SQRT(AMAX1(SEFLUX,0.))/TEFLUX
C	CHANGE TO Ne sqrt(Te in eV)
	FLUX = TEFLUX/1.68E7
	print 101,nyr,MO,NDAY,ecount,flux
 101	FORMAT(' nyr,n4,MO,NDAY,count,eflux,std',I6,I2.2,I2.2,F6.0,2E12.3)
C	WRITE(72,1072) YYYYMMDD,DENS,SDENS,TE,STE,FLUX,TEFLUX,SEFLUX,
C     1		FLUX-TEFLUX
C 1072	FORMAT(I9,F7.2,F7.3,F6.1,F6.2,E11.3,E11.3,E11.3,e11.3)
C	PRINT*,'END OF ZTABLE'
	RETURN
	END
