	SUBROUTINE FREQFIT
C
C	THIS SUBROUTINE FINDS THE FREQUENCY OF A SINE WAVE SIGNAL, AND
C	MAKES A LEAST SQUARES FIT TO FREQUENCY AND AMPLITUDE
C
C	FIRST IT ESTIMATES THE FREQUENCY BY DOING A FOURIER TRANSFORM
C	AND CHOOSING THE PEAK FREQUENCY COMPONENT.
C
C	THEN IT DOES A LEAST SQUARES FIT TO THE DATA, VARYING FREQUENCY,
C	AMPLITUDE, AND PHASE.
C
	  PRINT*,((ZCROSS(J+1)-ZCROSS(J)),J=1,IZCNT-1)
	  WPER1 = 2.*(ZCROSS(IZCNT)-ZCROSS(1))/(IZCNT-1)
	  PRINT*,'NEW WPER',WPER1
	  X(1) = ZCROSS(1)
	  X(2) = 2./WPER1
	  DX(1) = .5
	  DX(2) = .05*X(2)
	  CALL HUNTMN(2,X,DX,Y,FITZERO,SUMSQ)
	  WPER1 = 2./X(2)
	  PHI0 = X(1) + .25*WPER1	
	  PRINT*,'NEW WPER,PHI0=',WPER1,PHI0
	  NPHI0 = PHI0 + .5
C
C	  END OF FURTHER ZERO CROSSINGS FOR HIGH FREQUENCIES
C
	ENDIF
C
C
C	ALLOW FOR POSSIBILITY OF NEGATIVE PEAK
C
 	AMPT = AMPL
	IF(NDATA(NPHI0).LT.0) AMPT = -AMPL
	DO J = 1,2048
	  PHI = (J-PHI0)*TWOPI/WPER1
	  VOLTS(J) = .5*AMPT*COS(PHI)
	ENDDO
C	WRITE(27,1003) (J,VOLTS(J), NDATA(J),J=1,2048)
 1003	FORMAT(3(I9,E11.3,I5))
C
	CALL CALPLOT
C
C	NOW A SINE WAVE HAS BEEN FITTED THROUGH THE ZERO CROSSINGS AND
C	THE KNOWN AMPLITUDE, SO VOLTAGE INPUT FOR EACH DATA POINT HAS
C	BEEN CALCULATED

