	SUBROUTINE LSFIT(Y,X,WT,N,A,B,RMS)
C
C	FIT Y = A*X + B, WITH REMOVAL OF BAD POINTS
C
	DIMENSION Y(1),X(1),WT(1),ERR(1000),WTS(1000)
C
	IF(N.GT.1000) STOP 'TOO MANY POINTS FOR LSFITER'
C
	DO J = 1,N
	  WTS(J) = WT(J)
	ENDDO
	NREMOVE = 0
	LIMIT = .1*N + .5
C
 100	SYY=0.
	SXY=0.
	SXX=0.
	SX=0.
	SY=0.
	SC=0.
	DO 1 J = 1,N
	   SYY=SYY+WT(J)*Y(J)**2
	   SXY=SXY+WT(J)*X(J)*Y(J)
	   SXX=SXX+WT(J)*X(J)**2
	   SX=SX+WT(J)*X(J)
	   SY=SY+WT(J)*Y(J)
	   SC=SC+WT(J)
 1	CONTINUE
	A=0.
	B=0.
	DEN=SXX*SC-SX*SX
	IF(DEN.EQ.0.) TYPE 101
	IF(DEN.EQ.0.) RETURN
	A=(SXY*SC-SY*SX)/DEN
	B=(SXX*SY-SX*SXY)/DEN
	SUMSQ=SYY+SXX*A**2+SC*B**2-2.*SXY*A-2.*SY*B+2.*SX*A*B
	SM=SUMSQ/SC
	RMS=SQRT(AMAX1(SM,0.))
C
C	NOW FIND LARGE ERRORS, AND REMOVE POINTS, ONE (LARGEST) AT A TIME
C		 IF MORE THAN 4 SIGMA, BUT LIMIT TO 10% OF POINTS
C
	ERRMAX = 0.
	max=1
	DO J = 1,N
	  ERR(J) = Y(J) - A*X(J) - B
	  IF(ABS(WT(J)*ERR(J)).GT.ERRMAX) THEN
	    ERRMAX = ABS(WT(J)*ERR(J))
	    MAX = J	
	  ENDIF
	ENDDO
	IF(ERRMAX.GE.4.*RMS) THEN
	  WT(MAX) = 0.
	  NREMOVE = NREMOVE+1
	  PRINT*,'REMOVE, N,Y,X',MAX,Y(MAX),X(MAX)
	  IF(NREMOVE.LE.LIMIT) GO TO 100
	ENDIF
C
C	RESTORE WT
C
	DO J = 1,N
	  WT(J) = WTS(J)
	ENDDO
C
	RETURN
C
C
 101	FORMAT(' VANISHING DETERMINANT IN LSFIT')
	END

