	PROGRAM MAKESHKFILE
C
C	SEPARATES BOW SHOC CROSSING IN A GIVEN MODE
C
	INTEGER YYMMDD,HHMMSS,TDS_COUNT
	REAL SCETDAY
	ISPEED = 0
C
	OPEN(UNIT=69,FILE='MAKEFILE17.RESULTS',STATUS='OLD',READONLY)
C
 100	CONTINUE
	READ(69,*,END=300) SCETDAY,YYMMDD,HHMMSS,XTEMP,YTEMP,ZTEMP,
     1	      RTEMP,INOUT
     1       ,IQUAL,SCALE,ANGBN,SUMSQ,VALF,ALFMACH,VRAT,BRAT,DELB,
     2	      TDS_COUNT,TDSM,PWR,ISPS
	IF(ISPS.NE.ISPEED) GO TO 100
	IF(IQUAL.LE.1) GO TO 100
	WRITE(90,1107) SCETDAY,YYMMDD,HHMMSS,XTEMP,YTEMP,ZTEMP,RTEMP,INOUT
     1       ,IQUAL,SCALE,ANGBN,SUMSQ,VALF,ALFMACH,VRAT,BRAT,DELB,
     2	      TDS_COUNT,TDSM,PWR,ISPS
 1107	FORMAT(F8.0,I9,I7,3F8.2,F7.2,2I3,F6.2,F4.0,F6.3,F6.0,F6.2,3F5.1,
     1	 I4,F6.1,E9.2,I3)
c	at present, 128 characters above
	GO TO 100
 300	CONTINUE
	STOP
	END
