	SUBROUTINE OFFIT(X,SUMSQ)
C
	INCLUDE  'TDS_CALDATA.FOR'
	COMMON /OFFBLK/ ITCH,NHIST(256,6)
	REAL X(25),VBOUND(129),NVHIST(128)
C
	INDEX=5
	DO N = 1,129
	  VBOUND(N) = A(INDEX)*EXP(B(INDEX)*(N-.5))
	ENDDO
C
C	DO NEGATIVE SIDE
C
C	COUNT ZEROS, AND MAXIMUM NO OF OCCURRENCES, FOR LOW T/M NO.
	NZEROS = 0
	MAXNO = 0
	NPMAX = 49
	DO N = 1,10
	  NP = 128-N
	  IF(NHIST(NP,ITCH).EQ.0) NZEROS = NZEROS + 1
	  IF(NHIST(NP,ITCH).GT.MAXNO) THEN
		MAXNO = NHIST(NP,ITCH)
		NPMAX = NP
	  ENDIF
	ENDDO
	PRINT*,'NEG SIDE, NZEROS,NPMAX,MAXNO=',NZEROS,NPMAX,MAXNO
	DO N = 1,50
	  XN = 128-N
	  VCALC = A(INDEX)*(EXP(B(INDEX)*XN) - NOFFS(INDEX))
	  DO M = 1,128
	     IF(VCALC.LT.VBOUND(M+1).AND.VCALC.GE.VBOUND(M)) THEN
		NVHIST(M) = NVHIST(M) + NHIST(N,ITCH)
		GO TO 20
	     ENDIF
	  ENDDO
 20	  CONTINUE
	ENDDO
C
C	DO POSITIVE SIDE
C
C	COUNT ZEROS, AND MAXIMUM NO OF OCCURRENCES, FOR LOW T/M NO.
	NZEROS = 0
	MAXNO = 0
	NPMAX = 50
	DO N = 1,10
	  NP = 127+N
	  IF(NHIST(NP,ITCH).EQ.0) NZEROS = NZEROS + 1
	  IF(NHIST(NP,ITCH).GT.MAXNO) THEN
		MAXNO = NHIST(NP,ITCH)
		NPMAX = NP
	  ENDIF
	ENDDO
	PRINT*,'POS SIDE, NZEROS,NPMAX,MAXNO=',NZEROS,NPMAX,MAXNO
	DO N = 1,50
	  XN = 127+N
	  VCALC = A(INDEX)*(EXP(B(INDEX)*XN) - NOFFS(INDEX))
	  DO M = 1,128
	     IF(VCALC.LT.VBOUND(M+1).AND.VCALC.GE.VBOUND(M)) THEN
		NVHIST(M) = NVHIST(M) + NHIST(N,ITCH)
		GO TO 40
	     ENDIF
	  ENDDO
 40	  CONTINUE
	ENDDO
	RETURN
	END

