
	PROGRAM PLOTMK21
C
C	READS RESULTS FROM MAKEFILE21 RUN OF 23 FEB 2003
C
	CHARACTER*1 EVENT
	REAL SKEWT(2),BW(10),F(10),AMP(10),XX(2048),YY(2048)
	INTEGER NO_EVT(3),SCETI4(2)
C
	OPEN(UNIT=90,FILE='FOR090.DAT',STATUS='OLD',READONLY)
	OPEN(UNIT=91,FILE='FOR091.DAT',STATUS='OLD',READONLY)
	OPEN(UNIT=92,FILE='FOR092.DAT',STATUS='OLD',READONLY)
	NPT = 0
 100	CONTINUE
	READ(90,1011,END=200) sceti4,NO_EVT(1),EVENT,NO_PKS,DDIFF,
     1	 (F(M),M=1,5)
	READ(91,1012) sceti4,NO_EVT(2),EVENT,NO_PKS,SKEWT,
     1	 (BW(M),M=1,5)
	IF(NO_EVT(2).NE.NO_EVT(1)) PRINT*,'EVENT 2 DIFFERENT'
	READ(92,1013) sceti4,NO_EVT(3),EVENT,NO_PKS,XRE,YRE,ZRE,
     1	 (AMP(M),M=1,5)
	IF(NO_EVT(3).NE.NO_EVT(1)) PRINT*,'EVENT 3 DIFFERENT'
C
	NPT = NPT+1
	XX(NPT) = DDIFF
	YY(NPT) = AMP(1)
C	IF(AMP(1).GT.-15.) WRITE(77,*) SCETI4,NO_EVT(1),AMP(1),DDIFF
	GO TO 100
C
 1011	format(I10,I7,I10,A2,I3,F8.1,5F8.1)
 1012	format(I10,I7,I10,A2,I3,2F8.1,5F8.1)
 1013	format(I10,I7,I10,A2,I3,3F7.0,5F7.1)

 200	CONTINUE
	ITERM = 3
	CALL PLTDOT(XX,YY,NPT,ITERM)
	STOP
	END
	SUBROUTINE PLTLINE(ITERM)
C
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	DIMENSION YY(2048),PP(2048)
C
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
C
	XEND = 3000.
	  CALL MGOSETLOC(300.,1100.,XEND,2230.)
C
	  CALL MGOSETEXPAND(.85)
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
C	  CALL MGOPUTLABEL(53,STR,9)
	  CALL MGOSETEXPAND(1.)
C
C
	CALL MGOSETLTYPE(0)
	CALL MGOSETEXPAND(.6)
	CALL MGOCONNECT(PP,YY,2048)
	CALL MGOSETEXPAND(.8)
	CALL MGOBOX(0,2)
	CALL MGOSETEXPAND(1.)
	TRANGE = GY2-GY1
C	TINC = .08*TRANGE
	TINC = .07*TRANGE
	XTITLE = GX2 +.005*(GX2-GX1)
	YTITLE = GY2
	CALL MGOSETEXPAND(.8)
	CALL MGOSETLIM(-2.,YMIN,2050.,YMAX)
	CALL MGOTICKSIZE(0.,0.,0.,0.)  
	CALL MGOBOX(1,2)
	CALL MGOXLABEL(10,'SAMPLE NO.')
	CALL MGOYLABEL(10,'FREQ (kHZ)')
	CALL MGOSETEXPAND(1.)
C
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END	
	SUBROUTINE PLTDOT(XX,YY,NPT,ITERM)
C
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	DIMENSION YY(2048),XX(2048)
C
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
C
	XEND = 3000.
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(300.,300.,XEND,2230.)
	ELSE
	  CALL MGOSETLOC(100.,100.,800.,700.)
	ENDIF
C
	  CALL MGOSETEXPAND(.85)
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
C	  CALL MGOPUTLABEL(53,STR,9)
	  CALL MGOSETEXPAND(1.)
C
C
	YMIN = 1.E8
	YMAX = -1.E8
	XMIN = 1.E8
	XMAX = -1.E8
C
	DO N = 1,NPT
	  XMAX = AMAX1(XX(N),XMAX)
	  XMIN = AMIN1(XX(N),XMIN)
	  YMAX = AMAX1(YY(N),YMAX)
	  YMIN = AMIN1(YY(N),YMIN)
	ENDDO
	CALL MGOSETEXPAND(.8)
	TRANGE = GY2-GY1
C	TINC = .08*TRANGE
	TINC = .07*TRANGE
	XTITLE = GX2 +.005*(GX2-GX1)
	YTITLE = GY2
	CALL MGOSETEXPAND(.8)
C	CALL MGOSETLIM(XMIN,YMIN,XMAX,YMAX)
	CALL MGOSETLIM(-20.,YMIN,60.,YMAX)
C	CALL MGOTICKSIZE(0.,0.,0.,0.)  
	CALL MGOPOINTS(60.,1,XX,YY,NPT)
	CALL MGOBOX(1,2)
	CALL MGOXLABEL(10,'DIFF')
	CALL MGOYLABEL(10,'AMP DB')
	CALL MGOSETEXPAND(1.)
	CALL MGOPLOTID('PLOTMK21',' ')
C
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
c	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END	

