	program plot_preamp
c
C
	COMMON /GAINBLK/ PHASE,CGAIN
	COMPLEX CGAIN
	DATA TWOPI /6.2831853/
C
	DO I = 1,120
	  F = 500.*I
	  W = TWOPI*F
C	  GAIN = EYACPA(F)
C	  PHPA = PHASE
C	  DET = FFTAMP(2,F)
C	  GAIN = GAIN*DET
C	  PHASE = PHASE + PHPA
	  GAIN = FILTER_3DP(F)
	  WRITE(11,*) .001*F,GAIN,360.*PHASE/TWOPI
	  PRINT*, F,GAIN,360.*PHASE/TWOPI
	ENDDO
	STOP
	END
