

	PROGRAM PREAMP2
C
C	THIS PROGRAM CALCULATES THE ELECTRIC PREAMP RESPONSE, 
C	IT WRITES A FILE FOR011.DAT TO BE PLOTTED BY MONGO
C
	COMPLEX Z1,Z2,Z3,Z4,Y1,Y2,VIN,V1,V2,V3,CGAIN,gainac,gaindc
	CHARACTER*50 CH(20)
	COMMON /GAINBLK/ PHASE,CGAIN
C
	DATA TWOPI /6.2831853/
	DATA FHZMIN,FHZMAX,NF /.3,200.E3,130/
C
C	IPA = 1 IS EX, 2 IS EY, 3 IS EZ
C
	IACDC = 1     !  0 IS AC, 1 IS DC
	IPA = 0
C
C	ICHAC IS THE AC CHANNEL, ICHDC IS THE DC CHANNEL
C
	ICHAC = 1
	ICHDC = 7
C
	DO IPA = 1,3
C
	WRITE(11,*) 'PA=',IPA,'  AC,DC CHANNELS',ICHAC,ICHDC
	FRAT = ALOG(FHZMAX/FHZMIN)/(NF-1)
	FRAT = EXP(FRAT)
	FHZ = FHZMIN
	VIN = 1.
	DO 100 NN = 1,NF
	W = TWOPI*FHZ
C
	IF(IPA.EQ.1) THEN
	  VDC = XPADC(FHZ)
	  GAINDC = CGAIN
	  VDC = XPADC(FHZ)*FFTAMP(ICHDC,FHZ)
	  GAINDC = CGAIN
	  PHDC = 57.29578*PHASE
	  VAC = XPAAC(FHZ)*FFTAMP(ICHAC,FHZ)*FFT_FILTER(ICHAC,FHZ)
C	  VAC = XPAAC(FHZ)*FFTAMP(ICHAC,FHZ)
	  GAINAC = CGAIN
	  PHAC = 57.29578*PHASE
	ENDIF	
C
	IF(IPA.EQ.2) THEN
	  VDC = YPADC(FHZ)*FFTAMP(ICHDC,FHZ)*FFT_FILTER(ICHDC,FHZ)
C	  VDC = YPADC(FHZ)*FFTAMP(ICHDC,FHZ)
	  GAINDC = CGAIN
	  PHDC = 57.29578*PHASE
	  VAC = YPAAC(FHZ)*FFTAMP(ICHAC,FHZ)*FFT_FILTER(ICHAC,FHZ)
C	  VAC = YPAAC(FHZ)*FFTAMP(2,FHZ)
	  GAINAC = CGAIN
	  PHAC = 57.29578*PHASE
	ENDIF	
C
	IF(IPA.EQ.3) THEN
C	  VDC = ZPADC(FHZ)*FFTAMP(7,FHZ)*FFT_FILTER(7,FHZ)
	  VDC = ZPADC(FHZ)*FFTAMP(10,FHZ)*16.3
	  GAINDC = CGAIN
	  PHDC = 57.29578*PHASE
C	  VAC = ZPAAC(FHZ)*FFTAMP(2,FHZ)*FFT_FILTER(2,FHZ)
	  VAC = ZPAAC(FHZ)*FFTAMP(2,FHZ)
	  GAINAC = CGAIN
	  PHAC = 57.29578*PHASE
	ENDIF	
C
C
C	IF(FHZ.LT.1.2E4)WRITE(11,1001)FHZ,VAC,GAINAC,PHAC,VDC,GAINDC,PHDC
	WRITE(11,1001)FHZ,VAC,GAINAC,PHAC,VDC,GAINDC,PHDC
 1001	FORMAT(E13.4,3F7.3,F7.1,2X,3F7.3,F7.1)
C	IF(FHZ.LT.120.)PRINT*,FHZ,VAC,PHAC,VDC,PHDC
	FHZ = FHZ*FRAT
 100	CONTINUE
	CLOSE(UNIT=11)
	ICH = 1
	CH(1) = 'PRINTER 2'
C	CH(1) = 'terminal 3'
	CH(2) = 'ERASE'
	CH(3) = 'DATA FOR011.DAT'
	CH(4) = 'LINES 2 2000'
	CH(5) = 'TICKSIZE -1  0  .5 1.'
	IF(IACDC.EQ.1) CH(5) = 'TICKSIZE -1  0  .02  .1'
	CH(6) = 'XCOLUMN 1'
	CH(7) = 'XLOGARITHM 1'
	CH(8) = 'YCOLUMN 2'
C	CH(9) = 'LIMITS -1. 3.301  0.  1.265'     ! DC P/A'S LOW END
	CH(9) = 'LIMITS'
	CH(10) = 'CONNECT'
	CH(11) = 'GRID 0'
	CH(12) = 'EXPAND 1.2'
	ICH = 13
	CH(ICH) = 'BOX'
	ICH = ICH+1
	CH(ICH) = 'XLABEL FREQUENCY'
	ICH = ICH+1
	CH(ICH) = 'YLABEL P/A GAIN'
	ICH = ICH+3
	CH(ICH) = 'HARDCOPY'
	ICH = ICH+1
	CH(ICH) = 'ID'     		!  18
	ICH = ICH+1
	CH(ICH) = 'END'     		!  19
	ICHT = ICH
C
C	PLOT AC
C
	IF(IPA.EQ.1) THEN
	  ICH = 16
	  CH(ICH) = 'RELOCATE .25 1.8'
	  ICH = ICH+1
	  CH(ICH) = 'LABEL EX AC'
	ENDIF	
C
	IF(IPA.EQ.2) THEN
	  ICH = 16
	  CH(ICH) = 'RELOCATE .25 5.5'
	  ICH = ICH+1
	  CH(ICH) = 'LABEL EY AC'
	ENDIF	
C
	IF(IPA.EQ.3) THEN
	  ICH = 16
	  CH(ICH) = 'RELOCATE .25 5.'
	  ICH = ICH+1
	  CH(ICH) = 'LABEL EZ AC'
	ENDIF	
C
C	IF(IACDC.EQ.0) CALL MONGO(ICHT,CH,500,2,FRGN)
C
C	PLOT DC
C
	CH(7) = 'YCOLUMN 6'
C
	IF(IPA.EQ.1) THEN
	  ICH = 15
	  CH(ICH) = 'RELOCATE .25 .35'
	  ICH = ICH+1
	  CH(ICH) = 'LABEL EX DC'
	ENDIF	
C
	IF(IPA.EQ.2) THEN
	  ICH = 15
	  CH(ICH) = 'RELOCATE .25 .25'
	  ICH = ICH+1
	  CH(ICH) = 'LABEL EY DC'
	ENDIF	
C
	IF(IPA.EQ.3) THEN
	  ICH = 15
	  CH(ICH) = 'RELOCATE .25 .65'
	  ICH = ICH+1
	  CH(ICH) = 'LABEL EZ DC'
	ENDIF	
C
C	PRINT*,'MONGO CALLED FOR',IPA
	IF(IACDC.EQ.1) CALL MONGO(ICHT,CH,500,2,FRGN)

C
	ENDDO
C
	STOP
	END
	SUBROUTINE MGO
C	THIS IS  PREAMP.MGO
C	STORED HERE FOR REFERENCE--TO BE RUN INTERACTIVELY
C
C	DATA FOR011.DAT
C	FORMAT (E13.4,3F7.3,F6.1,2X,3F7.3,F6.1)
C	XCOLUMN 1
C	XLOGARITHM 1
C	YCOLUMN 4                 ! GAIN AC
C	LIMITS  -0.5  6.   0.  4.
C	CONNECT
C	BOX
C	XCOLUMN 1
C	XLOGARITHM 1
C	YCOLUMN 8                 ! GAIN DC
C	LIMITS 0.  6.  0.  5.
C	CONNECT
C	XLABEL LOG FREQUENCY (HZ)
C	YLABEL GAIN
C	ID
	RETURN
	END

