	program PRFOR43
C
C	PLOTS A HISTOGRAM OF WIND TDS HISTOGRAM
C
	CHARACTER*80 FILE
	CHARACTER*12 CH(20)
	COMMON /HISTBLK/ NHIST(256,6),NPOS(6),NEG(6)
	COMMON /HEADBLK/ FILE
C
	OPEN(UNIT=43,NAME='FOR043.DAT',TYPE='OLD',READONLY)
	DO I = 1,6
C	  READ(43,1043,ERR=20) (NHIST(J,I),J=1,100)
	  READ(43,*,ERR=20) (NHIST(J,I),J=1,256)
	ENDDO
	READ(43,100) FILE
	PRINT*,FILE
	READ(43,*) NPOS
	PRINT*,'NPOS',NPOS
	READ(43,*) NEG
	PRINT*,'NEG',NEG
C
 20	CONTINUE
	CALL PLTHIST(-1)
 100	FORMAT(A)
	STOP
	END
	SUBROUTINE PLTHIST(ITERM)
C
C	PLOT TDS HISTOGRAM FOR 5 CHANNELS
C
	CHARACTER*12 TITLE1(20),TITLE2(20)
	CHARACTER*20 STR
	character*4	pa(6,4)
	character*80	file
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	COMMON /HISTBLK/ NHIST(256,6),NPOS(6),NEG(6)
	COMMON /HEADBLK/ FILE
	DIMENSION YY(300),XX(300)
C
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
C
C	PLOT TDS DATA
C
	YTOP = 3000.
	YBOT = 300.
	PRANGE = (YTOP-YBOT)/6.
	PRINT*,'PLTMAX CALLED IN PRFOR43T, TIMES'

	XEND = 2300.

C
	  IF(ITERM.LT.0) THEN
	    CALL MGOSETLOC(500.,YBOT,XEND,YTOP)
	  ENDIF
C
	    CALL MGOSETEXPAND(.85)
	    IF(ITERM.GT.0) THEN
	      CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
	    ELSE
	      CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	    ENDIF
	   CALL MGOSETEXPAND(1.)
C
	DO NW = 1,3
	  CALL MGOWINDOW(1,3,NW)
	  IF(NW.EQ.1) THEN
	    NWU = 4
C	    IF((NPOS(1)+NEG(1)).GT.(NPOS(2)+NEG(2))) NWU = 1
	  ENDIF
	  IF(NW.EQ.2) THEN
	    NWU = 5
C	    IF((NPOS(3)+NEG(3)).GT.(NPOS(4)+NEG(4))) NWU = 3
	  ENDIF
	  IF(NW.EQ.3) NWU = 6
	  YMAX = 0.
	  DO N = 1,256
		YY(N) = NHIST(N,NWU)
	 	YMAX = AMAX1(YY(N),YMAX)
		XX(N) = N - 128
	  ENDDO
	  CALL MGOSETLIM(-128.,0.,128.,1.05*YMAX)
	  CALL MGOCONNECT(XX,YY,256)
	  CALL MGOBOX(1,2)
	  WRITE(STR,101) NWU
 101	  FORMAT(' NO. IN CH.',I2)
 102	  FORMAT(I8)
	  CALL MGOXLABEL(12,'TM NO. - 128')
	  CALL MGOYLABEL(14,STR)
	  CALL MGOSETEXPAND(1.)
	  TRANGE = GY2-GY1
	  TINC = .12*TRANGE
C
	  CALL MGOSETEXPAND(.6)
	  XPLACE = GX1 + .25*(GX2-GX1)
	  YPLACE = GY1 + .8*(GY2-GY1)
	  WRITE(STR,102) NEG(NWU)
	  CALL MGOGRELOCATE(XPLACE,YPLACE)
	PRINT*,'NW,NWU,NEG,STR',NW,NWU,NEG(NWU),STR
	  CALL MGOPUTLABEL(8,STR,5)
	  XPLACE = GX1 + .75*(GX2-GX1)
  	  WRITE(STR,102) NPOS(NWU)
	  CALL MGOGRELOCATE(XPLACE,YPLACE)
  	  CALL MGOPUTLABEL(8,STR,5)
	ENDDO
	CALL MGOSETEXPAND(.6)
	CALL MGOPLOTID('TDS HISTO','[KELLOGG.WIND]TDSRECT')
	CALL MGOSETEXPAND(.5)
	CALL MGOGRELOCATE(GX1,GY2)
	CALL MGOPUTLABEL(50,FILE,9)
	CALL MGOSETEXPAND(1.)
C
	PRINT*,'TERMINAL',ITERM
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END


