	PROGRAM PROCMK18
C
C	PROCESSES DATA WRITTEN TO FOR056.DAT BY MAKEFILE18, SEARCH FOR
C		LANGMUIR WAVES IN THE EARTH'S TAIL
C
	CHARACTER*1 EVENT
	REAL XX(400),YY(400),ZZ(400),RESOL(4),DBAVR(10),DBCOUNT(10)
	INTEGER SCETI4(2)
	DATA RESOL /118.,30.,8.,2./
	DATA DBAVR/10*0./
	DATA DBCOUNT/10*1.E-10/
C
C	OPEN(UNIT=79,FILE='FOR079.DAT;7',STATUS='OLD',READONLY)
C	OPEN(UNIT=79,FILE='ORBIT.TABLE',STATUS='OLD',READONLY)
C	OPEN(UNIT=79,FILE='GSM.TABLE',STATUS='OLD',READONLY)
C
	XMINDB = 20.*ALOG10(.1)
	XMAXDB = 20.*ALOG10(100.)
	NBIN = 30
	ILOAD = 0
	X = XMINDB
	CALL HISTOG(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL1)
	CALL HISTOG60(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL2)
	CALL HISTOG90(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL3)
	XMINEL = 0.
	XMAXEL = 1.
	CALL HISTOGEL(ILOAD,X,NBIN,XMINEL,XMAXEL,TOTAL4)
	XMINA = 0.
	XMAXA = 90.
	CALL HISTOGANG(ILOAD,X,NBIN,XMINA,XMAXA,TOTAL5)
	CALL EACORR(ILOAD,X,X)
	ILOAD = 1
C
C	OPEN(UNIT=56,FILE='MAKEFILE18.RESULTS',STATUS='OLD',READONLY)
c	OPEN(UNIT=56,FILE='MAKEFILE18.RESULTS;24',STATUS='OLD',READONLY)
	OPEN(UNIT=56,FILE='MAKEFILE18SAVE.RESULTS',STATUS='OLD',READONLY)
C
 100	CONTINUE
	
C	READ (56,*,END=200,ERR=100) NO_EVT,SCETI4,ISPS,IZCNT,
C     1		F1,F2,F3,ZCBW,FRBW,FP_3DP,FP_SWE,XMAX,XRE,YRE,ZRE
	READ(56,1111,END=200,ERR=100) SCETI4,NO_EVT,EVENT,ISPS,IZCNT,FREQHZ,
     1	 FAVR,FREQ,BWAVR,FRBW,FP_3DP,EMAX,XRE,YRE,ZRE,XYPH,PANGLE,RATIO
C	1111 IS NOW 114 CHARACTERS
 1111	FORMAT(I10,I8,I10,A2,I2,I4,3F7.0,F7.2,F6.2,F7.0,F6.1,3F7.1,2F7.1
     1		,F6.3)
C	BWLIM = RESOL(ISPS+1)
C	IF(BWAVR.GT.BWLIM) GO TO 100
	IF(FRBW.GT..1) GO TO 100        ! REMOVE ONE SPURIOUS EVENT
	IF(ABS(YRE).GT.34.) GO TO 100	! REMOVE SOME EVENTS OUTSIDE TAIL
c********
C	THIS USES A FORMAT FOR WHICH TDSVIST WORKS, BUT NTMDAY IS FAKE
	ICHOOSE = 0
	IF(ICHOOSE.EQ.1) THEN
	NTMDAY = MOD(SCETI4(1),100)
	IF(ABS(PANGLE).GT.40.) GO TO 100
	write(58,1114) SCETI4,NO_EVT,NTMDAY,EVENT,ISPS,IZCNT,FREQHZ
     1	 ,FAVR,FREQ,BWAVR,FRBW,FP_3DP,EMAX,XRE,YRE,ZRE,XYPH,PANGLE,RATIO
C	1114 IS NOW 113 CHARACTERS
 1114	FORMAT(I10,I7,I10,I3,A2,I2,I4,3F7.0,F7.2,F6.2,F7.0,F6.1,3F7.1
     1		,2F7.1,F6.3)
C
	WRITE(59,1111) SCETI4,NO_EVT,EVENT,ISPS,IZCNT,FREQHZ,
     1	 FAVR,FREQ,BWAVR,FRBW,FP_3DP,EMAX,XRE,YRE,ZRE,XYPH,PANGLE,RATIO
	GO TO 100
	ENDIF
C********
	ICHOOSE = 0
	IF(ICHOOSE.EQ.1) THEN
	  IF(ABS(PANGLE).LT.40.) THEN
	  ENDIF
	ENDIF 
C********
C	CALCULATE AVERAGE AMPLITUDES FOR QPERP AND QPAR
	ICHOOSE = 0
	IF(ICHOOSE.EQ.1) THEN
	  IF(XRE.GT.-85.) GO TO 100
	  IF(EMAX.GT.0.) THEN
	    X = 20.*ALOG10(EMAX)
	  ELSE
	    GO TO 100
	  ENDIF
	  IF(ABS(PANGLE).LT.40.) THEN
	    DBAVR(1) = DBAVR(1) + X
	    DBCOUNT(1) = DBCOUNT(1) + 1.
	  ELSE
	    DBAVR(2) = DBAVR(2) + X
	    DBCOUNT(2) = DBCOUNT(2) + 1.
	  ENDIF
	GO TO 100
	ENDIF
C********
C	CALCULATE HISTOGRAM OF AMPLITUDES AS FUNCTION OF DISTANCE
	NP = NP+1
	XX(NP) = XRE
	YY(NP) = YRE
	ZZ(NP) = ZRE
C	PRINT*,'NP,EMAX,A,EL',NP,EMAX,PANGLE,RATIO
	IF(EMAX.GT.0.) THEN
	  X = 20.*ALOG10(EMAX)
	  IF(XRE.GE.-60.) THEN	
	    DBAVR(1) = DBAVR(1) + X
	    DBCOUNT(1) = DBCOUNT(1) + 1.
	    CALL HISTOG(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL1)
	  ENDIF
	  IF(XRE.LT.-60.AND.XRE.GT.-75.) THEN
	    DBAVR(2) = DBAVR(2) + X
	    DBCOUNT(2) = DBCOUNT(2) + 1.
	    CALL HISTOG60(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL2)
	  ENDIF
	  IF(XRE.LT.-85.) THEN
	    DBAVR(3) = DBAVR(3) + X
	    DBCOUNT(3) = DBCOUNT(3) + 1.
	    CALL HISTOG90(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL3)
	  ENDIF
	ELSE
	  PRINT*,'SCETI4,NO_EVT,EMAX',SCETI4,NO_EVT,EMAX	
	ENDIF
C
	X = RATIO
	CALL HISTOGEL(ILOAD,X,NBIN,XMINEL,XMAXEL,TOTAL4)
	Y = ABS(PANGLE)
	IF(Y.GT.90.) Y = 180. - Y
	CALL HISTOGANG(ILOAD,Y,NBIN,XMINA,XMAXA,TOTAL5)
	CALL EACORR(ILOAD,X,Y)
	GO TO 100
 200	CONTINUE
C
	ILOAD = 2
	CALL HISTOG(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL1)
	CALL HISTOG60(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL2)
	CALL HISTOG90(ILOAD,X,NBIN,XMINDB,XMAXDB,TOTAL3)
	CALL HISTOGEL(ILOAD,X,NBIN,XMINEL,XMAXEL,TOTAL4)
	CALL HISTOGANG(ILOAD,X,NBIN,XMINA,XMAXA,TOTAL5)
	CALL EACORR(ILOAD,X,Y)
C
	WRITE(76,*) DBCOUNT(1),DBAVR(1)/DBCOUNT(1)
	WRITE(76,*) DBCOUNT(2),DBAVR(2)/DBCOUNT(2)
	WRITE(76,*) DBCOUNT(3),DBAVR(3)/DBCOUNT(3)
C	CLOSE(UNIT=79)
	CLOSE(UNIT=56)
	STOP
	END	
C
	SUBROUTINE PLOTEVENTS
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
	INTEGER*4 SCETI4(2)
	REAL*4 XX(500),YY(500),ZZ(500)
C
	ITERM = -1
c	ITERM = 3
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
	NP = 0
	NOR = 0
	CALL MGOSETEXPAND(1.)
	XMAX = -100.
	XMIN = 0.
C	YMAX = -70.
	YMAX = -31.
	YMIN = -YMAX
	CALL MGOWINDOW(1, 2, 1)
	CALL MGOSETLIM(XMIN,YMIN,XMAX,YMAX)
	CALL MGOBOX(1,2)
	CALL MGOXLABEL(5,'X(RE)')
	CALL MGOYLABEL(5,'Y(RE)')
	CALL MGOWINDOW(1, 2, 2)
	CALL MGOSETLIM(XMIN,YMIN,XMAX,YMAX)
	CALL MGOBOX(1,2)
	CALL MGOXLABEL(5,'X(RE)')
	CALL MGOYLABEL(5,'Z(RE)')
c	go to 200		! OK at this point
C
C	PLOT ORBITS
	IF(XRE.GT.-10.) THEN
	  CALL MGOWINDOW(1, 2, 1)
	  CALL MGOSETLIM(XMIN,YMIN,XMAX,YMAX)
	  CALL MGOCONNECT(XX,YY,NOR)
c  	CALL MGOSETEXPAND(1.)
	  CALL MGOWINDOW(1, 2, 2)
	  CALL MGOSETLIM(XMIN,YMIN,XMAX,YMAX)
	  CALL MGOCONNECT(XX,ZZ,NOR)
	  NOR = 0
	ELSE
	  NOR = NOR+1
	  XX(NOR) = XRE
	  YY(NOR) = YRE
	  ZZ(NOR) = ZRE
	ENDIF
c	go to 200		! OK at this point
	GO TO 150
C
C	PLOT LANGMUIR AND BERNSTEIN WAVES FOUND
C
 100	CONTINUE
C	write(44,*) '1',x1,x2,y1,y2
	READ (56,*,END=200,ERR=100) NO_EVT,SCETI4,ISPS,IZCNT,
     1		F1,F2,F3,ZCBW,FRBW,FP_3DP,FP_SWE,XMAX,XRE,YRE,ZRE
	NP = NP+1
	XX(NP) = XRE
	YY(NP) = YRE
	ZZ(NP) = ZRE
	GO TO 100
 200	CONTINUE
C
 150	CONTINUE
C	write(44,*) 'GOT TO 200,NP=',NP
	CALL MGOSETEXPAND(1.)
	CALL MGOWINDOW(1, 2, 1)
	CALL MGOPOINTS(80.,1,XX,YY,NP)
	CALL MGOBOX(1,2)
C
c	write(44,*) '3',x1,x2,y1,y2
	CALL MGOWINDOW(1, 2, 2)
	CALL MGOPOINTS(80.,1,XX,ZZ,NP)
	CALL MGOBOX(1,2)
C
C	write(44,*) 'GOT TO PLOTID, NP=',NP
	CALL MGOPLOTID('[.WIND]PLOTMK18','FROM MAKEFILE18')
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
C	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
	END
	SUBROUTINE HISTOG(ILOAD,X,NBIN,XMIN,XMAX,TOTAL)
C
C	INTEGER*4 NARR
	DIMENSION NARR(256)
	DATA NARR /256*0/
C
	IF(ILOAD.EQ.0) THEN
	  DO N = 1,256
	    NARR(N) = 0
	  ENDDO
	  TOTAL = 0.
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  XT = AMAX1(X,XMIN)
	  XT = AMIN1(XT,XMAX)
	  IBIN = (NBIN-1)*(XT-XMIN)/(XMAX-XMIN) + 1
	  NARR(IBIN) = NARR(IBIN)+1
	  TOTAL = TOTAL + 1.
	  RETURN
	ENDIF
C
C	WRITE OUTPUT
C
	DO IBIN = 1,NBIN
	  XT = (IBIN-.5)*(XMAX-XMIN)/(NBIN-1) + XMIN
	  XT = 10.**(XT/20.)
	  WRITE(55,*) IBIN,XT,NARR(IBIN)
	ENDDO
	  WRITE(55,*) TOTAL
	RETURN
	END
	SUBROUTINE HISTOG60(ILOAD,X,NBIN,XMIN,XMAX,TOTAL)
C
C	INTEGER*4 NARR
	DIMENSION NARR(256)
	DATA NARR /256*0/
C
	IF(ILOAD.EQ.0) THEN
	  DO N = 1,256
	    NARR(N) = 0
	  ENDDO
	  TOTAL = 0.
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  XT = AMAX1(X,XMIN)
	  XT = AMIN1(XT,XMAX)
	  IBIN = (NBIN-1)*(XT-XMIN)/(XMAX-XMIN) + 1
	  NARR(IBIN) = NARR(IBIN)+1
	  TOTAL = TOTAL + 1.
	  RETURN
	ENDIF
C
C	WRITE OUTPUT
C
	DO IBIN = 1,NBIN
	  XT = (IBIN-.5)*(XMAX-XMIN)/(NBIN-1) + XMIN
	  XT = 10.**(XT/20.)
	  WRITE(66,*) IBIN,XT,NARR(IBIN)
	ENDDO
	  WRITE(66,*) TOTAL
	RETURN
	END
	SUBROUTINE HISTOG90(ILOAD,X,NBIN,XMIN,XMAX,TOTAL)
C
C	INTEGER*4 NARR
	DIMENSION NARR(256)
	DATA NARR /256*0/
C
	IF(ILOAD.EQ.0) THEN
	  DO N = 1,256
	    NARR(N) = 0
	  ENDDO
	  TOTAL = 0.
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  XT = AMAX1(X,XMIN)
	  XT = AMIN1(XT,XMAX)
	  IBIN = (NBIN-1)*(XT-XMIN)/(XMAX-XMIN) + 1
	  NARR(IBIN) = NARR(IBIN)+1
	  TOTAL = TOTAL + 1.
	  RETURN
	ENDIF
C
C	WRITE OUTPUT
C
	DO IBIN = 1,NBIN
	  XT = (IBIN-.5)*(XMAX-XMIN)/(NBIN-1) + XMIN
	  XT = 10.**(XT/20.)
	  WRITE(77,*) IBIN,XT,NARR(IBIN)
	ENDDO
	  WRITE(77,*) TOTAL
	RETURN
	END
	SUBROUTINE HISTOGANG(ILOAD,X,NBIN,XMIN,XMAX,TOTAL)
C
C	INTEGER*4 NARR
	DIMENSION NARR(256)
	DATA NARR /256*0/
C
	IF(ILOAD.EQ.0) THEN
	  DO N = 1,256
	    NARR(N) = 0
	  ENDDO
	  TOTAL = 0.
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  XT = AMAX1(X,XMIN)
	  XT = AMIN1(XT,XMAX)
	  IBIN = (NBIN-1)*(XT-XMIN)/(XMAX-XMIN) + 1
	  NARR(IBIN) = NARR(IBIN)+1
	  TOTAL = TOTAL + 1.
	  RETURN
	ENDIF
C
C	WRITE OUTPUT
C
	DO IBIN = 1,NBIN
	  XT = (IBIN-.5)*(XMAX-XMIN)/(NBIN-1) + XMIN
	  WRITE(81,*) IBIN,XT,NARR(IBIN)
	ENDDO
	  WRITE(81,*) TOTAL
	RETURN
	END
	SUBROUTINE HISTOGEL(ILOAD,X,NBIN,XMIN,XMAX,TOTAL)
C
C	INTEGER*4 NARR
	DIMENSION NARR(256)
	DATA NARR /256*0/
C
	PRINT*,'EL',ILOAD,X,XMIN,XMAX,TOTAL
	IF(ILOAD.EQ.0) THEN
	  DO N = 1,256
	    NARR(N) = 0
	  ENDDO
	  TOTAL = 0.
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  XT = AMAX1(X,XMIN)
	  XT = AMIN1(XT,XMAX)
	  IBIN = (NBIN-1)*(XT-XMIN)/(XMAX-XMIN) + 1
	  NARR(IBIN) = NARR(IBIN)+1
	  TOTAL = TOTAL + 1.
	  RETURN
	ENDIF
C
C	WRITE OUTPUT
C
	DO IBIN = 1,NBIN
	  XT = (IBIN-.5)*(XMAX-XMIN)/(NBIN-1) + XMIN
	  WRITE(78,*) IBIN,XT,NARR(IBIN)
	ENDDO
	  WRITE(78,*) TOTAL
	RETURN
	END
	SUBROUTINE EACORR(ILOAD,X,Y)
	DIMENSION XX(400),YY(400)
C
	IF(ILOAD.EQ.0) THEN
	  XMAX = -1.E8
	  YMAX = XMAX
	  XMIN = 1.E8
	  YMIN = XMIN
	  NTOTAL = 0
	  RETURN
	ENDIF
C
	IF(ILOAD.EQ.1) THEN
	  NTOTAL = NTOTAL + 1
	  XMAX = AMAX1(X,XMAX)
	  XMIN = AMIN1(X,XMIN)
	  YMAX = AMAX1(Y,YMAX)
	  YMIN = AMIN1(Y,YMIN)
	  XX(NTOTAL) = X
	  YY(NTOTAL) = Y
	  RETURN
	ENDIF
C
C	PLOT OUTPUT, no, make a file
C
	do n = 1,ntotal
	  write(82,*) n,xx(n),yy(n)
	enddo
	RETURN
	END
