	SUBROUTINE PUBCOMBO(ITERM)
C
C	SAME AS COMBO EXCEPT NO RAW DATA
C	THE FIRST (TOP) PANEL IS THE DATA IN PHYSICAL UNITS, 
C	THE SECOND IS THE FREQ  FROM 
C	ZERO CROSSINGS, AND THE THIRD IS THE FOURIER TRANSFORM
C	THIS VERSION DOES NOT HAVE INTERPOLATED PHYSICAL DATA
C
	CHARACTER*12 TITLE(25)
	CHARACTER*120 STR
	CHARACTER*4 EVENT
	CHARACTER*1 DISPOSE
	INTEGER*4 TDS_CHANNEL,S_SCET(2)
	INTEGER*4 NUMBER_EVENT,YYYY,DD
	REAL*8 BEGINevt,endevt
	integer*4 dds
	COMMON /HEADBL/ TITLE,EVENT,NUMBER_EVENT
	common /headblk/ major,minor,s_scet,sunclock,beginevt,endevt,dds
	COMMON /PLTBLK/ IZCNT,IPROCESS,ZCROSS(2048),ZINT(2048),
     1   NDATA(2048),DATA(2050),SPECT(1025)
	COMMON /TDS_STATUS/ TDS_CHANNEL,SPS,FILTER,IRX,ISPS
	COMMON /STATUS/ FFILTER(4),SFILTER(4),FSPS(4),SSPS(4),SPINRATE
	COMMON /PUB/ HDATA(4100)
	DATA TWOPI /6.2831853/
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	DIMENSION YY(4096),YYT(4096),PP(4096),ANG(2048)
C
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
C
C	PUT LABELS ON RIGHT HAND SIDE
C
	IF(ITERM.LT.0) THEN
	  XSTART = 350.
	  XEND = 2000.
	  CALL MGOSETLOC(XSTART,400.,XEND,2900.)
	ELSE
	  XSTART = 100.
	  XEND = 880.
	  CALL MGOSETLOC(XSTART,80.,XEND,750.)
	ENDIF
	AVRFREQ=0.
	IF(IZCNT.GT.1) THEN
	  AVRPER = (ZCROSS(IZCNT)-ZCROSS(1))/(IZCNT-1)
	  AVRFREQ = .001*SPS/AVRPER
	ENDIF
	TITLE(20) = ' AVR.FREQ.'
	WRITE(TITLE(21),1020) AVRFREQ
 1020	FORMAT(F8.2,' kHZ')
C
	XTITLE = GX2 +.02*(GX2-GX1)
	YTITLE = GY2
	TRANGE = GY2-GY1
	TINC = .03*TRANGE
	CALL MGOSETEXPAND(.8)
	DO N = 2,21
	  IF(N.EQ.4) YTITLE = YTITLE - TINC
	  IF(N.EQ.6) YTITLE = YTITLE - TINC
	  IF(N.EQ.12) YTITLE = YTITLE + TINC
	  IF(N.EQ.20) YTITLE = YTITLE - TINC
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  CALL MGOLABEL(12,TITLE(N))
	  YTITLE = YTITLE - TINC
	ENDDO
C
	  YTITLE = YTITLE-2.*TINC
	  CALL MGOSETEXPAND(.7)
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  CALL MGOLABEL(12,' TRANSMITTED @')
	  YTITLE = YTITLE-.8*TINC
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  FDAY = BEGINEVT - DFLOAT(DDS)
          NHR = FDAY*24.
	  MIN = FDAY*1440. - (NHR*60)
	  SEC = FDAY*86400. - 3600.*NHR - 60.*MIN	  
	  WRITE(STR,1028) NHR,MIN,SEC
 1028	  FORMAT(1X,I2.2,I2.2,1X,F6.2)
	  CALL MGOLABEL(12,STR)
	  call w_ur8_to_ymd(BEGINEVT,yyyy,mon,dd,hh,mm,ss,ms)
C	  call w_ur8_to_ydoy(beginevt,yyyy,doy,msday)
	  WRITE(STR,1029) yyyy,mon,dd
 1029	   format(I5,'/',I2,'/',I2)
	  YTITLE = YTITLE-.8*TINC
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  CALL MGOLABEL(12,STR)
C
	  YTITLE = YTITLE-TINC
	  CALL MGOSETEXPAND(.7)
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  CALL MGOLABEL(10,' SUN ANGLE')
	  YTITLE = YTITLE-.8*TINC
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  WRITE(STR,1027) SUNCLOCK*360./4096.
 1027	  FORMAT(F6.1' DEG.')
	  CALL MGOLABEL(10,STR)

	IF(IPROCESS.GE.3) THEN
	  CALL MGOSETEXPAND(.7)
	  YTITLE = YTITLE-2.*TINC
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  CALL MGOLABEL(8,' BAD A/D')
	  YTITLE = YTITLE-2.*TINC
	  CALL MGOGRELOCATE(XTITLE,YTITLE)
	  CALL MGOLABEL(9,'CORRECTED')
	  CALL MGOSETEXPAND(.8)
	ENDIF
C
	  CALL MGOSETEXPAND(.85)
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
	  CALL MGOSETEXPAND(1.)
	CALL MGOSETEXPAND(.8)
	CALL MGOPLOTID(EVENT,'[.WIND]TDSVIS,PUBCOMBO')
	CALL MGOSETEXPAND(1.)
C
	END_ANGLE =  -360.*(SUNCLOCK-14.)/4096. - 45. ! ANGLE SUN TO +EX AT END
	IF(END_ANGLE.LT.-180.) END_ANGLE = END_ANGLE + 360.
	IF(END_ANGLE.GT.180.)  END_ANGLE = END_ANGLE - 360.
	DANG = SPINRATE*360./SPS/TWOPI
	ST_ANGLE = END_ANGLE + 3072.*DANG  ! ANGLE SUN TO +EX AT START 16nov99
	END_ANGLE = END_ANGLE + 1024.*DANG
c	ST_ANGLE = END_ANGLE + 2048.*DANG	  ! ANGLE SUN TO +EX AT START
C
C
C	PLOT TDS DATA IN PHYSICAL UNITS
C
C	     CALL REALFT(HDATA,2048,-1)		! USE FFT TO INTERPOLATE
C	     DO IK = 1,4096
C	       HDATA(IK) = HDATA(IK)/1024.
C	       VDATA(IK) = DATA(IK)
C	     ENDDO
c
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(XSTART,1800.,XEND,2900.)
	ELSE
	  CALL MGOSETLOC(XSTART,465.,XEND,750.)
	ENDIF
	  YMAX = 0.
C	  EFFLEN = 45.				  ! X ANTENNA  18-JUL-95
C	  IF(IRX.EQ.2.OR.IRX.EQ.5) EFFLEN = 6.    ! Y ANTENNA   "
C	  IF(IRX.EQ.3.OR.IRX.EQ.6) EFFLEN = 4.    ! Z ANTENNA   "
	  EFFLEN = 41.1				  ! X ANTENNA   9-NOV-96
	  IF(IRX.EQ.2.OR.IRX.EQ.5) EFFLEN = 3.79  ! Y ANTENNA   "
	  IF(IRX.EQ.3.OR.IRX.EQ.6) EFFLEN = 2.17  ! Z ANTENNA   "
	  ACORR = 1000.
	  IF(IRX.GE.7) THEN			! SEARCH COILS
		ACORR=1.
		EFFLEN = 1.
	  ENDIF
C	CHANGE TO mV/meter
	  DO N = 1,2048
 	    PP(N) = 1000.*(N-1)/SPS
	    ANG(N) = ST_ANGLE - (N-1)*DANG
C 	    PP(N) = N
C	    YY(N) = ACORR*HDATA(N)/EFFLEN		! INTERPOLATED DATA
	    YY(N) = ACORR*DATA(N)/EFFLEN
	    YMAX = AMAX1(YY(N),YMAX)
	    YMAX = AMAX1(-YY(N),YMAX)
	  ENDDO
C
c********
c	do n = 1,4096
c	  write(97,*) pp(n),yy(n)
c	enddo
c*****
C	PRINT*,'MAX mV/m',YMAX
C	CALL MGOTICKSIZE(0.,0.,0.,0.)  
	CALL MGOSETLIM(PP(1),-YMAX,PP(2048),YMAX)
C
c	CALL MGOGRID(0)
C	CALL MGOSETLTYPE(1)
c	CALL MGOGRID(1)
	CALL MGOSETLTYPE(0)
	CALL MGOSETEXPAND(.6)
	CALL MGOCONNECT(PP,YY,2048)
	CALL MGOSETEXPAND(.7)
	CALL MGOBOX(1,2)
	CALL MGOXLABEL(5,'mSEC.')
	IF(IRX.GE.7) THEN			! SEARCH COILS
	  CALL MGOYLABEL(2,'nT')
	ELSE
	  CALL MGOYLABEL(4,'mV/m')
	ENDIF
	CALL MGOSETEXPAND(1.)
C
C	PLOT FREQUENCY FROM ZERO CROSSINGS, ALSO SMOOTH FREQUENCY
C
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(XSTART,1250.,XEND,1595.)
	ELSE
	  CALL MGOSETLOC(XSTART,310.,XEND,413.)
	ENDIF

C
	SPSKHZ = .001*SPS
	YMIN = .5*SPSKHZ
	YMAX = 0.
C	PRINT*,'IZCNT',IZCNT
	DO N = 1,IZCNT-1
	  IF(ZINT(N).EQ.0.) PRINT*,'IN PLOT, ZINT=0 AT',N
	  YY(N) = SPSKHZ/ZINT(N)
	  PP(N) = 1000.*(ZCROSS(N)+ZCROSS(N+1))/SPS
	  YMIN = AMIN1(YY(N),YMIN)
	  YMAX = AMAX1(YY(N),YMAX)
	ENDDO
C	
C	SMOOTH FREQUENCY
C
	YMAX = 0.
	DO N = 2,IZCNT-2
	  YYT(N) = .4*YY(N) + .3*(YY(N+1)+YY(N-1))
	  YMAX = AMAX1(YYT(N),YMAX)
	ENDDO
	YYT(1) = YY(1)
	IF(IZCNT.GT.1) YYT(IZCNT-1) = YY(IZCNT-1)
C
  	YMAX = AMIN1(.5*SPSKHZ,1.1*YMAX)
C	PRINT*,'YMIN,YMAX',YMIN,YMAX
C	YMIN =  .5*AVRFREQ
C	YMAX = 1.25*AVRFREQ
C**********
	YMIN =  0.
C	YMAX =  3.
C	YMIN =  18.
C	YMAX =  26.
C	YMIN =  12.
C	YMAX =  17.
C	PRINT*,'SET TO   ',YMIN,YMAX
	CALL MGOSETEXPAND(.8)
	CALL MGOSETLIM(0.,YMIN,PP(2048),YMAX)
C	CALL MGOTICKSIZE(0.,0.,0.,0.)  
	CALL MGOCONNECT(PP,YYT,IZCNT-1)
	CALL MGOSETLIM(ANG(1),YMIN,ANG(2048),YMAX)
	CALL MGOBOX(1,2)
	CALL MGOSETEXPAND(.7)
	CALL MGOXLABEL(16,'ANGLE,SUN TO EX')
	CALL MGOYLABEL(10,'FREQ (kHZ)')
	CALL MGOSETEXPAND(1.)
C
C	PLOT FOURIER SPECTRUM
C
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(XSTART,300.,XEND,1020.)
	ELSE
	  CALL MGOSETLOC(XSTART,50.,XEND,264.)
	ENDIF
C
C
	N1 = 3
	N2 = 2048
	YMAX = -500.
	YMIN =  500.
	XMAX = 0.
	SPSUSE = SPS
	IF(TDS_CHANNEL.LE.2) SPSUSE = .001*SPS
	DO N = N1,N2,2
	  NP = (N-1)/2
	  PP(NP) = NP*SPSUSE/2048.
C	  YY(NP) = 10.*ALOG10(DATA(N)**2 + DATA(N+1)**2)
	  YY(NP) = SPECT(NP)
	  XMAX = AMAX1(XMAX,PP(NP))
	  IF(YY(NP).GT.YMAX) THEN
	    NPSV = NP
	    YMAX = YY(NP)
	  ENDIF
	  YMIN = AMIN1(YMIN,YY(NP))
	ENDDO
C
C	CALCULATE 10 DB BANDWIDTH
C
	MAXCOUNT = 0
	LOWCOUNT = 0
	DO N=NPSV,1024
	   IF(SPECT(N).GT.(YMAX-10.)) THEN
		MAXCOUNT = MAXCOUNT+LOWCOUNT+1
		LOWCOUNT = 0
	   ELSE
		LOWCOUNT = LOWCOUNT+1
	   ENDIF
	   IF(LOWCOUNT.GT.3) GO TO 410
	ENDDO
C 410	MAXCOUNT = MAXCOUNT + LOWCOUNT
 410	CONTINUE
	LOWCOUNT = 0
	DO N=NPSV-1,1,-1
	   IF(SPECT(N).GT.(YMAX-10.)) THEN
		MAXCOUNT = MAXCOUNT+LOWCOUNT+1
		LOWCOUNT = 0
	   ELSE
		LOWCOUNT = LOWCOUNT+1
	   ENDIF
	   IF(LOWCOUNT.GT.3) GO TO 420
	ENDDO
 420	CONTINUE
C	PRINT*,'DB,YMAX,YMIN',YMAX,YMIN
	BW = MAXCOUNT*SPSUSE/2048.
C	PRINT*,'MAXCOUNT, BANDWIDTH',MAXCOUNT,BW
	XN1 = N1-2
	XN2 = N2+2
	YRANGE = YMAX-YMIN
	YMAX = YMAX + .05*YRANGE
	YMIN = YMIN - .05*YRANGE
	YMIN = AMAX1(YMIN,YMAX-70.)
	CALL MGOSETLIM(-.017*XMAX,YMIN,XMAX,YMAX)
c	CALL MGOGRID(0)
C	CALL MGOSETLTYPE(1)
c	CALL MGOGRID(1)
	CALL MGOSETLTYPE(0)
	CALL MGOSETEXPAND(.6)
	CALL MGOCONNECT(PP,YY,NP)
C	CALL MGOPOINTS(60.,1,PP,YY,NP)
	CALL MGOSETEXPAND(.7)
	CALL MGOBOX(1,2)
	CALL MGOYLABEL(17,'POWER, DB V\u2/HZ')
	IF(TDS_CHANNEL.GT.2) CALL MGOXLABEL(9,'FREQ, HZ')
	IF(TDS_CHANNEL.LE.2) CALL MGOXLABEL(9,'FREQ, kHZ')
	YTITLE = GY2
	TRANGE = GY2-GY1
	TINC = .1*TRANGE
	YTITLE = YTITLE-TINC
	CALL MGOGRELOCATE(XTITLE,YTITLE)
C	CALL MGOLABEL(10,'   10 dB  ')
C	YTITLE = YTITLE-TINC
C	CALL MGOGRELOCATE(XTITLE,YTITLE)
C	CALL MGOLABEL(10,' BANDWIDTH')
C	YTITLE = YTITLE-TINC
C	CALL MGOGRELOCATE(XTITLE,YTITLE)
C	CALL MGOLABEL(10,'  OF PEAK ')
	IF(TDS_CHANNEL.GT.2) WRITE(STR,1021) .001*BW
	IF(TDS_CHANNEL.LE.2) WRITE(STR,1022) BW
 1021	FORMAT(F7.2,' HZ')
 1022	FORMAT(F6.3,' kHZ')
	YTITLE = YTITLE - TINC
	CALL MGOGRELOCATE(XTITLE,YTITLE)
C	CALL MGOLABEL(10,STR)
	CALL MGOSETEXPAND(1.)
C
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
	  READ(5,1023) DISPOSE
 1023	  FORMAT(A1)
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END	

