	PROGRAM SINCAL
C
C	FITS A SINE WAVE TO CALIBRATE TDS A/D CONVERTER
C
	CHARACTER*120 JUNK(10)
	CHARACTER*14 TITLE(10)
	COMMON /CALBLK/ VOLTS(2048),NDATA(2060)
	COMMON /HEADBL/ JUNK
	COMMON /FITBLK/ NPT,VOLTIN(2048),TM(2048)
	COMMON /ZBLK/ NZER,ZCROSS(128)
	COMMON /PLOTDT/ ITERM,TITLE
	COMMON /HNTBLK/ NHUNT(25)
	EXTERNAL FITDATA,FITZERO
	DIMENSION IZCROSS(4,128),IZCNTS(128)
	DIMENSION X(25),DX(25),Y(25)
C	DATA ITERM /3/
	DATA ITERM /-6/
	DATA TWOPI /6.2831853/
	DATA LOLIM /20/
C	INSERT, FREQ,AMPL,SPS,P/A,MODEL,CHANNEL,FILTER
C	DATA FREQ /1000./
	DATA FREQ /7./
C	DATA AMPL /4.0/				! AMPLITUDE IN V p-p
C	DATA AMPL /.4/				! AMPLITUDE IN V p-p
	DATA AMPL /.5/				! AMPLITUDE IN V p-p
C	DATA SPS /1875./			! SAMPLE RATE, PER SEC.
	DATA SPS /7500./			! SAMPLE RATE, PER SEC.
C
	TITLE(3) = 'P/A EXDC'
C	TITLE(1) = 'ENG. MODEL'
	TITLE(1) = 'FLIGHT MODEL'
C	TITLE(2) = 'TDS CH 3'
C	WRITE(TITLE(4),1004) SPS
 1004	FORMAT('SPS',F8.0)
	WRITE(TITLE(5),1005) FREQ
 1005	FORMAT(F5.0,' HZ')
	WRITE(TITLE(6),1006) AMPL
 1006	FORMAT(F5.2,' V P-P')
	TITLE(7) = 'FILTER 3.125 KHZ'
	TITLE(8) = 'SINCAL57.DAT'
	PRINT*,'LOLIM=',LOLIM
	PRINT*,' '
	PRINT*,TITLE(8)
C
	OPEN(UNIT=19,NAME=TITLE(8),TYPE='OLD',READONLY)
C	OPEN(UNIT=19,NAME='NOISE2.DAT',TYPE='OLD')
 1001	FORMAT(I4,1X,20I5)
 1002	FORMAT(A)
	DO IL = 1,6
	  READ(19,1002) JUNK(IL)
	  PRINT *,IL,JUNK(IL)
	ENDDO
C
	DO IL = 1,103
	  IK2 = 20*IL
	  IK1 = IK2-19
	  READ(19,1001,END=200) LINNO,(NDATA(IK),IK=IK1,IK2)
C	  PRINT*,'DATA',LINNO,NDATA(IK1),NDATA(IK2)
	ENDDO
200	CONTINUE
	DO IK = 1,2048
	  NDATA(IK) = NDATA(IK)-128
	ENDDO
C
C	CALCULATE NOMINAL WAVE PERIOD IN SAMPLES
C
	WPER = SPS/FREQ
	PRINT*,'WPER',WPER
C
C	FIND FIRST ZERO CROSSING
C
	DO IL = 1,2047
	  IZ = IL
	  IF(NDATA(IL).EQ.0) PRINT*,'ZERO DATA',IL,NDATA(IL-1),
     1   NDATA(IL),NDATA(IL+1)
	  IF(NDATA(IL)*NDATA(IL+1).LE.0) GO TO 20
	ENDDO
 20	CONTINUE
C	PRINT*,'FIRST ZERO CROSSING AT IZ=',IZ
C
C
C	  CALCULATE ZERO CROSSINGS IN GROUPS FOR UP TO 4 GROUPS
C
	  IZCROSS(1,1) = IZ
	  IZCNT = 1
	  IL1 = IZ+1
	  IL2 = IL1 + WPER/8.
	  IL2 = MIN0(IL2,2047)
	  DO IGP = 1,4
 	    DO IL = IL1,IL2
	      IF(NDATA(IL)*NDATA(IL+1).LE.0) THEN
	        IZCNT = MIN0(IZCNT+1,128)
	        IZCROSS(IGP,IZCNT) = IL
	      ENDIF
	    ENDDO
	    IL1 = IZCROSS(IGP,1) + 3.*WPER/8.
	    IL2 = IL1 + WPER/4.
	    IL2 = MIN0(IL2,2047)
	    IZCNTS(IGP) = IZCNT
	    IZCNT = 0
  	  ENDDO
C
C	  CALCULATE AVERAGES FOR MULTIPLE ZERO CROSSINGS
C
	  DO IGP = 1,4
	    IZCNT = IZCNTS(IGP)
	    PRINT*,'ZEROS',IGP,(IZCROSS(IGP,I),I=1,IZCNT)
	    ZCROSS(IGP) = 0.
	    DO I = 1,IZCNT
	      ZCROSS(IGP) = ZCROSS(IGP) + IZCROSS(IGP,I)
	    ENDDO
	    ZCROSS(IGP) = ZCROSS(IGP)/IZCNT + .5
	  ENDDO
	  PRINT*,'Z CROSSINGS',(ZCROSS(J),J=1,4)
	  WPER1 = .5*(ZCROSS(3) - ZCROSS(1) + ZCROSS(4) - ZCROSS(2))
	  PRINT*,'NEW WPER',WPER1
	  PHI0 = .25*(ZCROSS(1)+ZCROSS(2)+ZCROSS(3)+ZCROSS(4)-2.*WPER1)
	  PRINT*,'PHI0',PHI0
	  NPHI0 = PHI0 + .5
C
C	IF FREQUENCY IS HIGH, THERE WILL BE A LOT OF ZERO CROSSINGS AND
C	ALL WILL BE SINGLE, SO FIND SOME MORE
C
	IF(WPER.LT.820.) THEN
	    PRINT*,'FIND SOME MORE ZEROS'
	  DO JT = 1,127
	    IL1 = ZCROSS(IZCNT) + 3.*WPER/8.
	    IL2 = IL1 + WPER/4.
	    IL2 = MIN0(IL2,2047)
	    IF(IL1.GT.2047) GO TO 25
C	    PRINT*,'IL1,IL2',IL1,IL2
 	      DO IL = IL1,IL2
	        IF(NDATA(IL)*NDATA(IL+1).LE.0) THEN
		  IZCNT = IZCNT+1
	          ZCROSS(IZCNT) = IL+.5
	          IL1 = IL
		  GO TO 22
	        ENDIF
	      ENDDO
 22	      CONTINUE
  	  ENDDO
C
 25	  CONTINUE
C
	  PRINT*,IZCNT,' ZEROS FOUND'
	  PRINT*,(ZCROSS(J),J=1,IZCNT)
	  PRINT*,'INTERVALS'
	  PRINT*,((ZCROSS(J+1)-ZCROSS(J)),J=1,IZCNT-1)
	  WPER1 = 2.*(ZCROSS(IZCNT)-ZCROSS(1))/(IZCNT-1)
	  PRINT*,'NEW WPER',WPER1
	  X(1) = ZCROSS(1)
	  X(2) = 2./WPER1
	  DX(1) = .5
	  DX(2) = .05*X(2)
	  CALL HUNTMN(2,X,DX,Y,FITZERO,SUMSQ)
	  WPER1 = 2./X(2)
	  PHI0 = X(1) + .25*WPER1	
	  PRINT*,'NEW WPER,PHI0=',WPER1,PHI0
	  NPHI0 = PHI0 + .5
C
C	  END OF FURTHER ZERO CROSSINGS FOR HIGH FREQUENCIES
C
	ENDIF
C
C
C	ALLOW FOR POSSIBILITY OF NEGATIVE PEAK
C
 	AMPT = AMPL
	IF(NDATA(NPHI0).LT.0) AMPT = -AMPL
	DO J = 1,2048
	  PHI = (J-PHI0)*TWOPI/WPER1
	  VOLTS(J) = .5*AMPT*COS(PHI)
	ENDDO
	WRITE(27,1003) (J,VOLTS(J), NDATA(J),J=1,2048)
 1003	FORMAT(3(I9,E11.3,I5))
C
C	NOW A SINE WAVE HAS BEEN FITTED THROUGH THE ZERO CROSSINGS AND
C	THE KNOWN AMPLITUDE, SO VOLTAGE INPUT FOR EACH DATA POINT HAS
C	BEEN CALCULATED
C
C	FIT UPPER PART OF CALIBRATION CURVE, WITH ZERO OFFSET
C
	NPT = 0
	DO J = 1,2048
	  IF(IABS(NDATA(J)).GT.71.AND.NDATA(J).GT.LOLIM) THEN
	    NPT = NPT+1
	    VOLTIN(NPT) = ABS(VOLTS(J))
	    TM(NPT) = NDATA(J)
	  ENDIF
	ENDDO
C
	NHUNT(2) = 0
C	X(1) =20./.7238
	X(1) = 31.
	X(2) = 0.
	X(3) = 2.8E-3
	X(3) = X(1)*ALOG10(X(3))
C
	DX(1) = .05*X(1)
	DX(2) = 5.E-3
	DX(3) = .1*X(3)
	IF(NPT.LE.3) GO TO 30
	CALL FITDATA(X,SUMSQS)
	PRINT*,' '
	PRINT*,' '
	PRINT*,' FIRST TRY AT HIGH FIT, +DATA,',NPT,'  POINTS, SUMSQ='
     1  ,SUMSQS
	DO IT = 1,20
	  CALL HUNTMN(3,X,DX,Y,FITDATA,SUMSQ)
	  PRINT*,'HUNTMN OUTPUT',X(1),X(2),X(3),SUMSQ
	  IF(SUMSQ.GT..9995*SUMSQS) GO TO 30
	  SUMSQS = SUMSQ
	ENDDO
	PRINT*,'NOT ENOUGH ITERATIONS, POOR HIGH FIT'
 30	CONTINUE
	VZERO = 10.**(X(3)/X(1))
	IF(NPT.GT.3) THEN
	  RMS = SQRT(SUMSQ/(NPT-2))
	  PRINT*,' VZERO = OLD X(3) =',VZERO,'  RMS ERR',RMS,'  TM UNITS'
	  DO IT = 1,5
	    IF(DX(3).EQ.0.) DX(3) = 1.E-5
	    CALL FINMIN(3,X,DX,Y,FITDATA,SUMSQF)
	    CALL FINMIN(3,Y,DX,X,FITDATA,SUMSQF)
	    PRINT*,' FINMIN GIVES',(X(N),N=1,3),SUMSQF
	  ENDDO
	  V71 = 10.**((71.+X(3))/X(1)) - X(2)
	  PRINT*,'VOLTS TO GIVE TM = 71', V71
	ELSE
	  PRINT*,'NOT ENOUGH DATA FOR HIGH, +DATA FIT'
	ENDIF
C
	NPT = 0
	DO J = 1,2048
	  IF(IABS(NDATA(J)).GT.71.AND.NDATA(J).LT.-LOLIM) THEN
	    NPT = NPT+1
	    VOLTIN(NPT) = ABS(VOLTS(J))
	    TM(NPT) = -NDATA(J)
	  ENDIF
	ENDDO
C
	NHUNT(2) = 0
	X(2) = 0.
C
	DX(1) = .05*X(1)
	DX(2) = 5.E-3
	DX(3) = .1*X(3)
	IF(NPT.LE.3) GO TO 35
	CALL FITDATA(X,SUMSQS)
	PRINT*,' '
	PRINT*,' '
	PRINT*,'/FIRST TRY AT HIGH FIT, -DATA,',NPT,'  POINTS, SUMSQ='
     1  ,SUMSQS
	DO IT = 1,20
	  CALL HUNTMN(3,X,DX,Y,FITDATA,SUMSQ)
	  PRINT*,'HUNTMN OUTPUT',X(1),X(2),X(3),SUMSQ
	  IF(SUMSQ.GT..9995*SUMSQS) GO TO 35
	  SUMSQS = SUMSQ
	ENDDO
	PRINT*,'NOT ENOUGH ITERATIONS, POOR HIGH FIT'
 35	CONTINUE
	VZERO = 10.**(X(3)/X(1))
	IF(NPT.GT.3) THEN
	  RMS = SQRT(SUMSQ/(NPT-2))
	  PRINT*,' VZERO = OLD X(3) =',VZERO,'  RMS ERR',RMS,'  TM UNITS'
	  DO IT = 1,5
	    IF(DX(3).EQ.0.) DX(3) = 1.E-5
	    CALL FINMIN(3,X,DX,Y,FITDATA,SUMSQF)
	    CALL FINMIN(3,Y,DX,X,FITDATA,SUMSQF)
	    PRINT*,' FINMIN GIVES',(X(N),N=1,3),SUMSQF
	  ENDDO
	  V71 = 10.**((71.+X(3))/X(1)) - X(2)
	  PRINT*,'VOLTS TO GIVE TM = 71', V71
	ELSE
	  PRINT*,'NOT ENOUGH DATA FOR HIGH, -DATA FIT'
	ENDIF
C
C
C	FIT LOWER PART OF CALIBRATION CURVE, WITH NONZERO OFFSET
C
	NPT = 0
	DO J = 1,2048
	  IF(IABS(NDATA(J)).LE.71.AND.NDATA(J).GT.LOLIM) THEN
	    NPT = NPT+1
	    VOLTIN(NPT) = ABS(VOLTS(J))
	    TM(NPT) = NDATA(J)
	  ENDIF
	ENDDO
	NHUNT(2) = 1
	X(2) = 2.3E-2
	DX(1) = .05*X(1)
	DX(2) = .1*X(2)
	DX(3) = 1.E-5
	CALL FITDATA(X,SUMSQS)
	PRINT*,' '
	PRINT*,' '
	PRINT*,' FIRST TRY AT FULL FIT, +DATA,',NPT,'  POINTS, SUMSQ='
     1  ,SUMSQS
	DO IT = 1,20
	  CALL HUNTMN(3,X,DX,Y,FITDATA,SUMSQ)
	  PRINT*,'HUNTMN OUTPUT',X(1),X(2),X(3),SUMSQ
	  IF(SUMSQ.GT..9995*SUMSQS) GO TO 40
	  SUMSQS = SUMSQ
	ENDDO
	PRINT*,'NOT ENOUGH ITERATIONS, POOR FULL FIT'
 40	CONTINUE
	VZERO = 10.**(X(3)/X(1))
	IF(NPT.GE.4) RMS = SQRT(SUMSQ/(NPT-3))
	PRINT*,' VZERO = OLD X(3) =',VZERO,'  RMS ERR',RMS,'  TM UNITS'
	PRINT*,'HUNTMN OUTPUT',X(1),X(2),X(3),SUMSQ
	SUMSQS = SUMSQ
	  DO IT = 1,10
	    CALL FINMIN(3,X,DX,Y,FITDATA,SUMSQF)
	    CALL FINMIN(3,Y,DX,X,FITDATA,SUMSQF)
	    PRINT*,' FINMIN GIVES',(X(N),N=1,3),SUMSQF
	    IF(SUMSQF.GT..9999*SUMSQS) GO TO 47
	    SUMSQS = SUMSQF
	  ENDDO
  47	  V71 = 10.**((71.+X(3))/X(1)) - X(2)
	  PRINT*,' '
	  PRINT*,' FINMIN GIVES',(X(N),N=1,3),SUMSQF
	  PRINT*,'VOLTS TO GIVE TM = 71', V71
C
	NPT = 0
	DO J = 1,2048
	  IF(IABS(NDATA(J)).LE.71.AND.NDATA(J).LT.-LOLIM) THEN
	    NPT = NPT+1
	    VOLTIN(NPT) = ABS(VOLTS(J))
	    TM(NPT) = -NDATA(J)
	  ENDIF
	ENDDO
	NHUNT(2) = 1
	DX(1) = .05*X(1)
	DX(2) = .1*X(2)
	DX(3) = 1.E-5
	CALL FITDATA(X,SUMSQS)
	PRINT*,' '
	PRINT*,' '
	PRINT*,' FIRST TRY AT FULL FIT, -DATA,',NPT,'  POINTS, SUMSQ='
     1  ,SUMSQS
	DO IT = 1,20
	  CALL HUNTMN(3,X,DX,Y,FITDATA,SUMSQ)
	  PRINT*,'HUNTMN OUTPUT',X(1),X(2),X(3),SUMSQ
	  IF(SUMSQ.GT..9995*SUMSQS) GO TO 45
	  SUMSQS = SUMSQ
	ENDDO
	PRINT*,'NOT ENOUGH ITERATIONS, POOR FULL FIT'
 45	CONTINUE
	VZERO = 10.**(X(3)/X(1))
	IF(NPT.GE.4) RMS = SQRT(SUMSQ/(NPT-3))
	PRINT*,' VZERO = OLD X(3) =',VZERO,'  RMS ERR',RMS,'  TM UNITS'
	PRINT*,'HUNTMN OUTPUT',X(1),X(2),X(3),SUMSQ
	SUMSQS = SUMSQ
	  DO IT = 1,10
	    CALL FINMIN(3,X,DX,Y,FITDATA,SUMSQF)
	    CALL FINMIN(3,Y,DX,X,FITDATA,SUMSQF)
	    PRINT*,' FINMIN GIVES',(X(N),N=1,3),SUMSQF
	    IF(SUMSQF.GT..9999*SUMSQS) GO TO 48
	    SUMSQS = SUMSQF
	  ENDDO
  48	  PRINT*,' '
	  PRINT*,' FINMIN GIVES',(X(N),N=1,3),SUMSQF
	  V71 = 10.**((71.+X(3))/X(1)) - X(2)
	  PRINT*,'VOLTS TO GIVE TM = 71', V71
	  PRINT*,' '
	CALL CALPLOT
	STOP
	END
	SUBROUTINE CALPLOT
C
	CHARACTER*14 TITLE(10)
	CHARACTER*120 JUNK(10)
	CHARACTER*120 STR
	COMMON /HEADBL/ JUNK
	COMMON /CALBLK/ VOLTS(2048),NDATA(2060)
	COMMON /PLOTDT/ ITERM,TITLE
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
	DIMENSION YY(500),PP(500)
C
	  CALL MGOINIT
	  CALL MGOSETUP(ITERM)
	  CALL MGOERASE
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(400.,330.,3000.,2300.)
	ENDIF
C
C	  WRITE(STR,703) NYR,NDOY,NHRMIN,NFCLKS
C 703	  FORMAT('\\t',I5,' DAY',I4,1X,I4.4,'  S/C CLK=',I12)
	  CALL MGOSETEXPAND(.85)
	  IF(ITERM.GT.0) THEN
	    CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
	  ELSE
	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
	  ENDIF
C	  CALL MGOPUTLABEL(53,STR,9)
c	  WRITE(STR,704) SAA()
c 704	  FORMAT('\\tSOLAR ASPECT',F6.1,' DEG.')
c	  CALL MGOPUTLABEL(55,STR,9)
	  CALL MGOSETEXPAND(1.)
C
	CALL MGOTICKSIZE(-1.,0.,2.,10.)  
	YLOLIM = -9.
	CALL MGOSETLIM(-5.,YLOLIM-1.,1.,130.)
	CALL MGOGRID(0)
	CALL MGOSETLTYPE(1)
	CALL MGOGRID(1)
	CALL MGOSETLTYPE(0)
	CALL MGOSETEXPAND(.6)
	  DO I = 1,2048
	    IF(VOLTS(I).GT.0.) THEN
	      VOLTL = ALOG10(VOLTS(I))
	      DATPL = NDATA(I)
	      CALL MGORELOCATE(VOLTL,DATPL)
	      CALL MGOSETANGLE(45.)
	      CALL MGOPOINT(4,1)
	      CALL MGOSETANGLE(0.)
	    ELSE
	      VOLTL = ALOG10(-VOLTS(I))
	      DATPL = -NDATA(I)
	      DATPL = AMAX1(DATPL,YLOLIM)
	      CALL MGORELOCATE(VOLTL,DATPL)
	      CALL MGOPOINT(4,1)
	    ENDIF
	  ENDDO
	CALL MGOSETEXPAND(1.)
	  CALL MGOBOX(1,2)
C	  WRITE(STR,704) JHP,PFRFREQ(JHP+1)
C 704	  FORMAT('\\tFREQ',I3,F6.2,'\\t kHz')
	CALL MGOSETEXPAND(.8)
	  CALL MGOXLABEL(5,'VOLTS')
	  CALL MGOYLABEL(10,'T/M NUMBER')
	  CALL MGOSETEXPAND(.55)
	  CALL MGORELOCATE(-4.9,129.)
	  CALL MGOLABEL(120,JUNK(2))
	  CALL MGORELOCATE(-4.9,119.)
	  CALL MGOLABEL(120,JUNK(1))
C	  CALL MGORELOCATE(-4.5,113.)
C	  CALL MGOLABEL(12,TITLE(2))
C	  CALL MGORELOCATE(-4.5,107.)
C	  CALL MGOLABEL(10,TITLE(3))
	  CALL MGORELOCATE(-4.5,101.)
	  CALL MGOLABEL(10,TITLE(4))
	  CALL MGORELOCATE(-4.5,95.)
	  CALL MGOLABEL(10,TITLE(5))
	  CALL MGORELOCATE(-4.5, 89.)
	  CALL MGOLABEL(12,TITLE(6))
	  CALL MGORELOCATE(-4.5, 81.)
	  CALL MGOLABEL(14,TITLE(7))
	  CALL MGORELOCATE(-4.6, 75.)
	  CALL MGOLABEL(12,'INPUT POS. ')
	  CALL MGOSETANGLE(45.)
	  CALL MGOPOINT(4,1)
	  CALL MGOSETANGLE(0.)
	  CALL MGORELOCATE(-4.6, 71.)
	  CALL MGOLABEL(12,'INPUT NEG. ')
	  CALL MGOPOINT(4,1)
	CALL MGOSETEXPAND(1.)
C
C
	CALL MGOSETEXPAND(.8)
	CALL MGOPLOTID(TITLE(8),'SINCAL')
	CALL MGOSETEXPAND(1.)
	IF(ITERM.LT.0) THEN
C	  CALL MGOTIDLE
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	  NPLOTS = NPLOTS + 1
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	RETURN
C
	END
	SUBROUTINE FITDATA(X,SUMSQ)
C
C	FITS T/M NO. = X(1)*ALOG10( VOLTS + VOFFS)/X(3))
C		WITH VOFFS = X(2)
C
	COMMON /FITBLK/ NPT,VOLTS(2048),TM(2048)
	DIMENSION X(25),WT(2048)
	DATA WT /2048*1./
C
	SUMSQ = 0.
c	X(3) = AMAX1(X(3),1.E-6)
C	X(2) = AMAX1(X(2),0.)
	DO N = 1,NPT
	  TMA = ABS(TM(N))
	  VT = ABS(VOLTS(N))
	  IF((VT+X(2)).GT.0.) THEN
C	    SUMSQ = SUMSQ + WT(N)*(TMA - X(1)*ALOG10((VT + X(2))/X(3)))**2
	    SUMSQ = SUMSQ + WT(N)*(TMA - X(1)*ALOG10(VT + X(2)) + X(3))**2
	  ELSE
	    SUMSQ = SUMSQ*(1.+2./NPT)
	  ENDIF
	ENDDO
	RETURN
	END
	SUBROUTINE FITZERO(X,SUMSQ)
C
	COMMON /ZBLK/ NPT,ZCROSS(128)
	DIMENSION X(25),WT(2048)
	DATA WT /2048*1./
C
	SUMSQ = 0.
	DO N = 1,NPT
	  SUMSQ = SUMSQ + (ZCROSS(N) - X(1) - X(2)*(N-1))**2
	ENDDO
	RETURN
	END
