	SUBROUTINE TDS_PHYSBZ(CH,LSAMP,NDATA,VDATA,SPECT)
C
C	THIS IS A SPECIAL VERSION WITH COMMANDABLE FILTERING, FOR TDSS
C		MAGNETIC DATA, AND WHICH DOES ONLY PART OF AN EVENT,
C		ELIMINATING THE BZ GLITCH
C
	integer*4	ok,ch
	integer*4	i,j,k,n
	integer*4	w_item_i4
	character*4	pa(6,4)
	integer*4	return_size,SUNCLOCK
	integer*4	tds_channel,ifilf,ifils,ifil,ifsps,issps,isps
	character*32	item
	real 		ffilter(4),sfilter(4),fsps(4),ssps(4),sps
	REAL 		DATA(2050),VDATA(1),SPECT(1025)
	REAL		ZCROSS(2048),ZINT(2048)
	REAL		ANG(2048),ANGTBL(380)
        INTEGER*4       NDATA(2048),NFDATA(2048),NBGDATA(380)
!
C
	COMPLEX PREAMP,TDSDET,TDS_FILTER
	COMPLEX FCOEF,FCOEFT,CCORR
	COMMON /TDS_STATUS/ TDS_CHANNEL,IFIL,FILTER,IRX,ISPS,SPS
	COMMON /PUB/ HDATA(4100)
	COMMON /XFER/ SPHASE(1025)
	COMMON /BZGL/ IGL,NGL1,NGL2
	COMMON /FRLIMITS/ FREQMIN,TOPFREQ
	DATA IBGDATA /0/
	DATA TWOPI /6.2831853/
c	DATA FFILTER /50000.,12500.,3125.,781./
c	DATA SFILTER /3125.,781.,195.,49./
c	DATA FSPS /120.,30.,7.5,1.875/
c	DATA SSPS /7500.,1875.,468.75,117.2/
c	DATA PA /'EXAC','EXAC','EXDC',' BX ',' BY ',' BZ ',
c     1           'EXDC','EYAC','EYDC','EXDC','EYDC','EZDC',
c     2           '    ','EZAC','EZDC','    ','    ','    ',
c     3           '    ','EZAC','EZDC','    ','    ','    '/
C
c	item = 'CHANNEL'
c	ok = W_ITEM_i4(ch, item, tds_channel, 1, return_size)
	item = 'EVENT_NUMBER'
	ok = W_ITEM_i4(ch, item, itemp, 1, return_size)
C
	FUNDFR = SPS/LSAMP
	NFREQ = LSAMP/2
C
	  DO N = 1,LSAMP
		NFDATA(N) = NDATA(N)
	  ENDDO
c	ENDIF
C
	DO IK = 1,LSAMP
	    DATA(IK) = TDSCAL(TDS_CHANNEL,ISPS,NFDATA(IK))
	    VDATA(IK) = DATA(IK)
	ENDDO
C
		CALL FIXBADTDS(IFXB,NFDATA,DATA,TDS_CHANNEL,SPS,ISPS)
C
C		REALFT IS FROM NUMERICAL RECIPES, CAMBRIDGE U PRESS
C
C	CORRECT FOURIER ANALYSED SIGNAL FOR FREQUENCY RESPONSE AT ALL
C		FREQUENCIES (IPRC = 4)
C
	CALL REALFT(DATA,NFREQ,1)
C
	     FREQMAX = .5*SPS
	     PAMAX = CABS(PREAMP(IRX,FREQMAX))
	     IF(IRX.GT.6) PAMAX = CABS(PREAMP(IRX,2000.))      !SEARCH COIL
	     IF(TDS_CHANNEL.LE.2) THEN
		IF(IRX.EQ.1) PAMAX = 2.4  		       ! EXAC
		IF(TDS_CHANNEL.EQ.2.AND.IRX.EQ.2) PAMAX = 6.6  ! EYAC
		IF(TDS_CHANNEL.EQ.2.AND.IRX.GT.2) PAMAX = 7.   ! EZAC
	     ENDIF
	     DO IK = 3,LSAMP,2
		FCOEF = CMPLX(DATA(IK),DATA(IK+1))
	        FREQ = SPS*(IK-1)/4096.
	        CCORR = PREAMP(IRX,FREQ)*TDSDET(TDS_CHANNEL,FREQ)
		CCORR = CCORR*TDS_FILTER(TDS_CHANNEL,IFIL+1,FREQ)
		FCOEF = FCOEF/CONJG(CCORR)
		DATA(IK) = FCOEF
		DATA(IK+1) = AIMAG(FCOEF)
	     ENDDO
C
C	NOW DATA CONTAINS FOURIER COEFFS CORRECTED FOR FREQUENCY RESPONSE
C
 100	CONTINUE
C
C	CALCULATE SPECTRUM, IN DB WRT 1 V**2/HZ
C
	SNORM = 20.*ALOG10(FLOAT(NFREQ)) + 10.*ALOG10(FUNDFR)
	IK = 1
	ISP = 1
	SPECT(ISP) = -SNORM
	IF(DATA(IK).NE.0.)SPECT(ISP) = 20.*ALOG10(ABS(DATA(IK)))-SNORM
	DO IK = 3,LSAMP,2
	    ISP = ISP+1
	    TPWR = DATA(IK)**2 + DATA(IK+1)**2
	    SPECT(ISP) = -50.
	    IF(TPWR.NE.0.) THEN
	      SPECT(ISP) = 10.*ALOG10(TPWR)-SNORM
	      SPHASE(ISP) = 57.296*ATAN2(DATA(IK+1),DATA(IK))
	    ENDIF
	ENDDO
C
C		CHANNELS 1 AND 2 HAVE TDSDET AT 322 HZ, AND POOR
C		PREAMP RESPONSE BELOW 120. HZ, SO CUT OFF AT 150 HZ.
C
C		SEARCH COILS SEEM TO BE ENTIRELY NOISE BELOW 3.2 HZ
C
	     DO IK = 3,LSAMP,2
	        FREQ = SPS*(IK-1)/4096.
		IF(FREQ.LT.FREQMIN.OR.FREQ.GT.TOPFREQ) THEN
		  DATA(IK) = 0.
		  DATA(IK+1) = 0.
		ENDIF
	     ENDDO
C
	     CALL REALFT(DATA,NFREQ,-1)
	     DO IK = 1,LSAMP
	       DATA(IK) = DATA(IK)/NFREQ
	       VDATA(IK) = DATA(IK)
	     ENDDO
C
 20	CONTINUE
C
	RETURN
	END

