	FUNCTION TDSDET(CHANNEL,F)
C
C	THIS IS THE GAIN OF A CIRCUIT JUST BEFORE THE TDS DETECTOR
C
	INTEGER*4 CHANNEL
	COMPLEX Z1,Y2,GAIN
	COMMON /GAINBLK/ PHASE,GAIN
	DATA R1,C1,R2,C2 /1.505E3,.33E-6,1.E5,.33E-6/
	DATA TWOPI /6.2831853/
C
	W = TWOPI*F
	IF(CHANNEL.GT.2) THEN
	  Z1 = CMPLX(R2,-1./W/C2)
	  GAIN = R2/Z1
	ELSE
	  Z1 = CMPLX(R1,-1./W/C1)
	  GAIN = R1/Z1
	ENDIF
C
	GNIP = AIMAG(GAIN)
	GNRP = GAIN
	PHASE = ATAN2(GNIP,GNRP)
	FFTAMP = CABS(GAIN)
	RETURN
	END

