Return-Path: kellogg@megasx.obspm.fr
Received: by waves.space.umn.edu (UCX V4.1-12, OpenVMS V6.2-1H3 Alpha);
	Thu, 13 Aug 1998 13:13:22 -0500
Date: Thu, 13 Aug 1998 20:10:15 +0200
Message-Id: <98081320101488@megasx.obspm.fr>
From: kellogg@megasx.obspm.fr
To: KELLOGG@waves.space.umn.edu
X-VMS-To: SMTP%kellogg@waves.space.umn.edu
X-VMS-Cc: KELLOGG

	PROGRAM TDSVOLTS
C
	COMPLEX PREAMP,TDSDET,CCORR,TDS_FILTER
	INTEGER*4 TDS_CHANNEL
	DATA IFIL /0/
C	
	include		'wind_examples:wind_tm_routine_def.for'
	include		'wind_examples:wind_return_code_def.for'
C
	TYPE*,'FOR TDS FAST'
	TYPE*,'    SAMPLE RATE = 0 IS 120,000 SAMPLES/SEC'
	TYPE*,'FOR TDS SLOW'
	TYPE*,'    SAMPLE RATE = 0 IS 7500 SAMPLES/SEC'
 100	CONTINUE
	TYPE*,'TYPE FREQ(kHz), CHANNEL,SAMPLE RATE, DATA (-128 TO 128)'
	READ(5,*) FREQ,TDS_CHANNEL,ISPS,NFDATA
	  FREQMAX = 1000.*FREQ
	  TYPE*,FREQMAX,TDS_CHANNEL,ISPS,NFDATA
	  DATA = TDSCAL(TDS_CHANNEL,ISPS,NFDATA+128)
	  IRX = 1
C*****	  note that receiver is not done right
	  IF(TDS_CHANNEL.EQ.1) IRX = 1
	  IF(TDS_CHANNEL.EQ.2) IRX = 2
	  CCORR = PREAMP(IRX,FREQMAX)*TDSDET(TDS_CHANNEL,FREQMAX)
	  CCORR = CCORR*TDS_FILTER(TDS_CHANNEL,IFIL+1,FREQMAX)
	  RCORR = 1./CABS(CCORR)
C	  CJCORR = CONJG(CCORR)
	  VOLTS = DATA*RCORR
	TYPE*,'NFDATA,VOLTS',NFDATA,VOLTS
	GO TO 100
 200	STOP
	END
	SUBROUTINE FIXBADTDS(IFXB,NFDATA,DATA,TDS_CHANNEL,SPS,ISPS)
C	DUMMY
	RETURN
	END
