	SUBROUTINE VMATRIX(DATA,IEB,WT,NPT)
C
C	CALCULATES VARIANCE MATRIX AND EIGENVALUES
C
C	COMMON /PARTBLK/ XDATA(2050,4),XFDATA(2050,4),XGSE(2050,4),
C     1		XRE,YRE,ZRE,SUNCLOCK,SPINRATE,SPSS
	COMMON /VARMATX/ EVAL(3),EVECT(3,3)
	REAL DATA(2050,4),DATAS(2050,3),VMAT(3,3),WT(2050)
	REAL SN(3),CL(3),V3(3),AV(3),STD(3),EFFLENE(3),EFFLEN(3)
	INTEGER*4 SUNCLOCK
	DATA NSYS /-1/
	DATA EFFLENE /41.1, 3.79, 2.17/
C
C	THIS PROGRAM EXCLUDES GLITCH DATA BY USING WT
C	Change on 24 Aug 2007 to use E instead of volts at input 
C
	IF(IEB.EQ.0) THEN
	  DO N = 1,3
	    EFFLEN(N) = EFFLENE(N)
	  ENDDO
	ELSE
	  DO N = 1,3
	    EFFLEN(N) = 1.
	  ENDDO
	ENDIF
C	subtract averages
C
C	WRITE(79,*) ' '	
C	WRITE(79,*) 'VARIANCE MATRIX,NPT=',NPT	
C
	DO M = 1,3
	  AV(M) = 0.
	  COUNT = 0.
	  DO N = 1,NPT
		AV(M) = AV(M) + WT(N)*DATA(N,M)
		COUNT = COUNT+WT(N)
	  ENDDO
C	PRINT*,'M,AV,COUNT',M,AV(M),COUNT
	  AV(M) = AV(M)/COUNT
	ENDDO
	DO M = 1,3	
	  DO N = 1,NPT
		DATAS(N,M) = WT(N)*(DATA(N,M) - AV(M))
	  ENDDO
	ENDDO
C
C	PRINT*,' WITH AVERAGES REMOVED'
C
C	FORM VARIANCE MATRIX
C	
	DO K = 1,3
	  DO M = 1,3
		VMAT(K,M) = 0.
	  ENDDO
	ENDDO
C	
	DO N = 1,NPT
	  DO K = 1,3
	    DO M = K,3
		VMAT(K,M) = VMAT(K,M) + 
     1		DATAS(N,K)*DATAS(N,M)/EFFLEN(K)/EFFLEN(M)
	    ENDDO
	  ENDDO
	ENDDO	
c	print*,'diag elems',vmat(1,1),vmat(2,2),vmat(3,3),
c     1	' trace',vmat(1,1)+vmat(2,2)+vmat(3,3)
C
C	CALCULATE EIGENVALUES AND MATRIX OF EIGENVECTORS
C
	CALL JACOBI(VMAT,3,3,EVAL,EVECT,NROT)
C	PRINT*,'EIGENVALUES',EVAL
C	PRINT*,'EIGENVECTOR'
C	PRINT*,(EVECT(1,I),I=1,3)
C	PRINT*,(EVECT(2,I),I=1,3)
C	PRINT*,(EVECT(3,I),I=1,3)
C
C	SORT IN DESCENDING ORDER OF EIGENVALUES
C
	CALL EIGSRT(EVAL,EVECT,3,3)
C
C
C 	ENFORCE A RIGHT HANDED SYSTEM BY REVERSING THE SMALLEST
C	EIGENVECTOR IF NECESSARY
C
	ADOTBXC = EVECT(1,1)*EVECT(2,2)*EVECT(3,3)
     1	 - EVECT(1,1)*EVECT(3,2)*EVECT(2,3)
     1	 + EVECT(2,1)*EVECT(1,3)*EVECT(3,2)
     1	 - EVECT(2,1)*EVECT(1,2)*EVECT(3,3)
     1	 + EVECT(3,1)*EVECT(1,2)*EVECT(2,3)
     1	 - EVECT(3,1)*EVECT(2,2)*EVECT(1,3)
C	PRINT*,'DETERMINANT OF EIGENVECTORS',ADOTBXC
	IF(ADOTBXC.LT.0.) THEN        ! REVERSE SMALLEST EVECT FOR RH SYSTEM
	  EVECT(1,3) = -EVECT(1,3)
	  EVECT(2,3) = -EVECT(2,3)
	  EVECT(3,3) = -EVECT(3,3)
C	  PRINT*,'CHANGE TO RIGHT HANDED SYSTEM'
	ENDIF
C
C	PRINT*,'IN SYSTEM',NSYS,'  EIGENVALUES:'
C	PRINT*,EVAL,'eig sum',eval(1)+eval(2)+eval(3)
C	PRINT*,'EIGENVECTORS'
C	PRINT*,(EVECT(1,I),I=1,3)
C	PRINT*,(EVECT(2,I),I=1,3)
C	PRINT*,(EVECT(3,I),I=1,3)
C	WRITE(79,*) 'IN SYSTEM',NSYS,'  EIGENVALUES:'
C	WRITE(79,*)  EVAL
C	WRITE(79,*) 'EIGENVECTORS IN COLUMNS BELOW EIGENVALUES'
C	WRITE(79,*)(EVECT(1,I),I=1,3)
C	WRITE(79,*)(EVECT(2,I),I=1,3)
C	WRITE(79,*)(EVECT(3,I),I=1,3)
	NSYS = 2
	RETURN
	END	
