	PROGRAM WAVES_DIRECTIONS
C
C	MAKES A PLOT OF WAVE DIRECTIONS OBTAINED FROM FIT_WAVE AND
C		TDSEXEY
C
	CHARACTER*120 	JUNK
	REAL		ANGMAG(60),SUNCLOCK(60)
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
C	THE 12 CONSEQUTIVE 1997 nOV 4 EVENTS:
	DATA SUNCLOCK /0., 185.,98.,2042.,2485.,1452.,71.,2435.,3231.,
     1		797.,4005.,2789.,3626.,926.,190.,3*0.,1942.,
     1          2*0.,1030.,8*0.,17*0.,
     1		4*1452.,4*98.,5*0./
	DATA ANGMAG /0., 108.,108.,108.,108.,102.,102.,105.,110.,
     1		110.,110.,111.,121.6,111.5,109.1,3*0.,-20.0,
     2          2*0.,-17.8,8*0.,17*0.,
     2  	4*102.,4*108.,5*0./
C	DATA ITERM /3/
	DATA ITERM /-2/
C
	NDO = 22
	NDO = 64
c      DO NDO = 13,14
C
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
C
      DO ISUBR = 1,2
	IF(ISUBR.EQ.1) THEN
	  IF(ITERM.LT.0) THEN
	    CALL MGOSETLOC(500., 750., 1700., 1950.)
	  ELSE
	    CALL MGOSETLOC(200.,870.,80.,750.)
	  ENDIF
	ELSE
	  IF(ITERM.LT.0) THEN
	    CALL MGOSETLOC(1900., 750., 3100., 1950.)
	  ELSE
	    CALL MGOSETLOC(200.,870.,80.,750.)
	  ENDIF
	ENDIF
C
	  IF(ISUBR.EQ.1) THEN
	    NDO = 64
	    OPEN(UNIT=44,FILE='FITWAVE.RESULTS',STATUS='OLD',READONLY)
	    READ(44,22) JUNK
	    READ(44,22) JUNK
	  ELSE
	    NDO = 17
	    OPEN(UNIT=45,FILE='FITWAVE12.RESULTS',STATUS='OLD',READONLY)
	    READ(45,22) JUNK
	    READ(45,22) JUNK
	  ENDIF
C
C	ISUBR = 1		! 1 IS 8 VARIABLE FIT, LONGITUDINAL WAVES
C				  2 IS 12 VARIABLE FIT, WITH CIRCULAR POL.
 22	FORMAT(A)
	IF(ISUBR.EQ.1) N1 = 0
	IF(ISUBR.EQ.2) N2 = 0
 100	CONTINUE
	PRINT*,'ISUBR,N1,N2,NDO',ISUBR,N1,N2,NDO

	IF(ISUBR.EQ.1) THEN
	    N1 = N1+1
	    READ(44,*,END=200,ERR=200)  NDATE,NEVENT,F1,DELF,EX1,EY1,
     1		EX2,EY2,PH1,PH2,RMS
 	print*,'after read 1',ndate,nevent,rms
	    IF(N1.NE.NDO) GO TO 100
	print*,'sunclock,angmag',sunclock(n1),angmag(n1)
	    EMAG1 = SQRT(EX1**2 + EY1**2)
	    EMAG2 = SQRT(EX2**2 + EY2**2)
	    WRITE(77,*) 'SUBR 1',NEVENT,RMS,EMAG1,EMAG2
	    EMAX = AMAX1(EMAG1,EMAG2)
	    EMAX = 1.25*EMAX
	    CALL MGOGRELOCATE(1000.,2100.)
	    CALL MGOPUTLABEL(8,'YY-MM-DD',6)
	    WRITE(JUNK,234) NDATE
	    CALL MGOPUTLABEL(10,JUNK,6)
	    WRITE(JUNK,234) NEVENT
 234	    FORMAT(I10) 	
	    CALL MGOPUTLABEL(11,'  EVENT NO.',6)
	    CALL MGOPUTLABEL(10,JUNK,6)
	ELSE
	    N2 = N2+1
	    READ(45,*,END=200,ERR=200)  NDATE,NEVENT,F1,DELF,EX1,EY1,
     1		EX2,EY2,PH1,PH2,TX1,TY1,TX2,TY2,RMS
	print*,'after read 2',ndate,nevent,rms
	    IF(N2.NE.NDO) GO TO 100
	    PWR1 = EX1**2 + EY1**2 + TX1**2 + TY1**2
	    PWR2 = EX2**2 + EY2**2 + TX2**2 + TY2**2
	    WRITE(77,*) 'SUBR 2',NEVENT,RMS,SQRT(PWR1),SQRT(PWR2)
	    EMAX = AMAX1(ABS(EX1),ABS(EY1),ABS(EX2),ABS(EY2),ABS(TX1),
     1		ABS(TX2),ABS(TY1),ABS(TY2))
 145	    FORMAT(2I10,F7.3,F7.3,4F6.2,2F8.2,F9.4)
	    EMAX = 1.5*EMAX
	ENDIF
C
C		START GRAPH	
C
C*****
C	SUNCLOCK(N1) = 185			! 2519413
C	ANGMAG(N1) = 108.1
	SUNCLOCK(N1) = 3399			! 32453262
	ANGMAG(N1) = -53.9
C*****
	    CALL MGOSETLIM(-EMAX,-EMAX,EMAX,EMAX)
	    ANG_EX = 360. - 360.*SUNCLOCK(N1)/4096. - 45.
C		LEFT HANDED COORDINATE SYSTEM, Z IN DOWNWARD
C
C		PLOT A HEAVY LINE IN DIRECTION OF B
C
	    BX = .9*EMAX*COSD(ANGMAG(N1))
	    BY = .9*EMAX*SIND(ANGMAG(N1))
C	print*,'at b draw,isubr,n1,n2,angmag(n1)',isubr,n1,n2,angmag(n1)
	    CALL MGOSETLWEIGHT(3)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(BX,BY)
	    CALL MGOPUTLABEL(1,'B',6)
	    CALL MGOSETLWEIGHT(1)
C
C		PLOT A DOTTED LINE TO SUN, PUT ON RESIDUALS, AND DO BOX
C
	    CALL MGOSETLTYPE(2)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(.7*EMAX,0.)
	    CALL MGOPUTLABEL(3,'SUN',6)
	    CALL MGOSETLTYPE(0)
	    CALL MGOBOX(1,2)
	    CALL MGOXLABEL(4,'mV/m')
	    CALL MGORELOCATE(-.4*EMAX,1.1*EMAX)
	    WRITE(JUNK,235) RMS
 235	    FORMAT(F6.2) 	
	    CALL MGOPUTLABEL(3,'RMS',6)
	    CALL MGOPUTLABEL(6,JUNK,6)
	    CALL MGOPUTLABEL(5,' mV/m',6)
C
	IF(ISUBR.EQ.1) THEN
	    EANG1 = ATAN2D(-EY1,EX1) + ANG_EX
	    EANG2 = ATAN2D(-EY2,EX2) + ANG_EX
	    CALL MGORELOCATE(0.,0.)
	    EXT1 = EMAG1*COSD(EANG1)
	    EYT1 = EMAG1*SIND(EANG1)
	    CALL MGODRAW(EXT1,EYT1)
	    IF(DELF.GT.0.) THEN
	      CALL MGOPUTLABEL(2,'E1',6)
	    ELSE
	      CALL MGOPUTLABEL(2,'E2',6)
	    ENDIF
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(-EXT1,-EYT1)
	    EXT2 = EMAG2*COSD(EANG2)
	    EYT2 = EMAG2*SIND(EANG2)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(EXT2,EYT2)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(-EXT2,-EYT2)
	    IF(DELF.GT.0.) THEN
	      CALL MGOPUTLABEL(2,'E2',6)
	    ELSE
	      CALL MGOPUTLABEL(2,'E2',6)
	    ENDIF
	ELSE
	    CALL ELLIPSE(ANG_EX,DELF,EX1,EY1,EX2,EY2,TX1,TY1,TX2,TY2)
	ENDIF
C
C
 200	CONTINUE
	 PRINT*,'IN READ',NEVENT,F1,DELF,EX1
	 PRINT*,'IN READ',EX2,EY1,EY2,RMS
      ENDDO
C
	 CALL MGOSETEXPAND(.5)
	 CALL MGOPLOTID('WAVES_DIRECTIONS2',' ')
	 CALL MGOSETEXPAND(1.)
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	CLOSE(UNIT=44)
	CLOSE(UNIT=45)
c	ENDDO
C
	STOP
	END
	SUBROUTINE ELLIPSE(ANG_EX,DELF,EX1,EY1,EX2,EY2,TX1,TY1,TX2,TY2)
C
	DATA TWOPI /6.2831853/
C
	NUMBER = 100
	DELT = TWOPI/NUMBER
C
	 PRINT*,'IN ELLIPSE',ANG_EX
	 PRINT*,'IN ELLIPSE',EX1,EY1,TX1,TY1
	 PRINT*,'IN ELLIPSE',EX2,EY2,TX2,TY2
C
C	DO N = N1,N2
C	  T = (N-1024)*DELT	
C	  EX = EX1*SIN(TWOPI*F1*T + PH1) + EX2*SIN(TWOPI*F2*T + PH2)
C    1	   + TX1*COS(TWOPI*F1*T + PH1) + TX2*COS(TWOPI*F2*T + PH2)
C	  EY = EY1*SIN(TWOPI*F1*T + PH1) + EY2*SIN(TWOPI*F2*T + PH2)
C     1	   + TY1*COS(TWOPI*F1*T + PH1) + TY2*COS(TWOPI*F2*T + PH2)
C	  SUMSQ = SUMSQ + (X4DATA(N,1)/XLEN - EX)**2
C     1		+ (X4DATA(N,2)/YLEN - EY)**2
C	ENDDO
C
C	PLOT ELECTRIC FIELD ELLIPSE OF FIRST WAVE
C
	COSAANG = COSD(ANG_EX)
	SINAANG = SIND(ANG_EX)
	  EX = TX1
	  IF(ABS(EX1).GT.ABS(TX1)) EX = EX1
	  EY = TY1
	  IF(ABS(EY1).GT.ABS(TY1)) EY = EY1
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGORELOCATE(EXGSE,EYGSE)
	  IF(DELF.GT.0.) THEN
	    CALL MGOPUTLABEL(2,'E1',6)
	  ELSE
	    CALL MGOPUTLABEL(2,'E2',6)
	  ENDIF
	  EX = TX1
	  EY = TY1
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGORELOCATE(EXGSE,EYGSE)
C
	DO N = 1,NUMBER
	  T = N*DELT	
	  EX = EX1*SIN(T) + TX1*COS(T) 
	  EY = EY1*SIN(T) + TY1*COS(T) 
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGODRAW(EXGSE,EYGSE)
	ENDDO
C
C	PUT ON ARROW
C
	  T = 0.	
	  EX = EX1*SIN(T) + TX1*COS(T) 
	  EY = EY1*SIN(T) + TY1*COS(T) 
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
C	  CALL MGODRAW(EXGSE,EYGSE)
	  T = T + DELT	
	  EX = EX1*SIN(T) + TX1*COS(T) 
	  EY = EY1*SIN(T) + TY1*COS(T) 
	  DDX = EX*COSAANG + EY*SINAANG - EXGSE
	  DDY = EX*SINAANG - EY*COSAANG - EYGSE
	  SIZE = .03
	  CALL ARROW(EXGSE,EYGSE,DDX,DDY,SIZE)	
C
C	PLOT ELECTRIC FIELD ELLIPSE OF SECOND WAVE
C
	EX = TX2
	EY = TY2
	EXGSE = EX*COSAANG + EY*SINAANG
	EYGSE = EX*SINAANG - EY*COSAANG
	CALL MGORELOCATE(EXGSE,EYGSE)
	IF(DELF.GT.0.) THEN
	  CALL MGOPUTLABEL(2,'E2',6)
	ELSE
	  CALL MGOPUTLABEL(2,'E1',6)
	ENDIF
	CALL MGORELOCATE(EXGSE,EYGSE)
C
	DO N = 1,NUMBER
	  T = N*DELT	
	  EX = EX2*SIN(T) + TX2*COS(T)
	  EY = EY2*SIN(T) + TY2*COS(T)
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGODRAW(EXGSE,EYGSE)
	ENDDO
C
C	PUT ON ARROW
C
	  T = 0.	
	  EX = EX2*SIN(T) + TX2*COS(T) 
	  EY = EY2*SIN(T) + TY2*COS(T) 
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
C	  CALL MGODRAW(EXGSE,EYGSE)
	  T = T + DELT	
	  EX = EX2*SIN(T) + TX2*COS(T) 
	  EY = EY2*SIN(T) + TY2*COS(T) 
	  DDX = EX*COSAANG + EY*SINAANG - EXGSE
	  DDY = EX*SINAANG - EY*COSAANG - EYGSE
	  CALL ARROW(EXGSE,EYGSE,DDX,DDY,SIZE)	
	RETURN
	END
