	PROGRAM WAVES_DIRECTIONS
C
C	MAKES A PLOT OF WAVE DIRECTIONS OBTAINED FROM FIT_WAVE AND
C		TDSEXEY
C
	CHARACTER*120 	JUNK
	REAL		ANGMAG,SUNCLOCK
	CHARACTER*3 MONTH(12)
	DATA MONTH /'JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG',
     1    'SEP','OCT','NOV','DEC'/
C
	COMMON /MONGOPAR/
     1  X1,X2,Y1,Y2,GX1,GX2,GY1,GY2,LX1,LX2,LY1,LY2,
     1  GX,GY,CX,CY,
     1  EXPAND,ANGLE,LTYPE,LWEIGHT,
     1  CHEIGHT,CWIDTH,CXDEF,CYDEF,PSDEF,PYDEF,COFF,
     1  TERMOUT,XYSWAPPED,NUMDEV,
     1  PI,USERVAR(10),AUTODOT
	INTEGER*4 LX1,LX2,LY1,LY2,LTYPE,LWEIGHT,NUMDEV
C
C	THE 12 CONSEQUTIVE 1997 nOV 4 EVENTS:
C	DATA SUNCLOCK /0., 185.,98.,2042.,2485.,1452.,71.,2435.,3231.,
C     1		797.,4005.,2789.,6*0.,1942.,2*0.,1030.,2*1752.,
C     1	 6*1853.,23*0.,2*190.,25*0./
C	DATA ANGMAG /0., 108.,108.,108.,108.,102.,102.,105.,110.,
C     1		110.,110.,111.,6*0.,-20.0,2*0.,-17.8,2*-37.2,
C     1	6*-19.2,23*0.,2*109.1,25*0./
C	DATA ITERM /3/
	DATA ITERM /-1/
C
	NDO = 100
C
	CALL MGOINIT
	CALL MGOSETUP(ITERM)
	CALL MGOERASE
C
	IF(ITERM.LT.0) THEN
	  CALL MGOSETLOC(500., 850., 2300., 2650.)
	ELSE
	  CALL MGOSETLOC(200.,870.,80.,750.)
	ENDIF
C
C	  CALL MGOSETEXPAND(.85)
C	  IF(ITERM.GT.0) THEN
C	    CALL MGOGRELOCATE(10.,0.)                      ! maxch, crt
C	  ELSE
C	    CALL MGOGRELOCATE(400.,50.)                      ! hardcopy
C	  ENDIF
C	  CALL MGOPUTLABEL(53,STR,9)

C
C	ISUBR = 1		! 1 IS 8 VARIABLE FIT, LONGITUDINAL WAVES
C				  2 IS 12 VARIABLE FIT, WITH CIRCULAR POL.
C
	READ(5,*,ERR=10) ISUBR
	PRINT*,'READIN ISUBR=',ISUBR
	GO TO 20
 10	PRINT*,'ERROR IN WAVES_DIRECTIONS READIN'
	ISUBR = 1		! DEFAULT
C
 20	OPEN(UNIT=44,FILE='FITWAVE.RESULTS',STATUS='OLD',READONLY)
	OPEN(UNIT=45,FILE='FITWAVE12.RESULTS',STATUS='OLD',READONLY)
	READ(44,22) JUNK
	READ(44,22) JUNK
	READ(45,22) JUNK
	READ(45,22) JUNK
 22	FORMAT(A)
	N = 0
 100	CONTINUE
	N = N+1
	PRINT*,'ISUBR,N,NDO',ISUBR,N,NDO
	IF(ISUBR.EQ.1) THEN
c	    READ(44,144,END=200,ERR=300)  NDATE,NEVENT,F1,DELF,EX1,EY1,
c     1		EX2,EY2,PH1,PH2,RMS,N1,N2
	    READ(44,*,END=150,ERR=200)  NDATE,NEVENT,F1,DELF,EX1,EY1,
     1		EX2,EY2,PH1,PH2,RMS,N1,N2,ANGMAG,SUNCLOCK
 144	    FORMAT(2I10,F7.3,F7.3,4F6.2,2F8.2,F9.4)
 	    print*,'sunclock,angmag',sunclock,angmag
	    IF(N.NE.NDO) GO TO 100
 150        print*,'after read',n,ndate,nevent,rms
 	    EMAG1 = SQRT(EX1**2 + EY1**2)
	    EMAG2 = SQRT(EX2**2 + EY2**2)
	    EMAX = AMAX1(EMAG1,EMAG2)
	    EMAX = 1.2*EMAX
	ELSE
	    READ(45,*,END=160,ERR=200)  NDATE,NEVENT,F1,DELF,EX1,EY1,
     1		EX2,EY2,TX1,TY1,TX2,TY2,RMS,N1,N2,ANGMAG,SUNCLOCK
	    IF(N.NE.NDO) GO TO 100
 160	    print*,'sunclock,angmag',sunclock,angmag
	    EMAX = AMAX1(ABS(EX1),ABS(EY1),ABS(EX2),ABS(EY2),ABS(TX1),
     1		ABS(TX2),ABS(TY1),ABS(TY2))
 145	    FORMAT(2I10,F7.3,F7.3,4F6.2,2F8.2,F9.4)
	    EMAX = 1.5*EMAX
	ENDIF
C
C		START GRAPH	
C
	    CALL MGOSETLIM(-EMAX,-EMAX,EMAX,EMAX)
	    ANG_EX = 360. - 360.*SUNCLOCK/4096. - 45.
C		LEFT HANDED COORDINATE SYSTEM, Z IN DOWNWARD
C
C		PLOT A HEAVY LINE IN DIRECTION OF B
C
	    BX = EMAX*COSD(ANGMAG)
	    BY = EMAX*SIND(ANGMAG)
	    CALL MGOSETLWEIGHT(3)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(BX,BY)
	    CALL MGOPUTLABEL(1,'B',6)
	    CALL MGOSETLWEIGHT(1)
C
C		PLOT A DOTTED LINE TO SUN, WRITE EVENT NO. AND DO BOX
C
	    CALL MGOSETLTYPE(2)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(.7*EMAX,0.)
	    CALL MGOPUTLABEL(3,'SUN',6)
	    CALL MGOSETLTYPE(0)
	    CALL MGORELOCATE(-.8*EMAX,1.3*EMAX)
	    NYEAR = NDATE
	    NDAY = MOD(NDATE,100)
	    NYEAR = NYEAR/100
	    NM = MOD(NYEAR,100)
	    NYEAR = NYEAR/100	    
	    WRITE(JUNK,235) NYEAR,MONTH(NM),NDAY
 235	    FORMAT(I5,'-',A3,'-',I2)
	    CALL MGOPUTLABEL(12,JUNK,6)
	    WRITE(JUNK,234) NEVENT
 234	    FORMAT(I10) 	
	    CALL MGOPUTLABEL(11,'  EVENT NO.',6)
	    CALL MGOPUTLABEL(10,JUNK,6)
	    CALL MGORELOCATE(-.69*EMAX,1.15*EMAX)
	    CALL MGOSETEXPAND(.8)
	    WRITE(JUNK,236) N1,N2
 236	    FORMAT('SAMPLES',I5,' TO',I5)
	    CALL MGOPUTLABEL(20,JUNK,6)
	    WRITE(JUNK,237) RMS
 237	    FORMAT(F6.2) 	
	    CALL MGOPUTLABEL(6,'   RMS',6)
	    CALL MGOPUTLABEL(6,JUNK,6)
	    CALL MGOPUTLABEL(5,' mV/m',6)
	    CALL MGOSETEXPAND(1.)
	    CALL MGOXLABEL(5,' mV/m')
	    CALL MGOYLABEL(5,' mV/m')
	    CALL MGOBOX(1,2)
C
	IF(ISUBR.EQ.1) THEN
	    EANG1 = ATAN2D(-EY1,EX1) + ANG_EX
	    EANG2 = ATAN2D(-EY2,EX2) + ANG_EX
	    CALL MGORELOCATE(0.,0.)
	    EXT1 = EMAG1*COSD(EANG1)
	    EYT1 = EMAG1*SIND(EANG1)
	    CALL MGODRAW(EXT1,EYT1)
	    IF(DELF.GT.0.) THEN
	      CALL MGOPUTLABEL(8,' E\dL\df',6)
	    ELSE
	      CALL MGOPUTLABEL(8,' E\dH\df',6)
	    ENDIF
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(-EXT1,-EYT1)
	    EXT2 = EMAG2*COSD(EANG2)
	    EYT2 = EMAG2*SIND(EANG2)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(EXT2,EYT2)
	    CALL MGORELOCATE(0.,0.)
	    CALL MGODRAW(-EXT2,-EYT2)
	    IF(DELF.GT.0.) THEN
	      CALL MGOPUTLABEL(8,' E\dH\df',6)
	    ELSE
	      CALL MGOPUTLABEL(8,' E\dL\df',6)
	    ENDIF
	ELSE
	    CALL ELLIPSE(ANG_EX,DELF,EX1,EY1,EX2,EY2,TX1,TY1,TX2,TY2)
	ENDIF
C
C
 200	CONTINUE
	 PRINT*,'IN READ',NEVENT,F1,DELF,EX1
	 PRINT*,'IN READ',EX2,EY1,EY2,RMS
	 CALL MGOSETEXPAND(.5)
	 CALL MGOPLOTID('WAVES_DIRECTIONS',' ')
	 CALL MGOSETEXPAND(1.)
	IF(ITERM.LT.0) THEN
	  CALL MGOPRNTPLOT(NVEC)
	  PRINT*,' NO. VECTORS PLOTTED',NVEC
	ELSE
	  CALL MGOTCLOSE
	ENDIF
C
	CLOSE(UNIT=44)
	CLOSE(UNIT=45)
	PAUSE
C
	STOP
 300	PRINT*,'READ ERROR AT N,NDATE,NEVENT =',N,NDATE,NEVENT
	STOP
	END
	SUBROUTINE ELLIPSE(ANG_EX,DELF,EX1,EY1,EX2,EY2,TX1,TY1,TX2,TY2)
C
	DATA TWOPI /6.2831853/
C
	NUMBER = 100
	DELT = TWOPI/NUMBER
C
C
C	DO N = N1,N2
C	  T = (N-1024)*DELT	
C	  EX = EX1*SIN(TWOPI*F1*T + PH1) + EX2*SIN(TWOPI*F2*T + PH2)
C    1	   + TX1*COS(TWOPI*F1*T + PH1) + TX2*COS(TWOPI*F2*T + PH2)
C	  EY = EY1*SIN(TWOPI*F1*T + PH1) + EY2*SIN(TWOPI*F2*T + PH2)
C     1	   + TY1*COS(TWOPI*F1*T + PH1) + TY2*COS(TWOPI*F2*T + PH2)
C	  SUMSQ = SUMSQ + (X4DATA(N,1)/XLEN - EX)**2
C     1		+ (X4DATA(N,2)/YLEN - EY)**2
C	ENDDO
C
C	PLOT ELECTRIC FIELD ELLIPSE OF FIRST WAVE
C
	COSAANG = COSD(ANG_EX)
	SINAANG = SIND(ANG_EX)
	  EX = TX1
	  EY = TY1
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGORELOCATE(EXGSE,EYGSE)
	  IF(DELF.GT.0.) THEN
	    CALL MGOPUTLABEL(8,' E\dL\df',6)
	  ELSE
	    CALL MGOPUTLABEL(8,' E\dH\df',6)
	  ENDIF
	  CALL MGORELOCATE(EXGSE,EYGSE)
C
	DO N = 1,NUMBER
	  T = N*DELT	
	  EX = EX1*SIN(T) + TX1*COS(T) 
	  EY = EY1*SIN(T) + TY1*COS(T) 
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGODRAW(EXGSE,EYGSE)
	ENDDO
C
C	PUT ON ARROW
C
	  T = 0.	
	  EX = EX1*SIN(T) + TX1*COS(T) 
	  EY = EY1*SIN(T) + TY1*COS(T) 
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
C	  CALL MGODRAW(EXGSE,EYGSE)
	  T = T + DELT	
	  EX = EX1*SIN(T) + TX1*COS(T) 
	  EY = EY1*SIN(T) + TY1*COS(T) 
	  DDX = EX*COSAANG + EY*SINAANG - EXGSE
	  DDY = EX*SINAANG - EY*COSAANG - EYGSE
	  SIZE = .03
	  CALL ARROW(EXGSE,EYGSE,DDX,DDY,SIZE)	
C
C	PLOT ELECTRIC FIELD ELLIPSE OF SECOND WAVE
C
	EX = TX2
	EY = TY2
	EXGSE = EX*COSAANG + EY*SINAANG
	EYGSE = EX*SINAANG - EY*COSAANG
	CALL MGORELOCATE(EXGSE,EYGSE)
C	CALL MGOPUTLABEL(3,' E2',6)
	  IF(DELF.LE.0.) THEN
	    CALL MGOPUTLABEL(8,' E\dL\df',6)
	  ELSE
	    CALL MGOPUTLABEL(8,' E\dH\df',6)
	  ENDIF
	CALL MGORELOCATE(EXGSE,EYGSE)
C
	DO N = 1,NUMBER
	  T = N*DELT	
	  EX = EX2*SIN(T) + TX2*COS(T)
	  EY = EY2*SIN(T) + TY2*COS(T)
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
	  CALL MGODRAW(EXGSE,EYGSE)
	ENDDO
C
C	PUT ON ARROW
C
	  T = 0.	
	  EX = EX2*SIN(T) + TX2*COS(T) 
	  EY = EY2*SIN(T) + TY2*COS(T) 
	  EXGSE = EX*COSAANG + EY*SINAANG
	  EYGSE = EX*SINAANG - EY*COSAANG
C	  CALL MGODRAW(EXGSE,EYGSE)
	  T = T + DELT	
	  EX = EX2*SIN(T) + TX2*COS(T) 
	  EY = EY2*SIN(T) + TY2*COS(T) 
	  DDX = EX*COSAANG + EY*SINAANG - EXGSE
	  DDY = EX*SINAANG - EY*COSAANG - EYGSE
	  CALL ARROW(EXGSE,EYGSE,DDX,DDY,SIZE)	
C
	RETURN
	END
