	SUBROUTINE WGEOM(IA,IB,X,Y,Z,NM,NP,NAT,NSA,NPLA,VGA,BDSK,
     2  ZLDA,NWG,VG,ZLD,WV,NFS1,NFS2)
	COMMON /DIPOLES/ H1,H2,S
	DIMENSION IA(1),IB(1),X(1),Y(1),Z(1),NSA(1),NPLA(1),BDSK(1)
	COMPLEX VGA(1),ZLDA(1),VG(1),ZLD(1)
	DATA H1,H2,S /1.,1.,.5/
C
C	GEOMETRY FOR WIND
C
	PRINT*,'WGEOM5, FOR MONOPOLE MAG BOOM AND ONE ANTENNA'
C
C	SPECIFY H = WIRE LENGTH AND NM1 = NUMBER OF SEGMENTS IN EACH ONE.
	NM1 = 6
C	INSURE THAT NM1 IS AN EVEN NUMBER
	NM1 = 2*((NM1+1)/2)
	NM = 2*NM1
C	THE NUMBER OF POINTS IS
	NP = 2*NM1+NINTER+3
	NP1 = NM1+1
C	THE SEGMENT SIZE IS
	H = H1
	DH = H/NM1
C	DEFINE COORDINATES OF NP POINTS AND NM SEGMENTS
	DO I = 1,NP1
	  X(I) = 0.
	  Y(I) = 0.
	  Z(I) = (-H/2.0) + (I-1)*DH
	print*,i,z(i)
	  IF(I.NE.NP1) THEN
	    IA(I) = I
	    IB(I) = I+1
	  ENDIF
	ENDDO
C	DEFINE GENERATOR LOCATION AND VALUE
	IGN = (NM1/2) + 1
	VG(IGN) = CMPLX(1.,0.)
	ZLD(IGN) = CMPLX(0.,0.)
C	INDICATE TWO-PORT COUPLING COMPUTATION DESIRED
	NFS1 = IGN
C	THE SEGMENT SIZE IS
	H = H2
	DH = H/NM1
C	DEFINE COORDINATES OF NP POINTS AND NM SEGMENTS
	DO I = NP1+1,NP
	  X(I) = S
	  Y(I) = 0.
	  Z(I) = (-H/2.0) + (I-1-NP1)*DH
	print*,i,z(i)
	  IF(I.NE.NP1) THEN
	    IA(I) = I
	    IB(I) = I+1
	  ENDIF
	ENDDO
C	DEFINE GENERATOR LOCATION AND VALUE
	IGN = (NM1/2) + 1 + NP1 
	VG(IGN) = CMPLX(1.,0.)
	ZLD(IGN) = CMPLX(0.,0.)
C	DO INTERCONNECTION
	DH = S/NINTER
	X(NP+1) = X(IGN)
	Y(NP+1) = Y(IGN)
	Z(NP+1) = Z(IGN)
	DO I = NP+1,NP+2+NINTER
	  X(I) = X(I-1) + DH
	  Y(I) = Y(I-1)
	  Z(I) = Z(I-1)
	  ZLD(I) = CMPLX(0.,1.E6)
	print*,i,X(I),z(i)
	  IF(I.NE.NP+2+NINTER) THEN
	    IA(I) = I
	    IB(I) = I+1
	  ENDIF
	ENDDO
C	INDICATE NO ATTACHMENTS
	NAT=0
C	INDICATE TWO-PORT COUPLING COMPUTATION DESIRED
	NFS2 = IGN
	print*,'wgeom,np,nm,nfs1,nfs2',np,nm,nfs1,nfs2
	RETURN
	END	

