	SUBROUTINE WGEOM(IA,IB,X,Y,Z,NM,NP,NAT,NSA,NPLA,VGA,BDSK,
     2  ZLDA,NWG,VG,ZLD,WV,NFS1,NFS2)
C
C	THIS IS MY SECOND TRY, AND IS A WIRE MODEL AS RECOMMENDED
C	BY E.H.NEWMAN BY TELEPHONE ON 10 JULY 1997
C
C	REPRESENT WIND BY A STACK OF WIRES IN THE FORM OF 'NSIDE'
C	N SIDED REGULAR POLYGONS.  NSIDE MUST BE AT LEAST 8. AND
C	MUST BE AN INTEGRAL MULTIPLE OF 8.
C	THERE ARE NSTACK SUCH POLYGONS.  NSTACK MUST BE AT LEAST
C	THREE.  WIRES RUN VERTICALLY THROUGH THE CORNERS OF THE
C	POLYGONS, AND RUN FROM CORNER TO OPPOSITE CORNER IN THE
C	TOP AND BOTTOM.  THE MAG BOOMS ARE REPRESENTED BY WIRES
C	ALSO.  SO FAR THEY ALL HAVE TO BE IN THE SAME VERTICAL
C	PLANE.
C
C	I CHANGED MY MIND FOR NOW.  MAKE IT 5 POLYGONS, TOP, BOTTOM,
C		MIDDLE, AND TWO MORE AT THE TOP AND BOTTOM EDGES OF
C		THE MAG BOOMS
C
	DIMENSION NSA(1)
	DIMENSION ZPOLY(11)
	COMPLEX ZLDA(10),VG(1),ZLD(1)
	COMPLEX ZSHT(20),VGA(10)
	DATA RWIND, HEIGHT, ZMONOPOLE /1.22,1.83,5.5/
	DIMENSION X(200),Y(200),Z(200),IA(200),IB(200),NAS(10)
	DIMENSION IAB(10),NPLA(10),BDSK(10)
	INTEGER*4 NBOOMAT(6),NXAT(2),NYAT(2),NZAT(2),NSX(2),NSY(2),NSZ(2)
	REAL LBOOM
C	
C	CALCULATE AN OCTAGON WITH THE SAME AREA AS TOP OF WIND
C
	PRINT*,'WGEOM, WIND_MODEL2,  CALLED'
	RBOOM = .12
	LBOOM = 12.
	NSIDE = 8
	NSTACK = 5
C
	NSIDE = (NSIDE/8)*8
	IF(NSIDE.LT.8) NSIDE = 8
	NSTACK = (NSTACK/2)*2 + 1
	IF(NSTACK.LT.5) NSTACK = 5
C
C	INDICES FOR ANTENNA AND BOOM LOCATIONS
C
	IBOOM = 1
	IXAT = 1
	IYAT = 1
	LEV_ANT = (NSTACK+1)/2
	LEV_BOOM = LEV_ANT - 1
	N_AZ_BOOM = NSIDE/2 + 1				! -X BOOM
	N_AZ_EX = NSIDE/8 + 1
	N_AZ_EY = N_AZ_EX + NSIDE/4
	PRINT*,'LEV_BOOM',LEV_BOOM
	PRINT*,'LEV_ANT',LEV_ANT
	PRINT*,'N_AZ_BOOM',N_AZ_BOOM
C
C	HEIGHTS OF THE VARIOUS POLYGONS IN THE STACK
C
	ZPOLY(1) = -.5*HEIGHT
	ZPOLY(2) = -RBOOM
	ZPOLY(3) = 0.
	ZPOLY(4) =  RBOOM
	ZPOLY(5) = .5*HEIGHT
	
C
C	OPEN(UNIT=99,NAME = 'WIND.INPUT',STATUS='NEW')
C
C	DO THE POLYGONAL BOTTOM, SEGMENTS 1 TO NSIDE
C
	Z(1) = -.5*HEIGHT
	X(1) = RWIND
	Y(1) = 0.
	IA(1) = 1
	IB(1) = 2
	NPTS = 1
	DO N = 2,NSIDE
	  Z(N) = Z(1)
	  ANG = (N-1)*360./NSIDE	
	  X(N) = RWIND*COSD(ANG)
	  Y(N) = RWIND*SIND(ANG)
	  NPTS = NPTS+1
	  IA(N) = N
	  IB(N) = N+1
	ENDDO	
	IB(NPTS) = 1
	NSEGS = NPTS
	PRINT*,'END OF BOTTOM, NTOT=',NPTS
C
C	DO THE OTHER POLYGONS IN THE STACK AND THE WIRES TO THE PRECEEDING
C		POLYGON.  MAKE A PLACE FOR THE MAG BOOMS, EACH CONSISTING
C		OF THREE WIRES.  SAVE LOCATIONS WHERE ANTENNAS AND BOOMS
C		ARE ATTACHED
C
	MPLUSX = 1
	MINUSX = NSIDE/2 + 1
	NBOOM = (NSTACK+1)/2
C
	DO N = 2,NSTACK
	  DO M = 1,NSIDE
	      NPTS = NPTS+1
	      X(NPTS) = X(M) 
	      Y(NPTS) = Y(M) 
	      Z(NPTS) = ZPOLY(N)
C		SEGMENTS OF THE POLYGON
  	      NSEGS = NSEGS+1
	      IA(NSEGS) = NPTS
	      IB(NSEGS) = NPTS+1
C
C		SAVE THE POSITIONS OF THE BOOM AND ANTENNA ATTACHMENTS
C
	      IF(N.EQ.LEV_BOOM.AND.IBOOM.LE.6) THEN		!BOOMS
		IF(M.EQ.1) THEN
		  NBOOMAT(IBOOM) = NPTS
		  IBOOM = IBOOM+1
		ENDIF
		IF(M.EQ.N_AZ_BOOM) THEN
		  NBOOMAT(IBOOM) = NPTS
		  IBOOM = IBOOM+1
		  LEV_BOOM = LEV_BOOM + 1
		ENDIF
	      ENDIF
C
	      IF(N.EQ.LEV_ANT) THEN				! ANTENNAS
		IF(M.EQ.N_AZ_EX) THEN
		  NXAT(IXAT) = NPTS
		  NSX(IXAT) = NSEGS
		  IXAT = IXAT+1
		  N_AZ_EX = N_AZ_EX + NSIDE/2
		ENDIF
		IF(M.EQ.N_AZ_EY) THEN
		  NYAT(IYAT) = NPTS
		  NSY(IYAT) = NSEGS
		  IYAT = IYAT+1
		  N_AZ_EY = N_AZ_EY + NSIDE/2
		ENDIF
	      ENDIF
	  ENDDO
C
	      IB(NSEGS) = IB(NSEGS)-NSIDE		! LAST ONE
C
C		DO SEGMENTS CONNECTING TO PREVIOUS POLYGON
C
	  DO M = 1,NSIDE
	    NSEGS = NSEGS+1
	    IA(NSEGS) = NPTS-NSIDE + M 
	    IB(NSEGS) = IA(NSEGS)-NSIDE
	  ENDDO
C
C	  SAVE FIRST POINT OF TOP
C
	  NPTOP = NPTS - NSIDE + 1
	ENDDO
C
	PRINT*,'END OF SURFACE,NPTS,NSEGS=',NPTS,NSEGS
C
C	CHECK POINTS OF ATTACHMENT
C
	DO I = 1,6
	  J = NBOOMAT(I)
	  PRINT*,'BOOM',J,X(J),Y(J),Z(J)
	ENDDO
	DO I = 1,2
	  J = NXAT(I)
	  PRINT*,' EX ',J,X(J),Y(J),Z(J)
	ENDDO
	DO I = 1,2
	  J = NYAT(I)
	  PRINT*,' EY ',J,X(J),Y(J),Z(J)
	ENDDO
C
C	DO SEGMENTS OF TOP AND BOTTOM
C
C	CENTER OF BOTTOM
C
	NPTS = NPTS+1
	NZAT(2) = NPTS
	X(NPTS) = 0.
	Y(NPTS) = 0.
	Z(NPTS) = -HEIGHT/2.
C
C	SEGMENTS GO FROM CENTER TO OUTSIDE
C
	DO N = 1,NSIDE
	  NSEGS = NSEGS+1
	  IA(NSEGS) = NZAT(2)
	  IB(NSEGS) = N
	ENDDO
C
C	CENTER OF TOP
C	
	NPTS = NPTS+1
	NZAT(1) = NPTS
	X(NPTS) = 0.
	Y(NPTS) = 0.
	Z(NPTS) = HEIGHT/2.
C
	DO N = NPTOP,NPTOP+NSIDE-1
	  NSEGS = NSEGS+1
	  IA(NSEGS) = NZAT(1)
	  IB(NSEGS) = N
	ENDDO
C
C	X ANTENNA
C
	I = NPTS+1
	NPTS = I 	
	X(I) = (RWIND+50.)/SQRT(2.)		! START OUTER END OF +EX
	Y(I) = X(I)
	Z(I) = 0.
	DHX = -5./SQRT(2.)				! 1 SEGMENTS IN 5. M.
	DHY = -5./SQRT(2.)				! 1 SEGMENTS IN 5. M.
	DO I = 2,11
	  NPTS = NPTS+1
	  X(NPTS) = X(NPTS-1) + DHX
	  Y(NPTS) = Y(NPTS-1) + DHY
	  Z(NPTS) = Z(NPTS-1)
	  NSEGS = NSEGS+1
	  IA(NSEGS) = NPTS-1
	  IB(NSEGS) = NPTS
C	PRINT 45,'EX',NPTS,NSEGS,IA(NSEGS),IB(NSEGS),X(NPTS),Y(NPTS),Z(NPTS)
 45	FORMAT(a4,4I5,3F8.3,1X,3F8.3)
	ENDDO 	
C
C		ATTACH INNER END TO SPACECRAFT, REPLACE LAST POINT
C
	NPTS = NPTS-1
	IB(NSEGS) = NXAT(1)
C
C	FIRST SEGMENT OF -EX
C
	NSEGS = NSEGS+1
	IA(NSEGS) = NXAT(2)
	I = NXAT(2)
C
	NPTS = NPTS+1
	X(NPTS) = X(I) + DHX
	Y(NPTS) = Y(I) + DHY
	Z(NPTS) = 0.
	IB(NSEGS) = NPTS
	DO I = 13,21
	  NPTS = NPTS+1
	  X(NPTS) = X(NPTS-1) + DHX
	  Y(NPTS) = Y(NPTS-1) + DHY
	  Z(NPTS) = Z(NPTS-1)
	  NSEGS = NSEGS+1
	  IA(NSEGS) = NPTS-1
	  IB(NSEGS) = NPTS
C	PRINT 45,'EX',NPTS,NSEGS,IA(NSEGS),IB(NSEGS),X(NPTS),Y(NPTS),Z(NPTS)
	ENDDO 	
C
C	Y ANTENNA
C
	I = NPTS+1
	NPTS = I
	X(I) = -(RWIND+7.5)/SQRT(2.)		! START AT OUTER END +EY
	Y(I) = -X(I)
	Z(I) = 0.
	DHX = 3.75/SQRT(2.)			! 2 SEGMENTS IN 7.5 M.
	DHY = -3.75/SQRT(2.)			! 2 SEGMENTS IN 7.5 M.
	DO I = 24,25
	  NPTS = NPTS+1
	  X(NPTS) = X(NPTS-1) + DHX
	  Y(NPTS) = Y(NPTS-1) + DHY
	  Z(NPTS) = Z(NPTS-1)
	  NSEGS = NSEGS+1
	  IA(NSEGS) = NPTS-1
	  IB(NSEGS) = NPTS
C	PRINT 45,'EY',NPTS,NSEGS,IA(NSEGS),IB(NSEGS),X(NPTS),Y(NPTS),Z(NPTS)
	ENDDO 
C
C	ATTACH INNER END TO S/C, REPLACE X,Y,Z,IA,IB
C
	NPTS = NPTS-1    		! THIS REPLACES INNER POINT
	IB(NSEGS) = NYAT(1)
C
C	FIRST SEGMENT OF 
	IA(NSEGS+1) = NYAT(2)
	I = NYAT(2)
	NPTS = NPTS+1
	X(NPTS) = X(I) + DHX
	Y(NPTS) = Y(I) + DHY
	Z(NPTS) = Z(I)
	NSEGS = NSEGS+1
	IA(NSEGS) = NYAT(2)
	IB(NSEGS) = NPTS
C	PRINT 45,'EY',NPTS,NSEGS,IA(NSEGS),IB(NSEGS),X(NPTS),Y(NPTS),Z(NPTS)
C			ONLY ONE MORE POINT
	NPTS = NPTS+1
	X(NPTS) = X(NPTS-1) + DHX
	Y(NPTS) = Y(NPTS-1) + DHY
	Z(NPTS) = Z(NPTS-1)
	NSEGS = NSEGS+1
	IA(NSEGS) = NPTS-1
	IB(NSEGS) = NPTS
C	PRINT 45,'EY',NPTS,NSEGS,IA(NSEGS),IB(NSEGS),X(NPTS),Y(NPTS),Z(NPTS)
C
C	Z ANTENNA, PLUS FIRST
C
	NSEGS = NSEGS+1
	NPTS = NPTS+1
	IA(NSEGS) = NZAT(1)
	NSZ(1) = NSEGS
	X(NPTS) = 0.
	Y(NPTS) = 0.
	Z(NPTS) = HEIGHT/2. + .5*ZMONOPOLE
	IB(NSEGS) = NPTS
	NSEGS = NSEGS+1
	IA(NSEGS) = NPTS
	NPTS = NPTS+1
	X(NPTS) = 0.
	Y(NPTS) = 0.
	Z(NPTS) = Z(NPTS-1) + .5*ZMONOPOLE
	IB(NSEGS) = NPTS
C
	NSEGS = NSEGS+1
	NPTS = NPTS+1
	IA(NSEGS) = NZAT(2)
	NSZ(2) = NSEGS
	X(NPTS) = 0.
	Y(NPTS) = 0.
	Z(NPTS) = -HEIGHT/2. - .5*ZMONOPOLE
	IB(NSEGS) = NPTS
	NSEGS = NSEGS+1
	IA(NSEGS) = NPTS
	NPTS = NPTS+1
	X(NPTS) = 0.
	Y(NPTS) = 0.
	Z(NPTS) = Z(NPTS-1) - .5*ZMONOPOLE
	IB(NSEGS) = NPTS
C
C	END OF X,Y,Z ANTENNA CALCULATION
C
C	DO MAG BOOMS, 3 WIRES IN EACH ONE, EA. 3 SEGMENTS OF 4 METERS EACH
C
	DBH = 4.
	DO IWIRE = 1,3
	  NSEGS = NSEGS + 1
	  II = NBOOMAT(2*IWIRE-1)
	  NPTS = NPTS+1
	  X(NPTS) = X(II) + DBH
	  Y(NPTS) = 0.
	  Z(NPTS) = ZPOLY(IWIRE +1)
	  IA(NSEGS) = II
	  IB(NSEGS) = NPTS
	  DO I = 2,3
	    NPTS = NPTS+1
	    X(NPTS) = X(NPTS-1) + DBH
	    Y(NPTS) = Y(NPTS-1) 
	    Z(NPTS) = Z(NPTS-1)
	    NSEGS = NSEGS+1
	    IA(NSEGS) = NPTS-1
	    IB(NSEGS) = NPTS
	  ENDDO
	ENDDO


	DBH = -4.
	DO IWIRE = 4,6
	  NSEGS = NSEGS + 1
	  II = NBOOMAT(2*IWIRE-6)
	  NPTS = NPTS+1
	  X(NPTS) = X(II) + DBH
	  Y(NPTS) = 0.
	  Z(NPTS) = ZPOLY(IWIRE - 2)
	  IA(NSEGS) = II
	  IB(NSEGS) = NPTS
	  DO I = 2,3
	    NPTS = NPTS+1
	    X(NPTS) = X(NPTS-1) + DBH
	    Y(NPTS) = Y(NPTS-1) 
	    Z(NPTS) = Z(NPTS-1)
	    NSEGS = NSEGS+1
	    IA(NSEGS) = NPTS-1
	    IB(NSEGS) = NPTS
	  ENDDO
	ENDDO
C
	PRINT*,'SO FAR,(Y DONE) NPTS,NSEGS=',NPTS,NSEGS
	PRINT*,' '
	DO NN = 1,NSEGS
	  II = IA(NN)
	  JJ = IB(NN)
	  PRINT 45,'  ',NPTS,NN,IA(NN),IB(NN),X(II),Y(II),Z(II),
     1		X(JJ),Y(JJ),Z(JJ)
	ENDDO
C
C
C	CONNECT ENDS TOGETHER--NOT DONE YET
C

C	IREC = 0
C	IPN = 3
C	IGENSIDE = 0
C	ZSHT(1) = CMPLX(0.,0.)
C	WRITE(99,1001) NCRNS,SEGM,IREC,IPN,IGENSIDE,ZSHT(1)
 1001	FORMAT(I4,F6.2,3I4,2E12.2)
C
C	READ 10, ON PAGE 40, SAVING IMPEDANCE MATRIX
C
	IWRZM = 0
	IRDZM = 0
C	WRITE(99,*) IWRZM,IRDZM
C	
C	DO THE WIRES AND MAG BOOMS, AND THE ATTACHMENTS
C		HIGHEST DESIRED FREQUENCY IS 15 MHZ, WAVELENGTH = 20 M
C		A SEGMENT SHOULD BE LESS THAN 1/4 WAVELENGTH LONG
C		SO 12 SEGMENTS FOR X, 2 FOR Y, 2 FOR Z, 3 FOR MAG BOOMS		
C
C	READ 11, OVERALL SPECS 
C
	NM = NSEGS
	NP = NPTS
	NAT = 0				! NO WIRE TO PLATE ATTACHMENTS
	NFPT = 6			! TWO FEED POINTS, FOUR LOAD POINTS
	NFS1 = 0			! NO MUTUAL COUPLING FOR NOW
	NFS2 = 0
C
C	READ 12 AND 13 ARE THE XYZ AND IA,IB ABOVE
C
C	READ 14 GIVES FEED POINTS
C	THIS IS FOR Y
C
	I = NSX(1) 				! X
	VG(I) = CMPLX(0.,0.)
	ZLD(I) = CMPLX(1.E7,0.)
	I = NSX(2) + NSEGS 			! -X
	VG(I) = CMPLX(0.,0.)
	ZLD(I) = CMPLX(1.E7,0.)
	I = NSY(1) 	 			! Y
	VG(I) = CMPLX(5.,0.)
	ZLD(I) = CMPLX(0.,0.)
	I = NSY(2) + NSEGS 			! -Y
	VG(I) = CMPLX(-.5,0.)
	ZLD(I) = CMPLX(0.,0.)
C
	I = NSZ(1) 	 			! FOR +Z
	VG(I) = CMPLX(0.,0.)
	ZLD(I) = CMPLX(1.E7,0.)
	I = NSZ(2) 	 			! FOR -Z
	VG(I) = CMPLX(0.,0.)
	ZLD(I) = CMPLX(1.E7,0.)
	
C	DO MAG BOOM AND Y, MONOPOLES
C	NM = 5
C	NP = NM+2
C	NAT = 2
C	NFEEDPT = 0		! EXCLUDING WIRE-TO-PLATE ATTACH. PTS.
C	NFS1 = 1
C	NFS2 = 5
C	WRITE(99,1003) NM,NP,NAT,NFEEDPT,NFS1,NFS2
 1003	FORMAT(10I6)
C	READ 12, COORDINATES OF THE POINTS, MAG BOOM FIRST
C	X(1) = RFLAT
C	Y(1) = 0.
C	Z(1) = 0.
C	WRITE(99,*) X(1),Y(1),Z(1)
C	DH = 4.				! 3 SEGMENTS IN 12 M. FOR MAG BOOM
C	DO I = 2,4
C	  X(I) = X(I-1) + DH
C	  Y(I) = Y(I-1) 
C	  Z(I) = Z(I-1)
C	  WRITE(99,*) X(I),Y(I),Z(I)
C	ENDDO
C
C	DO ANTENNAS
C
C	DO I = 28,29
C	  X(I) = X(I-1) + DHX
C	  Y(I) = Y(I-1) + DHY
C	  Z(I) = Z(I-1)
C	  WRITE(99,*) X(I),Y(I),Z(I)
C	ENDDO 	
C	
C	READ 13, DEFINE ENDPOINTS OF SEGMENTS
C
C
C	READ 14, FEED POINTS, TWO LOADS AND TWO GENERATORS
C
C	  WRITE(99,1002) NAS(I),IAB(I),NPLA(I),VGA(I),ZLDA(I),BDSK(I)
C	I = 1
C	ISEGM = 10				! x antenna 
C	IAB(I) = 1
C	VGA(1) = CMPLX(0.,0.)
C	ZLDA(1) = CMPLX(1.E7,0.)
C	WRITE(99,1004) ISEGM,IAB(I),VGA(I),ZLDA(I)
C	ISEGM = 13
C	IAB(2) = 0
C	WRITE(99,1004) ISEGM,IAB(2),VGA(I),ZLDA(I)
C	ISEGM = 24				! y antenna
C	IAB(3) = 1
	VGA(1) = CMPLX(1.,0.)
	ZLDA(1) = CMPLX(0.,0.)
C	WRITE(99,1004) ISEGM,IAB(3),VGA(1),ZLDA(1)
C	ISEGM = 26
C	IAB(4) = 0
C	WRITE(99,1004) ISEGM,IAB(4),-VGA(1),ZLDA(1)
C
C	READ 15, ATTACHMENT POINTS, THERE ARE NONE
C
C	NAS(1) = 1
C	IAB(1) = 0
C	NPLA(1) = 10
C	VGA(1) = CMPLX(1.,0.)
C	ZLDA(1) = CMPLX(0.,0.)
C	BDSK(1) = .9*SIDE/2.
C	DO I = 1,NAT
C	  WRITE(99,1002) NAS(I),IAB(I),NPLA(I),VGA(I),ZLDA(I),BDSK(I)
C	ENDDO
 1002	FORMAT(3I4,1X,2('(',E10.3,','E10.3,')'),F8.4)
 1004	FORMAT(2I4,1X,2('(',E10.3,','E10.3,')'),F8.4)
	RETURN
	END
