	SUBROUTINE WINDOFFS(IPRINT)
C
C	CALCULATES OFFSETS FROM A SINE WAVE TEST
C
	CHARACTER*128 STR(7)
	COMMON /SPBLK/ PWRW(512),PWRNW(512),FDATA(1024),DATA(1024),IFMAX
	COMMON /PLOTDT/ ITERM,FFTAVR,NDRV,AMP,IWINDW,STR
c
	common /fftblk/ nexpt(1024),ndata(1024)
	common /headblk/ major,minor,ifftch,scet
	character*32 scet
c
C	10 CHANNELS, 4 GAINS, 9 EXAMPLES OF EACH
	DIMENSION OFFSTR(10,4,13),NCOUNT(10,4)            ! HOLDS UP TO 9 VALUES
	DIMENSION X(25),DX(25),Y(25)
	DATA NCOUNT /40*0/
	DATA TWOPI /6.2831853/
C
C	DETERMINE FREQUENCY BY DOING A FOURIER TRANSFORM
C
	CALL TIMEFFT
C
C	NOW DO HUNTMN TO FIND EXACT FREQUENCY AND AMPLITUDES
C
	X(1) = FLOAT(IFMAX)/FLOAT(NPROS)
	DX(2) = .5/FLOAT(NPROS)
	SUMSQS = 1..E6
	DO IT = 1,10
	  CALL HUNTMN(1,X,DX,Y,SINFIT,SUMSQ)
	  PRINT*,'HUNTMN',IT,X(1),SUMSQ
	  SUMSQS = SUMSQ
	ENDDO
C
	IF(IPRINT.NE.0) THEN
	  DO ICH = 1,6 
	    DO NE = 1,4
	      NP = NCOUNT(ICH,NE) 
	      PRINT 1005,ICH,NE-1,(OFFSTR(ICH,NE,N),N=1,NP)
	      WRITE(26,1005) ICH,NE-1,(OFFSTR(ICH,NE,N),N=1,NP)
 1005	      FORMAT(I4,I3,13F8.1)
	    ENDDO
	  ENDDO
	  NE = 4
	  DO ICH = 7,9
	    NP = NCOUNT(ICH,NE) 
	    PRINT 1005,ICH,NE-1,(OFFSTR(ICH,NE,N),N=1,NP)
	    WRITE(26,1005) ICH,NE-1,(OFFSTR(ICH,NE,N),N=1,NP)
	  ENDDO
	  NE = 3
	  ICH = 10
	  NP = NCOUNT(ICH,NE) 
	  PRINT 1005,ICH,NE-1,(OFFSTR(ICH,NE,N),N=1,NP)
	  WRITE(26,1005) ICH,NE-1,(OFFSTR(ICH,NE,N),N=1,NP)
	ENDIF
C
 1001	FORMAT(I4,1X,20I5)
 1002	FORMAT(A)
 1003	FORMAT(' scet',a32,'  s/c maj,min frame',I6,'.',I3.3)
 1004	FORMAT(A15,4F12.3)
	PRINT 1003,MAJOR,MINOR
	PRINT *,' FFT CHANNEL',IFFTCH
	PRINT *,' scet ',SCET
	print*,'1st,last data',ndata(1),ndata(1024)
	print*,'1st,last expt',nexpt(1),nexpt(1024)
C
C	WRITE(16, 1003) MAJOR,MINOR
C	WRITE(16,*)' FFT CHANNEL',IFFTCH
C	WRITE(16,*) ' scet ',SCET
C	WRITE(16,*) '1st,last data',ndata(1),ndata(1024)
C	WRITE(16,*)'1st,last expt',nexpt(1),nexpt(1024)
C
C
	DAMAX = -1.E7
	DAMIN =  1.E7
	DO IK = 1,1024
	  NTEMP = NDATA(IK).AND.4095
	  TEMP = -(NTEMP-2048)
	  DATA(IK) = TEMP*(-16.)**NEXPT(IK)
	  FDATA(IK) = ABS(TEMP)+2048.*NEXPT(IK)
	  IF(DATA(IK).LT.0.) FDATA(IK) = -FDATA(IK)
	  IF(FDATA(IK).GT.DAMAX) THEN
	    MAXEXP = NEXPT(IK)
	    MAXDAT = NDATA(IK)
	    DAMAX = FDATA(IK)
	  ENDIF
	  IF(FDATA(IK).LT.DAMIN) THEN
	    MINEXP = NEXPT(IK)
	    MINDAT = NDATA(IK)
	    DAMIN = FDATA(IK)
	  ENDIF
	ENDDO
C
	IF(MAXEXP.EQ.MINEXP) THEN
	  NP = NCOUNT(IFFTCH,MINEXP+1) + 1
	  OFFSTR(IFFTCH,MINEXP+1,NP) = .5*(MAXDAT+MINDAT)
	  NCOUNT(IFFTCH,MINEXP+1)  = NP
	ENDIF
C
C	WRITE(16,*) 'min,max data,expt',mindat,minexp,maxdat,maxexp
C
C
	RETURN
	END

