	SUBROUTINE XFGSE(TMCH,NSYS,NPT,SPINRATE,SPSS,AANG,XDATA,XGSE)
C
C	THIS TRANSFORMS THE ELECTRIC FIELD INTO THE GSE SYSTEM
C	THE INPUT IS THE ELECTRIC FIELD IN THE SPACECRAFT ANTENNA
C	SYSTEM IN XDATA, THE OUTPUT, IN XGSE, IS THE ELECTRIC FIELD IN 
C	THE GSE SYSTEM.  NOTE THAT THE S/C IS UPSIDE DOWN, SO THAT IF
C	+EX POINTS AT THE SUN (ANG=0) THEN +EY POINTS IN THE - Y (GSE)
C	DIRECTION
C	NPT IS THE NUMBER OF DATA POINTS IN A SERIES
C	NSYS = 1 IS ANTENNA SYSTEM, = 2 IS ? SYSTEM, = 3 IS ? SYSTEM
C
	INTEGER*4 NSYS
	INTEGER*4 OK,OKT,TMCH,W_ITEM_I4,W_ITEM_R4,W_ITEM_R8
	character*32	item
C	COMMON /PARTBLK/ XDATA(2050,4),XFDATA(2050,4),XGSE(2050,4),
C     1		XRE,YRE,ZRE,SUNCLOCK,SPINRATE,SPSS
	REAL XDATA(2050,4),XGSE(2050,4)
	COMMON /VARMATX/ EVAL(3),EVECT(3,3)
	DATA TWOPI /6.2831853/
C
C	  THE FIELDS ARE IN THE ANTENNA SYSTEM
C	  TRANSFORM THEM TO THE GSE SYSTEM, EX, EY, EZ, BY ROTATING
C	  X AND Y, and INVERTING  Z gse is parallel to Z ant already,
C	   but opposite
C
	NSYS = 3
C	WRITE(79,*) ' '
C	WRITE(79,*) 'XFGSE CALLED--E DATA PUT INTO GSE SYSTEM, NSYS=3'
C
C	ANGLE =  -360.*SUNCLOCK/4096. - 45.       ! ANGLE SUN TO +EX AT END
	DANG = SPINRATE*360./SPSS/TWOPI
	ANGLE = AANG + NPT*DANG		  ! ANGLE SUN TO +EX AT START
	DO N = 1,NPT
		ANGLE = ANGLE - DANG
	        SINANG = SIND(ANGLE)
	        COSANG = COSD(ANGLE)
		XGSE(N,1) = XDATA(N,1)*COSANG + XDATA(N,2)*SINANG 
		XGSE(N,2) =-XDATA(N,2)*COSANG + XDATA(N,1)*SINANG 
		XGSE(N,3) = -XDATA(N,3)
	ENDDO
C
C	NOW XGSE ARE IN THE GSE SYSTEM
C
	RETURN
	END

